### ISSUE TITLE
429 errors in Logs

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#10014]
### Build

https://dev.azure.com/dnceng/public/_build/results?buildId=1880630&view=results

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section)

 ```json
 {
    "ErrorMessage" : "",
    "BuildRetry": false
 }
 ```

### Additional information about the issue reported

Can you please investigate what is going on with these failures

**Comment by ilyas1974** [comment]
This was reported by marcpaine in the CI Council channel.

**Comment by MattGal** [comment]
> Can you please investigate what is going on with these failures

@marcpopMSFT this is outside of our control, an HTTP 429 from an nuget package feed means that machine has made too many requests to that feed in a given amount of time.  Given what you're doing (virtually all of your Helix work items restore hundreds of packages, every execution), this is what I'd expect to happen.

Nuget restore is not something that responds well to the massive parallelism of Helix work item fan-out.  IIRC you were working on pre-populating a cache directory with your most-used packages, this would be one way to approach the problem.  If you can't avoid overloading the Azure DevOps package feeds, going back to forcing your tests to execute serially on the build machine might unfortunately be the best choice.

**Comment by marcpopMSFT** [comment]
@MattGal , my PR is ready to check in once I get a review (noting that it only works on windows now but that seems to be where most of the failures are). However, we've seen a very high number of 429 errors this week (much higher than last week). Do we have a contact on AzDO we can ask whether they changed their throttling logic? Since Monday we've been struggling with this and while it used to happen occassionally, it's now happening in nearly every PR (maybe we just need a weekend with no traffic to let things ease up). We've also seen a lot of builds fail to connect to machines after 45 minutes queued.

Here's my pre-population PR if we want to try it.
https://github.com/dotnet/sdk/pull/25055

**Comment by marcpopMSFT** [comment]
Here's an example of 8 legs timing out getting build machines: https://dev.azure.com/dnceng/public/_build/results?buildId=1881801&view=logs&j=e20c368f-1578-58c3-3fcd-dd02a0b0ce39

**Comment by MattGal** [comment]
> Do we have a contact on AzDO we can ask whether they changed their throttling logic?

I sent you their DRI email address on Teams, if you'd like to follow up with them.  I'm fairly certain 

> Here's an example of 8 legs timing out getting build machines: https://dev.azure.com/dnceng/public/_build/results?buildId=1881801&view=logs&j=e20c368f-1578-58c3-3fcd-dd02a0b0ce39

This is correlated to, but not caused by the same thing.  People are running a LOT of builds right now.  These builds often perform NuPkg restores, and there is both per-client/IP and overall throttling being applied to the feeds.  There's just a lot of work going through the system now.

One thing that I'd point out is that for pipelines in the "public" project you're fully entitled to be using the much fast, never-hits-this-problem AzDO Hosted agents like windows-2019/windows-2022/ubuntu-2004/etc.  Unless you need some image customization, this should be significantly more performant (until a critical mass of people in dnceng listen to me saying this :) ) as well.

**Comment by ilyas1974** [comment]
We believe this issue has been resolved. Closing this issue.
