### ISSUE TITLE
Create guide with code samples for GitHub apps

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#10200]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

There have been a variety of recent requests for PATs for bots for GitHub automation. GitHub user bots are not an ideal choice for this. They have poor permission scoping. GitHub Apps are much better for these cases, and automation code that works with a PAT will work just the same with an app, making it ideal for pre-testing.

There is a lot of confusion around what an app is, how it works, and how to create one. We should create a quick guide with code samples to help folks out.

**Comment by ChadNedzlek** [comment]
Here's a pretty rough sample of the steps necessary to authenticate: https://gist.github.com/ChadNedzlek/01bbcf02e9c819f61e097ff8549771cf

Note this is for a single repository, which I assume for most simple applications, is all that's needed.  (Otherwise you need to get a different istallation token/client for each repo)

**Comment by Chrisboh** [comment]
I feel that between Chad's example and the documentation found [here](https://docs.github.com/en/developers/apps/getting-started-with-apps/about-apps) users should have enough information to understand and create an App.  If you feel that anything is missing, please feel free to reopen.
