### ISSUE TITLE
Response status code does not indicate success: 429 & 503 

### ISSUE THREAD

**Issue by jeffschwMSFT** [dotnet/arcade#10202]
### Build

https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=1911423

### Build leg reported

Build / Windows_NT / Windows_NT Build_Release / Run Tests in Helix

### Pull Request

https://github.com/dotnet/sdk/pull/26882

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [x] Open the failing build above and investigate
- [x] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section)

 ```json
 {
    "ErrorMessage" : "",
    "BuildRetry": false
 }
 ```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by MattGal** [comment]
@jeffschwMSFT there's two things going on here. 

- There was clearly a degradation in performance for our AzDO package feeds, between this one and reported separately by Dan M in the past day
- The SDK tests do a LOT of package restoring, and HTTP 429s are a natural side effect especially when other situations (like the HTTP 503) 

I don't think this one makes sense as a "Known Issue" since the 429s are expected and there's nothing in the build pipeline log that would be helpful to aggregate this, and @marcpopMSFT has already been hunting down the 429s.  If you disagree let's chat on Teams, otherwise I think this should be closed.

**Comment by MattGal** [comment]
Closing; feel free to ping me to discuss or reactivate.
