### ISSUE TITLE
Docker Containers used for build not in MoT reports

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#10247]
Per conversation with Michael Simons, it appears that the containers we use for non-helix jobs are not showing up in the report data. We need to investigate.

**Comment by dkurepa** [comment]
This is something I recently became aware of (I didn't know we used docker for building too). We're missing this data because it's not in the Jobs Kusto table, we will have to do more scraping to get it. If a build is using docker, it will have an 'Initialize containers' job, where we can find the dockerTag for the used image (https://dev.azure.com/dnceng/public/_build/results?buildId=1919439&view=logs&j=ccbaf6f6-fd8d-5aed-75bd-0b95b0aa330d&t=abf8e74c-f6dc-4403-a02b-1f8e0fcf047a)

**Comment by dkurepa** [comment]
pr to include Docker containers in Kusto: https://github.com/dotnet/arcade-services/pull/1969

**Comment by dkurepa** [comment]
The docker Image Names have been added to the TimelineRecords Kusto table. They only exist for columns with the "Initialize containers" name

**Comment by dkurepa** [comment]
PR to include this new data in our outputs: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/25002

**Comment by ilyas1974** [comment]
I have verified that this information is being collected and is now available within our reports.
