### ISSUE TITLE
Decommission DNSB-RHEL* build agents 

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#10632]
FYI @lbussell  / @crummel / @MichaelSimons 

Today, the dnsb-rhel machines (4 in total: 2 each 7&8) are constantly flagged for not being fully patched.  They're also only used 
We have the capacity to make build images out of RedHat 7 and 8 Azure Gallery images, and our build pools already use D4_v3 as the VM size so performance should not be impacted significantly.

What is proposed:
- [ ] Create Build.Redhat.7.Amd64 and Build.Redhat.8.Amd64 build images
- [ ] Try out source-build pipelines against these machines
- [ ] (Depending on the outcome of step 2) delete the custom build pool and VMs here

This also has the side effect of allowing more than 2 concurrent source build jobs at once.

**Comment by MichaelSimons** [comment]
@MattGal, what kind of timeframe do you see for this?  I ask because of https://github.com/orgs/dotnet/projects/101.  I am pushing for us to utilize docker container in our RHEL CI legs.  They would still require a RHEL build agent because of licensing constraints.  If we had the containers in place, the only requirement on the build agent is the ability to run a docker image (e.g. podman is installed)

**Comment by lbussell** [comment]
@MichaelSimons I think your link is broken.

I think the work Michael is talking about is for 6.0+. We only use these RHEL agents for 3.1 Servicing CI right now, I think. I think that if we want to decommission these, there are 3 options:

1. Wait until 3.1 goes out of support and then decommission the agents.
3. Set up RHEL build images like @MattGal suggests and decommission the agents now.
4. Decommission the agents now and don't run RHEL CI on 3.1 since it is very unreliable at the moment. However they might be unreliable because they are static machines and not VMs.

**Comment by MichaelSimons** [comment]
> @MichaelSimons I think your link is broken.

Apologies, fixed.

**Comment by MattGal** [comment]
After discussing with @lbussell and @crummel , I am just going to delete these four machines.  Per @crummel  : "Especially if there's official RHEL queues now I'm willing to kill them off.  all we're really using them for right now is 3.1 servicing and I have to file an ICM every month because the Azure Security Pack stuff fills up the disk and we end up not being able to run any builds or even log in.  If we want to revive RHEL CI for servicing official queues are a way better solution"
