### ISSUE TITLE
Too Much Noise

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#10639]
Oof

![image](https://user-images.githubusercontent.com/47990216/187310212-b815b0e8-42ca-4d07-8a27-5c8ff7fab014.png)

**Comment by AlitzelMendez** [comment]
Check: https://github.com/dotnet/sdk/pull/27724/checks
Example build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=7714&view=results

**Comment by AlitzelMendez** [comment]
This is the pr: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/25737

But let me know what you think about this change.
On this change I update the "equal" check, so it checks the url ,because we were duplicating the build URL even though it was happening on different steps, so if the errors happen on a different build, we are going to show it too, which I think is the expected , also if it hits different known issues, we are going to show all of them 

This means that for build errors this is going to look like this: 
![image](https://user-images.githubusercontent.com/6895254/189961986-f2f02330-9d4c-4d3e-b1a5-19015bdd5db2.png)


I am a little hesitant about this change but at the same time I think is closer to what people is expecting of: I don't want to see known issues

**Comment by ChadNedzlek** [comment]
I wonder if making this a collapsed list would work, so you can see all 19 of them or whatever, if you want.

**Comment by AlitzelMendez** [comment]
closing as this was rolled out but I think it's worth to explore on: https://github.com/dotnet/arcade/issues/10931
