### ISSUE TITLE
Azure WorkItem Processor not linking issues 

### ISSUE THREAD

**Issue by garath** [dotnet/arcade#10641]
It was reported that the AzureDevOpsWorkitemProcessor is not appending GitHub links to the original AzDO Workitem. Investigate!

Example issue: https://github.com/dotnet/arcade/issues/10623

**Comment by adiaaida** [comment]
Lemme know if you'd like me to take a look at this Dtu. :)

**Comment by adiaaida** [comment]
Wait, this was 100% related to the fix here: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/commit/d22e5d469d5c50507ef2af25e76e7403ac13b0c2?refName=refs%2Fheads%2Fmain. I will wait until the rollout is complete and run another test

**Comment by adiaaida** [comment]
Github's graphql query inconsistencies strike again!

```
mutation {
    updateProjectV2ItemFieldValue(
      input: {
        projectId: "PROJECT_ID"
        itemId: "ITEM_ID"
        fieldId: "FIELD_ID"
        value: { 
          text: "Updated text"        
        }
      }
    ) {
      projectV2Item {
        id
      }
    }
  }
```

vs

```
mutation {
    addProjectV2ItemById(input: {projectId: "PROJECT_ID" contentId: "CONTENT_ID"}) {
      item {
        id
      }
    }
  }
```

We were failing to add an issue to the project because addProjectV2ItemById returns an `item` object. Naively, I just assumed that I'd made a mistake when making the first change, and updated everything to use an `item` object. But updating the field returns a projectV2Item.... for some reason. So now updating the fields are failing. Which blocks everything. I'm going to make the following changes:

1. Add a try/catch/finally so that if the issue is created, we update the azdo linked issue (or maybe just rearrange the code)
2. Fix the bug in the graphql/objects that we maintain for the queries.

**Comment by adiaaida** [comment]
This is now working
