### ISSUE TITLE
[Known issues] Report with impacted build is missing from known issues

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#10770]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

**Comment by AlitzelMendez** [comment]
could you please provide more details on this one? share an issue with this problem? 


I am still working on the test known issues, but it is not working yet because of this: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/25583 I already fixed it but is going to roll out until next week :/. I don't know if you refer to those one or it is a different problem

**Comment by AlitzelMendez** [comment]
I think this is the same as: https://github.com/dotnet/arcade/issues/10682
but I will wait for Ulises before closing

**Comment by ulisesh** [comment]
You're right, all the issues I found with missing report have only test known issues

Closing as a dupe of #10682
