### ISSUE TITLE
Lots of runtime tests timing out / failing

### ISSUE THREAD

**Issue by dkurepa** [dotnet/arcade#10907]
Hello, we had reports of major runtime test failure: https://github.com/dotnet/runtime/issues/75830. Might be an infra issue on our side

**Comment by MattGal** [comment]
Aside from updating LibMSQuic on our linux images to the latest public version at the request of @wfurt (this rolled out last Weds, 9/14),  I see no evidence that this specific work item timeout is caused by DncEng.   @dkurepa do you have any other data that has pointed you in this direction?

**Comment by karelz** [comment]
Some failures are also in System.Globalization.Tests -- https://github.com/dotnet/runtime/issues/75830#issuecomment-1250878707
Also note, that the System.Net.Quic happened prior to updating LibMsQuic -- at least since 8/31 (older logs are gone).

**Comment by MattGal** [comment]
> Some failures are also in System.Globalization.Tests -- [dotnet/runtime#75830 (comment)](https://github.com/dotnet/runtime/issues/75830#issuecomment-1250878707) Also note, that the System.Net.Quic happened prior to updating LibMsQuic -- at least since 8/31 (older logs are gone).

Understood.  I think investigating on a repro machine from the [helix-repro-vms](https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/d60c2e3b-00e6-48f3-a069-542c17981e1f/resourceGroups/helix-repro-vms/providers/Microsoft.DevTestLab/labs/helix-repro-vms/overview) DTL makes more sense than opening an FR issue.

- LibMSQuic has only been available on our RHEL 7 machines since the 8/17/2022 rollout; all its tests were skipped before this date for platforms without it, which was all of them.
- Only two non-RHEL-7 runs are listed in your list of runs.  In at least [one](https://dev.azure.com/dnceng-public/public/_build/results?buildId=14249&view=results), this test didn't fail at all, rather a bunch of JIT tests
- For me, this points to a problem with either the tests or the product functionality itself on RedHat 7

If even a cursory investigation using the repro-vms DTL shows we have a misconfiguration on our machines, I remain eager to address it.   I think given this is a test that can only have run for a single month, running in a run where no other work items timed out (even the four which ran on the same machine), the onus of the initial investigation falls to your team.

**Comment by ilyas1974** [comment]
After you have completed your investigation, please let us know and we would be happy to help you.
