### ISSUE TITLE
User study feedback: Truncated data is confusing

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#10913]
Because we're limited on how many characters we can show on a check, we decided to limit how many error results we can show on it. Unfortunately, this has caused confusion with customers who aren't noticing the links to "8 other errors" amongst the rest of the noise on the page. Some of the feedback included sentiments along the line of "if I'm not able to see all the error messages, I'm going to have to look at Azure DevOps anyway", which defeats the point of presenting error messages. 

Feedback: 
- "For tests, if we have more than 100 distinct test failures (or more than we can display on the page), don't display any, but provide links to the tests page instead. Should help to see the full magnitude of test failures."
- "Summary table for the test details. Name of test, branch. Need to be able to quickly scan it. But if it's like two tests that are failing, it doesn't need to be condensed, but a summary table of multiple tests would be helpful."
- "If it doesn't fit on the one page, then I have to look at other stuff anyway. Should this just be a summary instead?"

Suggestions: 
- If we have more errors than we can display on a screen, display a summary instead with links to the builds for investigations. 
- Possibly present as a table for easier readability.

**Comment by riarenas** [comment]
>Possibly present as a table for easier readability.

That sounds like it'd make the space issue worse. markdown tables take a bunch of extra characters

**Comment by ChadNedzlek** [comment]
Yeah, markdown tables are... rough, and very limited. :-(  This one is mostly limited by our requirement to use markdown, I'm not sure what better options we have here. Showning _none_ of the errors would be most unfortunate.

Builds errors tend to cause more errors, especially when so many legs are involved, so we are very frequently going to have more errors that we can show. We chose to show the "most important" errors, because the general rule in build land is that if you fix the first error, you, more than likely, will fix all the errors, so you don't actually need to look at all of them.  (It's weird if you got all the way to PR and somehow manage to introduce a bunch of real, unique build breaks that aren't related to each other).

**Comment by ChadNedzlek** [comment]
I'm curious why the multiple places we already present the information isn't working... we say in at least 3 places the number of tests that fail.  Which should be scannable quickly enough.

What information is being scanned for... what scenario is needing to be accomplish that we might be able to help with?  Knowing 400 v 4000 tests failed doesn't, to me, seem to help understand what I need to do.

**Comment by MichalStrehovsky** [comment]
The scannability of the test results page greatly improved recently - in the past it was very busy with a lot of text of various heading levels. I think stopping the reporting of test failures as additional build failures helped a lot. Now it's reasonably easy for me to glance at it top to bottom and know where I stand.

**Comment by missymessa** [comment]
We're going to focus efforts on collapsing sections (https://github.com/dotnet/arcade/issues/10931). If readability is still an issue after collapsing, we can revisit other solutions.
