### ISSUE TITLE
User study feedback: Custom ordering of sections 

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#10929]
Some of the feedback I got was around how some folks preferred a different order of sections (e.g. some wanted to see their test failures first, some wanted the ongoing infra issues section at the bottom [there's action to take there, so they felt this information wasn't useful at the top]), and some felt the current ordering was sufficient. 

This might not be something we are able to do for the current DevWF epic, and there are some data concerns about it (since we'd have to store their preferences somewhere), but I think some customers would find Build Analysis more useful if they were able to customize the ordering of the sections.

**Comment by ChadNedzlek** [comment]
We don't know who is looking at it, unfortunately, so we'd have to configure it at the repository level, which is pretty rough.  Doing it based on the author of the PR could be awkward, because people look at PR's they didn't make, and the order changing more or less arbitrarily (from the visitors perspective) would cause a lot of usability troubles (a bit win in UX is that users can find what they expect to find _where_ they expect to find it... having to visually search for something every time costs a lot of time/cognitive load).

It if was a live webpage, and we knew who was looking at it, and could rendering it the same way for the same person every time, sure, that could work (though then we still need a whole configuration storage system).

It's also worth noting that in a "normal" PR, really only one section should have any information in it... if the build failed, there won't be any tests (because tests won't run if the build doesn't work). If tests ran, there shouldn't be any build failures. And I think we are overusing "critical infra issues", and that's causing a lot of dissatisfaction there with issues that don't have anything to do with your PR.

Especially once we make stuff collapsable and more concise... I don't think we should do this, and I propose closing this issue in light of that (we should focus on making what is there more digestible).

**Comment by missymessa** [comment]
Doesn't fit right now. Sorry!
