### ISSUE TITLE
User study feedback: Link to Stage/Job/Task

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#10986]
Build failures include a granular breakdown of each stage. Example: 
<img width="506" alt="image" src="https://user-images.githubusercontent.com/47990216/191865359-684d8aca-6922-46b5-a04c-6f95f061bff1.png">

Users would appreciate if we could link to the stage/job/task, if possible. 

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
- Build Analysis: Added link to Stage/Job/Tas

**Comment by ChadNedzlek** [comment]
Interesting, the link is there (it's the [Log] button on the specific error), which has the added benefit of taking you to the actual line that failed (rather than making you scroll through the entire log to find the error).  But I... guess we could make the other thing a link to (it'll be a lot of characters in our limit, since azdo links are pretty long, but we can definitely make each piece of the header a different link to a different scope in the heirarchy).  I do think that will make people less likely to click the _more_ useful log link though, which is sad...  Maybe we should go the other way and unlink the build name, so that they are more likely to find the "good" link (and that saves us characters). Sometimes less is more. :-)

**Comment by missymessa** [comment]
They like the link to the build, though, so we should leave it (the build number, however, some have said they don't find that value useful at all)

**Comment by ChadNedzlek** [comment]
Did people find the "[Log]" link?  I wonder if the build link being so prominent is making them miss the useful thing, and then they "like" the build link because it's better than nothing.

**Comment by missymessa** [comment]
I think the [Log] link was getting lost. It's sandwiched between a symbol and a bunch of "goo" (as one user put it), which is the line that caused the error. One person did remark on it. I think it's also unclear where that link will take the user to.

**Comment by ChadNedzlek** [comment]
Hrm. I wonder how we can make it better... Maybe if we move the link to the first error up into the header... somehow? (Or make the "step" really be the link to the log line, and then remove the [Log] link, since no one is seeing/using it).

**Comment by missymessa** [comment]
Linking to the step would probably be helpful (or whatever the leaf node is on that path)

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/27729
