### ISSUE TITLE
Remove Incredibuild component from build images

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#11111]
From https://github.com/dotnet/core-eng/issues/14620. Not used, and this removes a possible external dependency that could fail when VMs/builds start.

### Release Note Description
Remove Incredibuild from DncEng Visual Studio images

**Comment by michellemcdaniel** [comment]
@mmitche can you give us some data about the issues this is causing?

**Comment by mmitche** [comment]
When we did an analysis of what URIs the build accessed, we saw this was happening at some point during arcade's build. Since incredibuild shouldn't be required by any of our repos, this is mostly about hygiene and cleanliness.

**Comment by michellemcdaniel** [comment]
What we discussed in Triage is that this might be something that is installed by default as part of VS and removing a workload could cause unintended issues. @MattGal

**Comment by michellemcdaniel** [comment]
@riarenas has some history context on this. Gonna put in FROps for now, because it's likely going to require a DDFun IcM

**Comment by MattGal** [comment]
This does not require a DDFUN IcM.  The Incredibuild component comes from the --includeOptional flag included here: https://dev.azure.com/devdiv/XlabImageFactory/_git/XlabImageFactory?path=/artifacts/Windows-VisualStudio-Bootstrapper/Windows-VisualStudio-Bootstrapper.ps1&version=GBmain&line=53&lineEnd=54&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

We can make PRs to this repo, and use different artifacts from this repo by modifying the JSON files inside dotnet-helix-machines' "base-images" folder.

However, it's probably a very bad idea to remove the "--includeOptional" flag from this PS1 as the tail of other removed components that come from unsetting this flag (which would also be variable by VS version, 2017/2019/2022).  Further, we can't include the `--remove` argument since this artifact only includes the default "install" verb.

Instead I think we should just augment the "`windows-vs-workloads`" artifact to include a new "RemoveWorkloads" parameter, and feed it the following component names:

```
Component.IncredibuildMenu
Component.Incredibuild
```

This leaves us a quick way to carefully remove things that come in from optional packages later, as this sort of problem is likely to come up again.

**Comment by MattGal** [comment]
These workloads are now removed (and spot-checked to be so) from every VS installation, as well as the artifact updated to be able to --remove arbitrary workloads during modification.  Will be in images for use on 1/25/2023

**Comment by MattGal** [comment]
Rolled out last week, closing.
