### ISSUE TITLE
[Maestro] Automate Maestro rollout

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#1115]
Automate the Maestro rollout to int as well as prod.

**Comment by markwilkie** [comment]
@ChadNedzlek - is this something you're working on as part of the arcade-services work?

**Comment by ChadNedzlek** [comment]
I stuck it in that epic. I'm hoping to be done today.

**Comment by mmitche** [comment]
@ChadNedzlek What's left here?

**Comment by ChadNedzlek** [comment]
I believe the web stuff is almost ready, here's what's not ready yet:
* Call the firewall bypass ps1 script to allow us to interact with the SQL
* Call BAR to report the build as part of the release, so the Tasks.dll (the only one consumed by anyone) using the BlobPublish.pushproj

**Comment by mmitche** [comment]
Thanks.  Do you have an estimate when you think it will be done?  Basically I'm thinking that we will need a few rollouts to iron out the last kinks before preview2, and we probably want to have dependency flow stabilized within the first week or two of Jan.  So having the rollout ready to go before EOY is necessary.

**Comment by ChadNedzlek** [comment]
Right now onboarding is a priority, so this isn't my top priority.  I wrote the "poke a hole in the firewall and then patch it up" script, so that's probably only a few minutes.

However, the BAR upload requires using Maestro.Tasks.dll, which currently doesn't work (if you reference the targets in there, it just crashes with an invalid file path), so I need to make changes into arcade, get those published, then pull that new arcade into arcade-services.

With my current priority set, that's probably at least a week out, if not longer (the odds of my changes to the publish task in arcade being correct are near zero, and the turn around on that is going to be very slow).  Someone more familiar with arcade/darc/maestro could probably do it in a day or two.

**Comment by ChadNedzlek** [comment]
The issue about the targets file is here: https://github.com/dotnet/arcade/issues/1555

**Comment by mmitche** [comment]
This is now working for int.  I am going to clone the release for prod, and call it done.
