### ISSUE TITLE
SAS token for dotnetstage

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#11275]
See this conversation in the FR channel: https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1665682943006?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1665682943006&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1665682943006&allowXTenantAccess=false

Essentially, @mthalman would like a SAS token for the `dotnetstage` storage account. @alexperovich pointed out that this is doable, but the related access key is not managed by Secret Manager, so the access key and subsequent SAS token would need to be set up to be managed by Secret Manager. @mmitche suggests that https://github.com/dotnet/arcade/blob/main/.vault-config/dnceng-partners-kv.yaml would be a good place for these keys/tokens to live.

**Comment by alexperovich** [comment]
The actual storage key should very much not be in the partners kv

**Comment by mthalman** [comment]
I'll need to have this SAS token ready and available from a variable group at least a couple days in advance of our last 7.0 RTM build.

**Comment by ilyas1974** [comment]
@alexperovich where would you suggest we store this information for our partners?

**Comment by alexperovich** [comment]
The SAS token is fine to have in the partners kv, I would prefer not having the actual storage key there
________________________________

**Comment by MattGal** [comment]
I got some excellent guidance from @AlexPerovich and am working on this now.  
The sequence of stuff (in order to not break people) is:

1. Merge this PR: https://dnceng.visualstudio.com/internal/_build/results?buildId=2023424&view=results.  This boostraps a new vault ("dotnetstagekeys") to contain the keys needed for dotnetstage and dotnetchecksumsstage
2. Update the DotNet-DotNetStage-Storage variable group to use this new vault instead of the old one for the same secret names: https://dnceng.visualstudio.com/internal/_library?itemType=VariableGroups&view=VariableGroupView&variableGroupId=105&path=DotNet-DotNetStage-Storage.  This helps the ~4 pipelines which use this version of the variable not break.
3. Make a corresponding PR to Arcade adding dotnetstage-account-sas-read-token & dotnetchecksumsstage-account-sas-read-token to https://github.com/dotnet/arcade/blob/main/.vault-config/dnceng-partners-kv.yaml
4. Expose the values of dnceng-partners-kv as a dnceng/internal variable group
5. Work with @MThalman to ensure that this unblocks their scenario
6. Remove secret from EngKeyVault (will naturally stop working in ~6 months regardless)

**Comment by MattGal** [comment]
I'm going to close this as complete. It's difficult to be certain if the EngKV secret is still in use by some legacy build pipeline, so I will let it expire naturally. (will happen as soon as secret manager flips the key in use for the new vault)
