### ISSUE TITLE
AzDO "Bug" type WorkItems should also open arcade issues

### ISSUE THREAD

**Issue by michellemcdaniel** [dotnet/arcade#11313]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Many of the auto-created issues that our team needs to react to (CG, in particular) are opened as AzDO Bug WorkItems. Today, we only auto-create matching arcade issues for AzDO Task WorkItems. We should be able to handle both so that things opened against us aren't a surprise.

**Comment by garath** [comment]
I propose we teach the tool to open based on a tag. All of the TSA and CG auto-created issues add useful tags, so if the tool's config easily accepted a list then this is cake.

**Comment by missymessa** [comment]
Is there a downside to opening GitHub issues for all Bug types regardless of tags? I'm concerned we'll be making the process unnecessarily complicated (and if TSA/CG ever stop adding specific tags we look for, the process will be broken) if we only look for specific tags.

**Comment by adiaaida** [comment]
We'll need to create another service hook (I assume they could write to the same azure storage queue?) for "Bug" work item types. There is an option for "[Any]" for the service hook, but we already auto-create issues for RCA and UserSentiment issues, so we'd either have to remove that code or filter out RCA+UserSentiment (though they have different text boxes, which we have to handle separately, which is why we've done it they way we have). Bugs also don't have the various fields that tasks have for GitHub labeling. I don't know if that will matter.

**Comment by garath** [comment]
> Is there a downside to opening GitHub issues for all Bug types regardless of tags?

I'm mostly concerned about breaking the internal/public barrier with unnecessary abandon. Having an allow-list system feels safer. (Though the current mapping system is very sterile, so I could be talked out of this concern.) Also: This system could let us automate a bit more by adding them to the Operations/FR backlogs. 

I think it is a reasonable assumption that the tags will not change enough to break a system like this. TSA has been using these tags as long as we've been participating and they exist for automation like this.

**Comment by garath** [comment]
The administrative overhead of mirrored issues is a bit higher because we really need to manage two issues. The desync this causes is already apparent in Operations (are we the most forgetful epic? maybe. nevermind that. that's besides the point.) I suggest we also figure out how to mirror at least the "open" and "closed" states, and perhaps even the assignee, between AzDO and GitHub.

**Comment by missymessa** [comment]
> I'm mostly concerned about breaking the internal/public barrier with unnecessary abandon

@garath I'm not really groking this. Can you explain more.

**Comment by garath** [comment]
> > I'm mostly concerned about breaking the internal/public barrier with unnecessary abandon
> 
>  Can you explain more.

Sorry. I mean that tools that open issues in AzDO assume they're in an "internal Microsoft" environment. And our tool mirrors some parts of them to the public.

**Comment by missymessa** [comment]
Is the current process not obfuscating enough between our internal AzDO issues and public GitHub issues?

**Comment by adiaaida** [comment]
The current process, 99% of the time, just creates an issue called "Azure Boards Issue #1234" with a link to the work item

**Comment by ilyas1974** [comment]
@missymessa , I know you and @garath are currently working on changes to our github/azdo issue linking. Is this something that you are considering as part of that work?

**Comment by missymessa** [comment]
@ilyas1974 it wasn't on my radar. Is this still something we want to do?

**Comment by ilyas1974** [comment]
My experience says we don't need this as we do not get "bug" type workitems opened within AzDO.

**Comment by missymessa** [comment]
Then let's close this :)

**Comment by garath** [comment]
Sorry if I'm confused, feel free to correct me. It seems to me like this issue still applies.

1. This issue seems exactly related to changes we've been discussing as part of dotnet/arcade#13592.

2. CG issues, as an example, do open using the Azure Boards "bug" template. Example: [5104](https://dev.azure.com/dnceng/internal/_workitems/edit/5104).

**Comment by michellemcdaniel** [comment]
Stu is correct. The primary driving motivation for this issue was CG issues.

**Comment by missymessa** [comment]
Completed this!  

Created two new service connections in Azure DevOps for dnceng/internal to also send work item create messages to our the workitems queue (same process we use for the task work items that are created), and everything Just Worked(TM). Tested the process by creating this bug in Azure DevOps: https://dev.azure.com/dnceng/internal/_workitems/edit/5241, which in turn, created this issue in GitHub: https://github.com/dotnet/dnceng/issues/481

This change should allow CG issues that are created to be tracked in GitHub without needing to manually create issues for them. 

/cc @garath @ilyas1974 @dougbu

**Comment by garath** [comment]
What are the names and IDs of the new service connections?

**Comment by missymessa** [comment]
> What are the names and IDs of the new service connections?

I mis-typed. These are service hooks.
