### ISSUE TITLE
For a compile-time compat add synthesized private fields for a value type (struct)

### ISSUE THREAD

**Issue by andriipatsula** [dotnet/arcade#11347]
```C#
public readonly partial struct Memory<T>
{
    private readonly object _dummy;
    private readonly int _dummyPrimitive;

    // ...
}
```

Rules: https://github.com/dotnet/arcade/blob/9b1a1c07a5cdbd90183b702601d170822adbaa5f/src/Microsoft.Cci.Extensions/Writers/CSharp/CSharpWriter.cs#L195-L220

**Comment by andriipatsula** [comment]
This is solved with the Roslyn Api, class `CSharpSyntaxRewriter`

**Comment by andriipatsula** [comment]
`System.Reflection.Metatada,1.6.0` - 110 occurrence

**Comment by ericstj** [comment]
@andriipatsula you mentioned that you gave this a try and had difficulty implementing similar logic in GenAPI to synthesize these private fields.  Can you share what you tried?

**Comment by andriipatsula** [comment]
Hey @ericstj, I tried to adapt the implementation that exists in the CCi-based GenAPI; I searched for a corresponding API in the Roslyn (metadata and *Symbol definitions). But my solution was error prone. There are couple of extensions methods introduced and used in `Microsoft.CCi.Extensions`:
https://github.com/dotnet/arcade/blob/034aa38aefca48451af44494ad5c284780db90da/src/Microsoft.Cci.Extensions/Writers/CSharp/CSharpWriter.cs#L193-L264

Sadly, I didn't save the PoC I made.

**Comment by ericstj** [comment]
I would expect that algorithm should be possible to implement using Roslyn.  Even though it had CCI extensions, the things they were doing were straight forward type inspection and should be implementable on top of the Roslyn APIs.

Looks to me like it enumerates excluded fields.  It seems to check them for 3 things.

If the field's type is a generic parameter - preserve it.

It any field is a reference type, or another struct that contains a reference type (recursively) then add a dummy fields of both object and int types.

Otherwise, if any field is a non-empty struct then add a dummy int field.
