### ISSUE TITLE
Create a root `.gitignore` for the VMR

### ISSUE THREAD

**Issue by premun** [dotnet/arcade#11598]
There's no `.gitignore` at the moment and the VMR gets messy after building so we should put one in `tarball/content`.

**Comment by MichaelSimons** [comment]
Here are the issues to track fixing the underlying source of the modifications:

TextOnly Packages - https://github.com/dotnet/source-build/issues/2614
ExitCode - https://github.com/dotnet/source-build/issues/2307
RepoRoot - https://github.com/dotnet/installer/issues/14980
NoWarn - https://github.com/dotnet/source-build/issues/3117

@crummel - What do you think about the Tools, packages, and tools-local modifications?  If you agree can you open individual issues to refactor so that the _edits_ happen within the artifacts folder.  

The tests folder is also going to be included in this list - https://github.com/dotnet/source-build/issues/2793

**Comment by premun** [comment]
Since we have a `.gitignore` file now and we cannot influence the modifications with this, I will close this
