### ISSUE TITLE
Update staging signcheck

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#11602]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The staging sign check fails to download files because the pattern is incorrect. The pattern is: "<repo>/packages", where it should actually be: "<repo>-<repo-sha>/**/".

Furthermore, it's only trying to check packages today, and should be checking msis, zips, etc. signcheck does support this.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by michellemcdaniel** [comment]
I'd like to split this into 2 issues: 1) packages that we think are being validated aren't being validated because of a yml bug. That's an FR issue. 2) The feature work of checking msis, zips, etc, since for historical reasons those were skipped because signcheck wasn't doing it correctly or something (I don't remember exactly what).

**Comment by michellemcdaniel** [comment]
actually, just closing this in favor of https://github.com/dotnet/arcade/issues/7411
