### ISSUE TITLE
Add test result publishing to arcade templates

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#1195]
We should have test result publishing added to the arcade templates, probably configurable  via a variable of some sort.

/cc @chcosta

**Comment by chcosta** [comment]
If we're going down this path, then we may want to add artifact publishing as well to the Arcade templates so that, by default, if you're using arcade to build, we ensure your artifacts (logs) get published.

**Comment by jonfortescue** [comment]
@mmitche Is this for tests run on Helix or on the AzDO build machines? Or is it even more generic than that?

**Comment by jcagme** [comment]
I've just merged a PR which included a change to [publish tes results](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=vsts&tabs=yaml). Results look like [this](https://dnceng.visualstudio.com/public/_build/results?buildId=37836&view=ms.vss-test-web.test-result-details). 

To see the actual results, remove the filters where it reads "Outcome: Aborted (+1)" since in this run nothing failed and you'll see each of the test groups. If expanded, all the unit tests and when clicked. the run results.

**Comment by jcagme** [comment]
Yes and was not my intention to imply that, it was more of a FYI. Sorry if I caused confusion

**Comment by markwilkie** [comment]
@jonfortescue - can you confirm this is already being tracked elsewhere?

**Comment by jonfortescue** [comment]
@markwilkie No &ndash; I wasn't tracking this one since it wasn't Helix-related (by my understanding)

**Comment by markwilkie** [comment]
and fixed....:)

**Comment by markwilkie** [comment]
@jcagme - please update details on how this was fixed.

**Comment by jcagme** [comment]
Mentioned above in https://github.com/dotnet/arcade/issues/1195#issuecomment-434790925. Basically I just added the `PublishTestResults@2` task to arcade's .vsts-ci.yaml so test results are published to the "Test" tab of the build

**Comment by chcosta** [comment]
That only fixes this for Arcade.  I believe that this was initially about adding this to the common templates.

**Comment by chcosta** [comment]
This was added to the common templates in https://github.com/dotnet/arcade/commit/af5dae468879ee3a6b7f6f6916d63a09a894788e
