### ISSUE TITLE
[Darc] Use interface on top of ILocal and IRemote

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#1202]
https://github.com/dotnet/arcade/pull/1153#discussion_r228297823

**Comment by dagood** [comment]
I don't understand the name "type manager" in this context.

For something that sits on top of `ILocal` and `IRemote`, I'd expect an interface, not an abstract class. The hierarchy could be reworked, though, to have some abstract class on top and concrete `Local` and `Remote` implementations. (Abstract class would be holding any logic that's indifferent to local/remote, not sure if there is any.)

With how this issue is written now, I'm concerned it's just moving the flags into this new "type manager" to forward things on to implementations rather than creating an OO-style hierarchy that removes the flags.

**Comment by markwilkie** [comment]
closed - no longer relevant

**Comment by dagood** [comment]
The problem still exists exactly the same in arcade-services. I can understand cutting this due to priority though.

**Comment by markwilkie** [comment]
@mmitche ?

**Comment by mmitche** [comment]
@dagood There's really minimal overlap between local and remote operations (basically just get dependencies and update dependencies, both of which have different semantics between local and remote.  There's also only a small handful of places that need to handle both cases.
