### ISSUE TITLE
Add link to build analysis file on sentiment feedback issues 

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/arcade#12088]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Right now, it's hard to get the build analysis file related with sentiment feedback issue, to make this easier we should include the link to the build analysis file on the issue.  

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by ChadNedzlek** [comment]
This can be a little tricky, because sentiment feedback works for everything (there are already at least 3 places that use it), and getting "the file" can be tricky.  We could hard code some stuff, but there's quite a few things that should be included.
* The markdown file the user was looking at
* The JSON file that drove it (so that you can run the exe using that to regenerate the data)
* Other renderings that might have happened nearby (we've gotten a lot of complaints about things being wrong/stale when it's really that there was a new, correct version posted a few minutes later, but the user just didn't refresh, and that's a lot of logs to look through)
* Logs related to the rendering in question.

There is a WPF app here that gathers most of it for any given feedback: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service?version=GBsentiment-wpf&path=/src/dev-harnesses/build-analysis-feedback-viewer/DevWorkflowFeedbackViewer

**Comment by ChadNedzlek** [comment]
That might be a bit much to shove into an issue, but we could theoretically tweak the tool a bit and make it easier to obtain if we find that we are having to investigate these issues a lot.  I think _most_ of the time, the issues don't need much investigation, so I'd be hesitant to invest a lot of time in this.

**Comment by missymessa** [comment]
I think knowledge about this tool in our investigation documentation would probably achieve the same goal?

**Comment by ChadNedzlek** [comment]
Probably needs to not be a random branch in the repo.  No one else has been particularly interested in it before now, so I haven't bothered with the headache of checking it in. But if it's something we want to make part of a real process, then we should do that.  I don't know if a WPF app can be a "tool", so we might have to rejigger it into a command line thing, or have some other way to deploy it.

**Comment by AlitzelMendez** [comment]
I hesitated in putting it on the documentation because it's not part of the main branch so as you said that probably need to be the first step. 

I think for investigation purposes it would a lot easier to use than follow all the steps to get all the files that is the process I use right now.

**Comment by ChadNedzlek** [comment]
Yeah, the steps to get all the files are actually quite intense, which is why I wrote the little app.  It needs to query and cross reference a bunch of things from a bunch of different places.

**Comment by ChadNedzlek** [comment]
It even sort of tries to render the markdown files as HTML. It's not perfect, because "github" markdown isn't real markdown, but it at least gives you a feel for what it probably sort of looks like mostly. :-)

**Comment by missymessa** [comment]
If we wanted to make it more robust, we could update it to take in gist information to write the output to a gist so we wouldn't have to deal with subpar HTML :D

**Comment by missymessa** [comment]
Not doing this work for this epic. We have instructions for how to get this information (as difficult as it is) so we'll make do with that until we get a "deluge of sentiment feedback" :)
