### ISSUE TITLE
Adding new on-prem queues to alerting

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#12098]
We recently add some new on-premise queues that are not showing up within our monitoring system. I seem to recall that the queues need to be explicated added "somewhere". 

Can you please investigate and add the new queues? (I know the new perf queues, raspbian11 and macOS queues are missing). 
Also, can you please create a wiki on what needs to be done for the future?

**Comment by ilyas1974** [comment]
Here is the page in our monitoring I'm referring to - https://dotnet-eng-grafana.westus2.cloudapp.azure.com/d/queueOverview/on-premises-helix-queue-status?orgId=1

**Comment by MattGal** [comment]
I learned some stuff here and I think no actions are needed.  Specifically, this code :  https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines?path=/src/Monitoring/Operations.cs&version=GBmain&line=67&lineEnd=68&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents  copies the OSOBInventory Table maintained by @ilyas1974  into Kusto, and this table's contents are used in all cases for supporting these queries backing grafana. 

Since no action is needed but this won't be addressed until the next rollout (1/11) I will put it in "waiting for rollout?
