### ISSUE TITLE
Remove 'unattended-upgrades' package from Ubuntu build and test images 

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#12240]
See [this teams conversation](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1673470138651?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1673470138651&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1673470138651&allowXTenantAccess=false) for context.

We already update our package sources and run various update stuff when generating images, as well as rebasing off new Canonical gallery images when available.  Removing this package will prevent (the issue described below and in the Teams convo) from occurring.

Alternatively, we could try to modify the contents of  `/etc/apt/apt.conf.d/20auto-upgrades` and then run `dpkg-reconfigure -plow unattended-upgrades -f noninteractive` in a new artifact, but I'm unsure what the benefit over removing the package entirely would entail.

### Release Note Description
Prevent automatic upgrades in Ubuntu build and test images, which can impact machine reliability

**Comment by ericstj** [comment]
Brief summary here of what we noticed.  Ubuntu 18.04 images were being used by the dotnet/spark builds.  The very first thing their build would do is run an `apt` command, which was failing with `Could not get lock /var/lib/dpkg/lock-frontend - open (11: Resource temporarily unavailable)`.  We determined that this was due to a background process running `unattended-upgr` - which we surmise is the automatic update service in Ubuntu.  It seems like we shouldn't have automatic updates enabled for short-lived machines since that's a waste of resources and can interfere with builds.  Instead any updates should be applied to the image centrally.

**Comment by MattGal** [comment]
I verified today that this artifact is already removed by the linux-ubuntu-security-updates artifact which seems to be missing from the "build.ubuntu" images.  I'll try to just add it back there.

**Comment by MattGal** [comment]
this artifact is now added to all build.ubuntu.* images (and was already on test images) and will roll out tomorrow 1/25/2023

**Comment by MattGal** [comment]
Rolled out last week, closing.
