### ISSUE TITLE
Rollout Scorer is broken (no new scorecards since 1/11/23)

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#12384]
- [x] This issue is blocking 
- [x] This issue is causing unreasonable pain

Can't prepare Retrospective notes without scorecards from Rollout Scorer

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by jonfortescue** [comment]
yeet

**Comment by AlitzelMendez** [comment]
looks that this is related with this change: https://github.com/dotnet/arcade-services/pull/2150

following with @dkurepa to see if this is something that we can fix easily :)

**Comment by dkurepa** [comment]
Looks like somethings wrong with authentication to the key vaults, we fail somewhere in https://github.com/dotnet/arcade-services/blob/9f7f4e4d485483c704f3ebf1b7081ed216a1c1d3/src/RolloutScorer/RolloutScorerAzureFunction/RolloutScorerFunction.cs#L32-L33. I think the problem is that we are using `User Assigned Identity` in the Rollout Scorer Azure Function, and then we're trying to use the `DefaultAzureCredential` without giving it the `ManagedIdentityClientId ` (based on https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet). To solve this issue, we can either add the userAssignedClientId to the app (I'm not 100% sure if it can be public) or switch the Rollout Scorer Azure Function App to the System Assigned Identity

**Comment by riarenas** [comment]
Should we revert the change instead?

**Comment by dkurepa** [comment]
The change is needed because of component governance, we can't revert it

**Comment by riarenas** [comment]
If the options are broken code or being out of SLA in component governance, I think we should be out of date in component governance.

**Comment by dkurepa** [comment]
I switched the rollout-scorer-prod function app to the System Assigned Managed Identity, and assigned it the required roles in the Vaults it needs. We should see if this was enough during it's next run

**Comment by AlitzelMendez** [comment]
the secret problem was fixed, and I update the tables, so this should work, not sure if it's going to be validated today or until next week so moving to validate.

I created the scorer manually: https://github.com/dotnet/arcade/pull/12946

**Comment by missymessa** [comment]
Rollout Scorer automatically opened https://github.com/dotnet/arcade/pull/13071. Looks like it's working again, so going to close out this issue. Thanks all!
