### ISSUE TITLE
Build Analysis: Stop recording merge on red from unauthorized org

### ISSUE THREAD

**Issue by AlitzelMendez** [dotnet/arcade#12453]
While I was looking at our dashboard, mostly preparing them for the end of epic and making sure it was on place turns out that 
we have merge on red records from "Abuchtela" organization 
[Dashboard](https://msit.powerbi.com/groups/de8c4cb8-b06d-4af8-8609-3182bb4bdc7c/reports/8bdd4339-ea39-4e67-963a-fc44a450605b/ReportSection?ctid=72f988bf-86f1-41af-91ab-2d7cd011db47&experience=power-bi)
![dashboard_org](https://user-images.githubusercontent.com/6895254/217102985-2a654718-7a78-44f3-bbeb-b772725bfe73.png)

After taking a look at the code seems that we are not reviewing the "is this repo allowed" to record the merge on red metric

My plan is to filter these records from the dashboard to only track dotnet organization, and for the code part I have more questions, are we doing this intentionally? are we trying to have all the merge records from the organization and not only for the registered repos? @missymessa 

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by missymessa** [comment]
Looks like this user https://github.com/Abuchtela has forked arcade, maybe others, and that's what's getting picked up by Build Analysis. 

I'm not sure if we want to be restrictive to just repos in dotnet (for example, mono/mono was one that wanted to use Build Analysis, but because they're not building PRs in dnceng-public [or even dnceng], we couldn't make that work for them). This is a good discussion for our sync tomorrow!  

@garath and @ChadNedzlek do either of you recall any reason we should or shouldn't be restrictive to just dotnet repos, aside from the scenario I already mentioned?

**Comment by garath** [comment]
As long as the PR experience from the fork of a supported repository isn't affected, I think this is fine. Though I'm confused about how Build Analysis is noticing these merges if they're happening entirely outside of dotnet/arcade.

**Comment by ChadNedzlek** [comment]
If I recall correctly, when GitHub mentions the PR's associated with a "check", it's based _purely_ on the commit hash.  If someone merges main into their fork VIA a PR and that PR can fast-forward, that "check" now includes a "PR" (since it's a PR with the specified commit hash).  Checks are weird.

**Comment by AlitzelMendez** [comment]
Fixed the dashboard, everything else looks fine. closing :)
