### ISSUE TITLE
Automate removing a repository from the VMR

### ISSUE THREAD

**Issue by MilenaHristova** [dotnet/arcade#12489]
### Goal

Add a new command which will remove a repository from the VMR by
- remove the repository folder from the VMRs `src` folder
- remove the repository mapping from `source-mappings.json`
- remove the repository and its submodules records from `source-manifest.json` 
- remove repository entry in `git-info/AllRepoVersions.props`
- remove repository props file from `git-info` folder
- regenerate `README.md` and `THIRD-PARTY-NOTICES.txt`

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

### Release Note Description
If a repository mapping is deleted from source-mappings.json all files associated with this repository are deleted from the VMR

**Comment by premun** [comment]
@MichaelSimons I realized yesterday that a proper removal of a repository needs quite a few things to happen. I only realized that too late but also the GH UI wouldn't let me review your changes as there were too many so it's not possible to review it anyway.

We will have a process for removal then, I think it will be better this way.

@MilenaHristova I am also thinking whether we shouldn't trigger this when we notice an item was removed from source-mappings.json during a sync. But maybe that's a step 2.

**Comment by MichaelSimons** [comment]
Can you provide the workflow you envision with this?  I see coordination needed because the first bullet is done against the VMR and several of the others against installer.  For example, you must remove and commit the changes to installer prior to being able to remove the VMR source.

Is it plausible to scan for removed repos in the vmr-sync tool and remove the source?  Then the vmr-remove command would only operate against the installer repo.

**Comment by premun** [comment]
Originally, I thought that you'd run the tool manually and opening the PR (similarly to what you did yesterday).
But automating this would make sense too as I suggested in the last paragraph. This way we wouldn't have to care about removals at all and a removal of the `source-mappings` item would trigger that.
