### ISSUE TITLE
DOTNET_INSTALL_DIR is set by build.ps1 which leaks in to other builds

### ISSUE THREAD

**Issue by anurse** [dotnet/arcade#1253]
I noticed this while debugging #1251. The build script sets the `DOTNET_INSTALL_DIR` environment variable in the current shell (because I invoked `./eng/common/build.ps1` from a PowerShell instance) which means that when I go to a different repo in the same shell instance, it will use whatever resolution logic applied to the previous repo. This is particularly bad if the build script ended up using a repo-local `.dotnet` directory because now RepoB is using RepoA's local installation of dotnet.

This probably doesn't apply to the bash script because it will be invoked in a sub-process and can't affect the parent process' environment

**Comment by markwilkie** [comment]
This is definitely something we need to address.  @anurse - I'm not reading this as currently blocking, can you confirm?

**Comment by markwilkie** [comment]
Thanks @anurse.  We will do this, but likely after 12/14

**Comment by anurse** [comment]
Ping @chcosta @natemcmaster (this one is also an "annoyance" for ASP.NET adoption. Not blocking, but annoying)

**Comment by chcosta** [comment]
We're happy to take a fix to Arcade, barring that I think it's likely this will not be addressed until next year (not because it's not important but because there are quite a few other high-pri work items in progress at the moment).

Thanks for the ping though and continuing to surface these pain points is encouraged.
