### ISSUE TITLE
Arcade insertions fail on dotnet/templating -> release/6.0.3xx & release/6.0.4xx

### ISSUE THREAD

**Issue by YuliiaKovalova** [dotnet/arcade#12740]
### Build

https://dev.azure.com/dnceng-public/public/_build/results?buildId=187934&view=logs&j=2f0d093c-1064-5c86-fc5b-b7b1eca8e66a&t=d2b639a6-cb19-5f1f-66fd-8047f66b3026

### Build leg reported

Build

### Pull Request

https://github.com/dotnet/templating/pull/6178

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [x] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section)

 ```json
 {
    "ErrorMessage" : "Could not load file or assembly */tools/Microsoft.DotNet.Arcade.Sdk.dll",
    "BuildRetry": false,
    "ErrorPattern": "Could not load file or assembly *",
    "ExcludeConsoleLog": false
 }
 ```

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by oleksandr-didyk** [comment]
Updated the error description, taking a look at it

**Comment by oleksandr-didyk** [comment]
It seems that the MSBuild property pointing to the location of Arcade's tool DLLs is incorrect in the source-build intermediate, hence the exception of missing DLL in the logs.

Versions of the Arcade's intermediate up to [February 15th](https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-eng/NuGet/Microsoft.SourceBuild.Intermediate.arcade/overview/6.0.0-beta.23114.5) seem to have the correct path set (from [BuildTasks.props](https://github.com/dotnet/arcade/blob/5c3a03310692d0df2f844df417c4265914aa6b84/src/Microsoft.DotNet.Arcade.Sdk/tools/BuildTasks.props) inside the intermediate, second property): 

```xml
<Project>
  <PropertyGroup>
    <ArcadeSdkBuildTasksAssembly Condition="'$(MSBuildRuntimeType)' != 'Core'">$(MSBuildThisFileDirectory)net472\Microsoft.DotNet.Arcade.Sdk.dll</ArcadeSdkBuildTasksAssembly>
    <ArcadeSdkBuildTasksAssembly Condition="'$(MSBuildRuntimeType)' == 'Core'">$(MSBuildThisFileDirectory)net6.0\Microsoft.DotNet.Arcade.Sdk.dll</ArcadeSdkBuildTasksAssembly>
  </PropertyGroup>
</Project>
``` 

Versions after though, including the one used in this build, have the TFM missing from the path:

```xml
<Project>
  <PropertyGroup>
    <ArcadeSdkBuildTasksAssembly Condition="'$(MSBuildRuntimeType)' != 'Core'">$(MSBuildThisFileDirectory)net472\Microsoft.DotNet.Arcade.Sdk.dll</ArcadeSdkBuildTasksAssembly>
    <ArcadeSdkBuildTasksAssembly Condition="'$(MSBuildRuntimeType)' == 'Core'">$(MSBuildThisFileDirectory)\Microsoft.DotNet.Arcade.Sdk.dll</ArcadeSdkBuildTasksAssembly>
  </PropertyGroup>
</Project>
```

while the relative path of the DLL remained the same:
<img width="931" alt="image" src="https://user-images.githubusercontent.com/106967057/222111114-f09a06b4-402a-4236-b76f-691bb6c54dd6.png">

Since the source-code differs from what ends up in the intermediate, I'm guessing source-build somewhere alters the contents of the file / substitutes the file completely. I failed to find where exactly this is done though, so pinging @dotnet/source-build-internal for some help here

**Comment by mmitche** [comment]
That's pretty bizarre. The change on the 14th was an SDK update. I'm rerunning the commit before to eliminate any environmental factors that may have contributed. Super weird.

**Comment by mmitche** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=2125521&view=results

**Comment by mmitche** [comment]
The source build intermediate package from the older build looks fine.

**Comment by mmitche** [comment]
The replacement happens in https://github.com/dotnet/arcade/blob/release/6.0/eng/SourceBuild.props#L20-L39. The issue here is https://github.com/dotnet/arcade/commit/5c3a03310692d0df2f844df417c4265914aa6b84 removed https://github.com/dotnet/arcade/commit/5c3a03310692d0df2f844df417c4265914aa6b84#diff-6a28d92de8923be8821f2123541dc23c8ad0359c96117709e6d49e752c0303d2L8.

This means that the property is empty when we generate the file.

@MichaelSimons do you know whether this target is still required in 6.0? As far as I can tell, it's gone in 7.0 onwards and I can't find a similar target elsewhere.

**Comment by MichaelSimons** [comment]
I don't have the history here.  @crummel - do you know?

**Comment by MichaelSimons** [comment]
By looking at things, I think it is still required in 6.0.

**Comment by crummel** [comment]
Yeah, it looks like we still have a couple places where we specifically change the TFM for source-build in 6.0, e.g. https://github.com/dotnet/arcade/blob/release/6.0/src/Common/Microsoft.Arcade.Common/Microsoft.Arcade.Common.csproj#L5 and https://github.com/dotnet/arcade/blob/release/6.0/src/Microsoft.DotNet.Arcade.Sdk/Microsoft.DotNet.Arcade.Sdk.csproj#L5.  We've taken a different approach in some cases (I think F#) where we change the path in the Sdk.props/etc files but if I remember correctly we couldn't do that here because we didn't have access to `DotNetBuildFromSource` or the Arcade path was not actually variable at the time, something like that.

**Comment by JanKrivanek** [comment]
@MichaelSimons will the inability to update the arcade for 6.0.3xx and 6.0.4xx Templating branches cause issues during the source build? In another words - might this be perceived as servicing blocker? (@mmitche, @wtgodbe)

**Comment by MichaelSimons** [comment]
> @MichaelSimons will the inability to update the arcade for 6.0.3xx and 6.0.4xx Templating branches cause issues during the source build? In another words - might this be perceived as servicing blocker? (@mmitche, @wtgodbe)

No, source-build is only supported in the 1xx feature band.

**Comment by JanKrivanek** [comment]
Thank you for the answer!
Oh - that's great! So I suppose that this arcade upgrade blocker does not need to be considered servicing blocker. If anybody believes otherwise - please let us know.

**Comment by YuliiaKovalova** [comment]
Hi everyone,

any updates on it? Do we really need to merge these insertions to dotnet/templating repo?

**Comment by mmitche** [comment]
It's not critical for the next release, but I would like to solve the issue.

**Comment by YuliiaKovalova** [comment]
thank you for the fix
