### ISSUE TITLE
Test artifacts and build log links are missing from failing helix tests

### ISSUE THREAD

**Issue by ericstj** [dotnet/arcade#13066]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

I noticed that dotnet/runtime test failures no longer have links to the console logs and dumps gathered by the tests.  

This hinders troubleshooting.

Sometimes I'm noticing that the console log link is also missing from the build output, which means the only way I can find it is to fetch it from helix API via job list (using runfo).

Here's an example.
Test result missing artifacts in artifacts tab:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=230208&view=ms.vss-test-web.build-test-results-tab&runId=4357056&resultId=132916&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

It says it's not a helix test, which is clearly incorrect since the Debug tab comments show the helix information.

Build Log missing link to output for test:
[Pipelines - Run 20230406.46 logs (azure.com)](https://dev.azure.com/dnceng-public/public/_build/results?buildId=230208&view=logs&j=cb131f87-d5af-5ecc-6e5f-6dc86994859c&t=76503e0a-8c41-542c-43da-63a4758a95b0&l=104)

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by riarenas** [comment]
I did some debugging of the extension that populates these:

* We are failing to parse the JSON provided to this function: https://github.com/dotnet/arcade-extensions/blob/b8d5ebab90f5665e9d14b8b05b434a22e6f97f43/src/helix/index.html#L104. Since that parsing fails, the code ends up going down the path of "this isn't a helix test, because the information that we use to determine whether it's a Helix test is missing".
* A sample of the failing json blob that is failing to be parsed is `"{\n  &quot;HelixJobId&quot;: &quot;0b3b1991-c1da-4049-b8ca-125b7e033b76&quot;,\n  &quot;HelixWorkItemName&quot;: &quot;System.Numerics.Vectors.Tests&quot;\n}"'. The failure to parse is due to the quotes being encoded.

Still trying to figure out what caused this to change, but it looks like replacing the encoding with simple `\"` to escape the quotes works with the extension.

**Comment by riarenas** [comment]
So far it looks like Azure DevOps changed this underneath us. Even test results posted back in March using an older API version are suffering from the same html encoding in the comment https://dev.azure.com/dnceng-public/public/_apis/test/Runs/3789466/results/100013?api-version=5.0.

**Comment by riarenas** [comment]
No disclaimers surrounding the comment in their docs https://learn.microsoft.com/en-us/rest/api/azure/devops/test/results/get?view=azure-devops-rest-7.0&tabs=HTTP#testcaseresult

**Comment by riarenas** [comment]
I have updated the extension to the latest version that works around this breaking change from Azdo and the artifacts tab is working now.

Will keep an eye on this for a couple of days to make sure things stay working.
