### ISSUE TITLE
windows.vs2017.amd64(.open) image generation timing out during git installations

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#13231]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Due to https://github.com/dotnet/arcade/issues/13230 the two images in the title are timing out during the installation of git.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [x] Internal Infrastructure Improvements
### Release Note Description
No release note.

**Comment by riarenas** [comment]
As a workaround we are marking these images as unmonitored

**Comment by dougbu** [comment]
:eyes:

**Comment by riarenas** [comment]
As far as we understand things, this has happened before, and happens when the version of git that comes with VS in the base image is newer than the version we try to install manually.

My suggestion for how to deal with this issue in order of least to more painful investigations:
*  Perform an update version bump for the windows-git artifact according to the instructions: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-machines?path=/artifacts/windows-git/README.md
* If that is not enough, we'll need to create some machines with the same base image and try to apply the git artifact manually to see which dialog is causing the problems, and why dhandler hasn't been enough to not have the installer hang.

**Comment by dougbu** [comment]
Every image on http://helix.dot.net I checked contains `git` v2.4.0. Since that version bump was included in the same commit (https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/commit/c1512d0e997cb9d8fcc839f1ac463aee6a604cd0) as our fix for the timeout and this issue affected some of the queue configurations I checked, all is well and we've rolled the fix out. Closing&hellip;
