### ISSUE TITLE
Implement Semantic Versioning Task

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#134]
Work to be done is implement what is described here https://github.com/dotnet/arcade/pull/108 as a MSBuild Task

**Comment by JohnTortugo** [comment]
@mmitche , Could you please take a look at the schematics below? I am not sure what should be the **format of the version string** (or what would be the default value for the field) when some of the optional fields are empty.

Major -> Required; integer; Fail if 0
Minor -> Required; integer;
Patch -> Required; integer;

Prerelease -> Optional; string; **what to do if empty?**
Shortdate -> Optional; integer; **what to do if empty?**
Builds -> Optional; integer; **what to do if empty?**
ShortSHA -> Optional; string; **if empty: retrieve from GIT.**

**Comment by mmitche** [comment]
> Prerelease -> Optional; string; what to do if empty?
> Shortdate -> Optional; integer; what to do if empty?
> Builds -> Optional; integer; what to do if empty?
> ShortSHA -> Optional; string; if empty: retrieve from GIT.

Prerelease - If ommitted, then all fields in the prerelease section (PRERELEASE.SHORTDATE.BUILDS) should be empty.  Error if otherwise (not semver2 compatible)

Two additional points:
- We also need a pivot to produce a stable (not containing dates or build metadata) version number.
- Wes also noted the short date is actually a combo of months since a base date and days.  See https://github.com/dotnet/arcade/pull/108#discussion_r184209456.

I'll make some further clarifications in my doc, but keep going for now.  We'll probably need to tweak bits here and there.

**Comment by mmitche** [comment]
BTW, I would make a separate work item for bringing in the git functionality.

**Comment by JohnTortugo** [comment]
Pushed new changes. Dropped the use of custom task. PTAL.

**Comment by maririos** [comment]
Issue moved to [dotnet/core-eng #3445](https://github.com/dotnet/core-eng/issues/3445) via [**ZenHub**](https://www.zenhub.com/)

**Comment by DoCode** [comment]
@maririos it's a very interesting discussion and implementation.  
But now it's hidden from me since you move this to the dotnet/core-eng.  
How can I continue to follow this issue and details?

**Comment by maririos** [comment]
@DoCode thanks for pointing that out. I will reopen then
