### ISSUE TITLE
BuildAnalysis: Link information of the failing job in addition to the failing configuration

### ISSUE THREAD

**Issue by ivanpovazan** [dotnet/arcade#13984]
Not sure if this belongs to the dotnet/runtime repo but it is related to what kind of information is provided to the users when analysing `runtime` pipeline failures.

### Description

In case of test failures the `BuildAnalysis` page on GitHub, displays the following:

<img width="989" alt="Screenshot 2023-08-17 at 14 27 12" src="https://github.com/dotnet/runtime/assets/55002338/b35bd117-935e-4e0b-a564-64e9447d7e9a">

Which has great and really helpful features like: 
- Links to the failing test console logs, details, artifacts etc
- List of failing configurations
- Quick access to create infrastructure or test failures issues

However, what feels like missing is the link to the failing job (associated with the failing configuration).

### Problem

When we want to further analyse, how was the specific configuration built and in which setup (especially on mobile devices) it is usually difficult to find the failing job, just based on failing configuration name. 

For example from the build analysis overview shown above:
For the tests that are failing on configuration: `coreclr windows arm64 Checked no_tiered_compilation @ Windows.11.Arm64.Open`
It is a bit problematic to find that the actual job that failed is: `coreclr Pri0 Runtime Tests Run windows arm64 checked`

### Proposal

I believe that by having a link to the failing job associated with the failing configuration, in both `BuildAnalysis` (on GitHub) and `Tests` (on Azdo), would speed up the process of analysing the cause of failures and would in general improve user experience.

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
- Added link to failing test in build analysis failing configuration

**Comment by AlitzelMendez** [comment]
**Note:**  There was some concern about adding the links to the configurations because of the use of characters, after doing some analysis every link will use around 150 characters and taking into consideration the average number of failing configurations and the number of displayed tests, this is something we can afford doing. 

for the `build analysis` GitHub view  side I will add a link to the failing test from where is easy to get to the artifacts tab which have all the logs information.

For example
<img width="508" alt="image" src="https://github.com/dotnet/arcade/assets/6895254/f8b8a45a-7849-4c2e-a220-8785d4158f83">

the first link will redirect you to:
<img width="815" alt="image" src="https://github.com/dotnet/arcade/assets/6895254/cd5a3c91-4b25-490b-84ea-3505b24cc98e">

from which you can also navigate to:
<img width="764" alt="image" src="https://github.com/dotnet/arcade/assets/6895254/1880b936-6566-4d81-a738-c482ec61ac40">

@ivanpovazan  could you please provide more information about what is your expectation on AzDO tests? are you expecting to see a link to where?

**Comment by AlitzelMendez** [comment]
@ivanpovazan, any thoughts on this?

**Comment by AlitzelMendez** [comment]
Hi @ivanpovazan,

thanks for sharing all this info, this is exactly the information I will add, the UI looks different because the job is expanded, but sounds that we are on the same page, I will check in this change and update you when is available.

**Comment by AlitzelMendez** [comment]
this has been rolled out, closing
