### ISSUE TITLE
Microsoft.SymbolUploader dependent on Microsoft.IdentityModel.Clients.ActiveDirectory

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#14028]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Microsoft.SymbolUploader, which hasn't seen much change in the last few years, has a dependency on Microsoft.IdentityModel.Clients.ActiveDirectory, which CG doesn't like. This is going to cause issues in a few days when we hit the fix SLA for it.

### Release Note Category
- [ ] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements

**Comment by ViktorHofer** [comment]
Microsoft.IdentityModel.Clients.ActiveDirectory has been deprecated since Dec 2022 and should be replaced with [Microsoft.Identity.Client](https://www.nuget.org/packages/Microsoft.Identity.Client/).

Also, SymbolUploader has other dependencies that are either stale, deprecated or problematic for other reasons, i.e. a very old version of Newtonsoft.Json.

That is one of the remaining dependencies that transitively bring-in the .NET Standard 1.x dependency graph. We should significantly update SymUploader as soon as possible.

**Comment by mmitche** [comment]
@tommcdon

**Comment by ViktorHofer** [comment]
BTW, how does that internal repository even build without receiving tons of CG errors? Presumably CG isn't enabled in that repository?

**Comment by mmitche** [comment]
It hasn't built in a long time.

**Comment by tommcdon** [comment]
cc @hoyosjs @mikem8361

**Comment by missymessa** [comment]
This was updated and a new build was released yesterday. Closing. 

Related PRs in Arcade: 
- https://github.com/dotnet/arcade/pull/14042
- https://github.com/dotnet/arcade/pull/14043
