### ISSUE TITLE
"error MSB4057: The target "Test" does not exist in the project." for some projects 

### ISSUE THREAD

**Issue by ryanbrandenburg** [dotnet/arcade#1464]
I get the following errors when trying to move extensions to arcade and run `.\build.cmd`:
```
error MSB4057: The target "Test" does not exist in the project.
D:\dd\Extensions\src\DependencyInjection\DI.Specification.Tests\src\Microsoft.Extensions.DependencyInjection.Specification.Tests.csproj : error MSB4057: The target "Test" does not exist in the project.
```

The offending branch can be found [here](https://github.com/aspnet/Extensions/tree/rybrande/Arcade).

**Comment by markwilkie** [comment]
cc/ @chcosta

**Comment by chcosta** [comment]
Ack, I've been working offline with Ryan on this.  Also, cc @riarenas as FYI

**Comment by chcosta** [comment]
@ryanbrandenburg worked around this by defining `<TestRunnerName />` in the offended projects.  I feel like this is a bit of a hack.

There should probably be some way to just completely opt out of being a test project, but I believe this target is currently forcing the projects back into the list of test projects and causing the failures.

https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/Tests.targets#L65

Ryan's hack works because this gets skipped...

https://github.com/dotnet/arcade/blob/187829842d4173c290bf64373498e91aedd91270/src/Microsoft.DotNet.Arcade.Sdk/tools/Tests.targets#L78

This is mostly from memory of looking into this last week (oops) so I could be off on what was happening here but it seems we need some better way to opt out of testing.

**Comment by ryanbrandenburg** [comment]
@chcosta that's how I remember it too. I expected this to work by simply setting `<IsTestProject>false</IsTestProject>`, but if I recall correctly the test targets and props were getting pulled in before the .csproj, so they didn't get the property from there.

**Comment by tmat** [comment]
Is `Microsoft.Extensions.DependencyInjection.Specification.Tests.csproj` not a test project?

**Comment by ryanbrandenburg** [comment]
Not one that we want to run tests against. It is a package full of tests that we ship for people to test their implementations against. That is, it has tests, but they are meant to be run by an end-user, not by our CI.

**Comment by tmat** [comment]
I see. Can you rename the project to not end with `.Tests`? Something like `.ManualTests` would do.
https://github.com/dotnet/arcade/blob/master/Documentation/ArcadeSdk.md#project-name-conventions

**Comment by tmat** [comment]
Alternatively you can add `Directory.Build.props` file next to the project and set `IsUnitTestProject` to `false` there.

**Comment by ryanbrandenburg** [comment]
Renaming the package is a customer-effecting breaking change, not the kind of thing we like to do just due  to infrastructure stuff.

We'll leave my hack in there for now and I'll watch this issue for further development.

**Comment by tmat** [comment]
You don't need to rename the package, just the project. But if you don't want to do that, setting `IsUnitTestProject` in `Directory.Build.props` is the right fix.

**Comment by jcagme** [comment]
@ryanbrandenburg did you end up setting `IsUnitTestProject` or ` continued with your hack of<TestRunnerName />`?
