### ISSUE TITLE
Arcade official build still publishes even when a leg fails

### ISSUE THREAD

**Issue by ericstj** [dotnet/arcade#1475]
Not sure if this known / expected / covered by https://github.com/dotnet/arcade/issues/1179 but I thought I'd file it since I noticed it.

This morning's official build failed the linux leg due to running out of disk space.  The windows release leg still succeeded and published which I found unusual (though actually convenient for me). 🤷‍♂️ 

/cc @jcagme

**Comment by ericstj** [comment]
See https://dnceng.visualstudio.com/internal/_build/results?buildId=53475 and select "Attempt 1"

**Comment by markwilkie** [comment]
cc/ @jcagme

**Comment by jcagme** [comment]
Yes, we currently publish regardless of the outcome of the complete build. When we publish, we are only pushing to our internal `dotnetfeed`. 

If you check the "Publish to Build Asset Registry" leg did not execute since there was a failed leg. Things in the Build Asset Registry (BAR) mandate the versions that are flowed to other repos. In the case of the failed build, it won't.

Currently, we are working on making a better use of the data in the BAR to make the publishing process better. Spec is here: https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/AsyncPublishing.md

Did this answer your question?

**Comment by ericstj** [comment]
I didn't have a question it was just something I noticed.  If you are OK with that behavior then close this issue.
