### ISSUE TITLE
[TestReporting] [Helix] support reporting test results from jUnit xml format

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#1485]
I know we've talked about this in person a few times, but don't see an issue tracking this.

ASP.NET Core needs to run tests for Java and NodeJS which produce test results in the jUnit xml format. It would be great if Helix test reporting could handle jUnit. Currently, only xunit XML reports are supported.

cc @alexperovich @HaoK

**Comment by markwilkie** [comment]
thoughts @alexperovich and @ChadNedzlek ?

**Comment by markwilkie** [comment]
Adding this as a priority for post Preview 2.  (@natemcmaster let me know if you think you'll need this sooner)

**Comment by ChadNedzlek** [comment]
It will probably be easier once we move to using Azure DevOps for all test reporting, since we won't have to change any many places. Currently the "XUnitness" is sort of rampant in the code. But if we only report to DevOps, then we just need @alexperovich's uploader thing to be able to tell that these are JUnit and parse them differently to do the upload.

**Comment by natemcmaster** [comment]
> uploader thing to be able to tell that these are JUnit and parse them differently to do the upload.

@ChadNedzlek that would be okay with me. AzDO supports all of the formats we use -- junit, xunit, and vstest. If it's just a matter of detecting and specifying when publishing to AzDO, this likely won't be much work.

**Comment by ChadNedzlek** [comment]
I believe that information is baked into the "Run Test" task.  We aren't running the tests with that task, because it doesn't work on most of the OS's we need to run tests on, so we need to parse the results ourselves into the format the API uses, so it's not quite that simple.  But those formats generally aren't that far apart, usually it's just names of elements that are different. So we can copy/paste the "parse XUnit stuff" into "parse JUnit stuff", and somehow know which of the two we are expecting (presumably that will have to be argument to the job that gets sent).

**Comment by natemcmaster** [comment]
Ok, I misunderstood. I thought you might be leveraging the TestResultsPublisher.exe tool used under the hood by [Publish Test Results](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=vsts&tabs=yaml) task.

**Comment by alexperovich** [comment]
We have a bit of python that reads the xml file and massages it into the format that azure devops expects. The way I wrote it makes adding another format a simple matter of creating another file that understands that format.

**Comment by Chrisboh** [comment]
@alexperovich I am moving this over to your Epic as we should track this as part of your work in making the test results showing up in AzDev
