### ISSUE TITLE
Please allow direct control over variables that cause arcade to DO something

### ISSUE THREAD

**Issue by rynowak** [dotnet/arcade#1616]
See: https://github.com/dotnet/arcade/blob/ffc7a871add67b229c7fd41ad1cdff41da926312/src/Microsoft.DotNet.Arcade.Sdk/tools/Publish.proj#L25

All of these variables: `PublishToAzure`, `PublishToSourceBuildStorage`, `PublishToSymbolServer` will not allow me to configure their value since they always explicitly set a value. It would be really useful if I could just control these values, either by injecting a `.props` file or by making them conditional.

It's good to have sensible defaults, but I think this logic is much too smart for its own good. Issues that I'm currently trying to solve:
1. I need **both** symbol publishing and BAR publishing, which requires an extra build step because I can't configure these things directly.
2. I want to disable symbol publishing for debug builds because I don't need it for anything. This requires a crazy level of workaround because I can't configure these things directly.

**Comment by tmat** [comment]
In general, I am against adding more customization to the build than necessary. 

Any customization should be driven by scenarios. If there is a scenario that's not possible today then let's discuss how to enable such scenario, instead of allowing tweaking of random variables. You can consider these variables to be private. You are effectively asking to make them public APIs, which warrants some discussion.

> I need both symbol publishing and BAR publishing, which requires an extra build step because I can't configure these things directly.

Can you explain why do you need this? The current policy is that all artifacts produced during the .NET Core stack build are published to BAR, from where it will flow to official channels like NuGet.org, symbol servers, etc. Why do you need to circumvent this process?

> I want to disable symbol publishing for debug builds because I don't need it for anything. This requires a crazy level of workaround because I can't configure these things directly.

It's actually not that difficult. See e.g. https://github.com/dotnet/symreader/blob/master/azure-pipelines.yml#L29, where I configured the build to only publish in an official Release build.

**Comment by rynowak** [comment]
> Any customization should be driven by scenarios. If there is a scenario that's not possible today then let's discuss how to enable such scenario, instead of allowing tweaking of random variables. You can consider these variables to be private. You are effectively asking to make them public APIs, which warrants some discussion.

Yes. I am specifically asking that for the features in `Publish.proj` to expose an on/off switch that isn't inferred from any other variable. I would describe the *current state* as "tweaking of random variables".

MSBuild allows developers to implement a really ridiculous level of hackery. You can customize almost anything done by dotnet/arcade via unsupported hacks. Trying to make the built in feature set hostile to customization just means that workarounds have to be more arcane than necessary. We are trying to onboard into dotnet/arcade, and not everything is in a state that works well with our existing stuff, or our requirements. I would buy this argument if arcade was *done* - but much of what we need is still being rationalized. 

> Can you explain why do you need this? The current policy is that all artifacts produced during the .NET Core stack build are published to BAR, from where they **will flow** to official channels like NuGet.org, symbol servers, etc. Why do you need to circumvent this process?

I need this now. I keep hearing that this will work better in the future, I'm trying to get unblocked now.

**Comment by rynowak** [comment]
> This I agree with. The hard part is that what is "hostile" to one party is "normal and sane" to another. 

Independent of my immediate needs, I also want to make an argument that providing a **direct** on/off for features rather than trying to infer based on presence of access tokens/feeds/etc is a more straightforward path. This can provide a better experience because rather that trying to infer a feature's state from the *required arguments* you can just do what the developer asked for and *validate the required arguments*. 

Providing a direct on/off for features that you expect to be present in 'official builds' also integrates nicely with the pipelines templates that arcade provides. Maybe my brain thinks of these things differently than others, but to me it's a much strong statement of intent to say "I expect to publish to BAR" than to say "I have an access token".

If I'm debugging why a target didn't run, and I see:
```
<Target Name="Foo" Condition="'$(EnableFoo)'=='true'>
</Target>
```

I can go to the logs and look for `EnableFoo` *without* any more steps, I can look in my pipeline definition and see that I'm passing in `EnableFoo`, etc.

**Comment by markwilkie** [comment]
@rynowak - I like the thinking.  You're saying use scenario based "switches".  The "isshipping" is kinda close to this thinking...but also "infers" quite a bit.  Also, some of it would be a documentation thing - e.g. "isshipping" means this and this and this....  The point being that we wouldn't want those pieces decoupled - which, is probably part of the discussion here.  That is, a possible disagreement on what should be decoupled verses not....

Maybe a concrete next step would be to get a proposal on table for how you'd like to see the publishing work from a property perspective?  

We're currently working on an actual AzDO release pipeline (plan: https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/AsyncPublishing.md) and because of this refactor, this is probably a decent time to think more (maybe even better??) about this.

**Comment by mmitche** [comment]
fyi, there is a direct on/off for these via the command line.  In msbuild, anything passed on the command line via /p:foo=bar will override whatever happens to be set in the property/targets files.

**Comment by rynowak** [comment]
>Maybe a concrete next step would be to get a proposal on table for how you'd like to see the publishing work from a property perspective?

If publishing is going to be driven by BAR or by release pipelines in the future then it doesn't seem super relevant... so this is a bit of a thought experiment. In terms of the actual properties that are there, I think the design is great. The only thing that I would add is allowing a `Publish.props` that's imported after properties get their default values.

My general feedback is that providing a simple on/off property for features supports many virtues. Combining that with `Foo.props` that's imported by the relevant arcade targets, I think that's everything we'd ever need for almost every scenario. If you **really** want to keep a developer from messing with certain properties, you can define them after importing `Foo.props`. As Matt pointed out, this can be worked around also 😆 



> fyi, there is a direct on/off for these via the command line. In msbuild, anything passed on the command line via /p:foo=bar will override whatever happens to be set in the property/targets files.

Thanks, I'm currently using this to work around this problem.

**Comment by ryanbrandenburg** [comment]
I'm currently dealing with this and `[Artifacts*PackagesDir](https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/RepoLayout.props#L61-L62)`. In order to now break out Release pipelines we have to have the package directories be named "product" and "internal" instead of "Shipping" and "NonShipping", and the only way I can seem to achieve that is to pass those parameters as cmdline properties (thanks for pointing that out @mmitche). The kind of workarounds I have to do every time Arcade won't let us set our own properties really make a mess of things (in this case I have to create a wrapper around each build.* script which can do the right thing).

**Comment by tmat** [comment]
Is there an issue with changing Release pipelines to use the new names?

The point of Arcade is to unify on common concepts and naming across our repos. Customizing these defeats the purpose of Arcade.

**Comment by ryanbrandenburg** [comment]
@natemcmaster can give you the full description of why we need this.

**Comment by natemcmaster** [comment]
I'm fine just working around Arcade on this one. IMO basically everything about arcade's handling of artifacts is a hot mess, and I'd rather keep what we have working than switch to something which doesn't.

**Comment by markwilkie** [comment]
@natemcmaster - when you get a minute, let's chat about the "hot mess".   :)  Now that we're coming up on preview II, it's about time to circle back around on things like this and make sure they're sorted.

**Comment by jcagme** [comment]
Could we follow up on https://github.com/dotnet/arcade/issues/1912 and close this as dupe given that the two issues are related?

**Comment by markwilkie** [comment]
Seems reasonable.  @ryanbrandenburg do you think #1912 covers this scenario as well?

**Comment by ryanbrandenburg** [comment]
Mostly, yeah.
