### ISSUE TITLE
[darc/maestro++] Maestro should update existing PRs instead of generating new ones

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/arcade#1728]
I enabled dependency flow on aspnet/Extensions yesterday. Today, I have [4 PRs from the bot](https://github.com/aspnet/Extensions/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+author%3Aapp%2Fdotnet-maestro). Can we make it re-use existing PRs instead of producing many?

![image](https://user-images.githubusercontent.com/2696087/50913784-f9288200-13e9-11e9-8862-c030ea5f776b.png)

**Comment by alexperovich** [comment]
We support subscription batching which is exactly what you want. You need to enable it on each subscription. I don't know if we added support to darc for this, but subscriptions have a "batchable" setting. @mmitche did we enable this through darc?

**Comment by mmitche** [comment]
We have not enabled this through darc yet.  All the existing subscriptions are marked as non-batchable.

**Comment by natemcmaster** [comment]
I don't think this is resolved. How do I use this new setting?

**Comment by natemcmaster** [comment]
cc @bricelam @rynowak

**Comment by mmitche** [comment]
You can use the swagger REST api to patch the subscriptions to be batchable:

https://maestro-prod.westus2.cloudapp.azure.com/swagger/ui/index.html#/Subscriptions/Subscriptions_Create

And then ensure there is a repository merge policy set for the repo/branch combo (since when you batch subscriptions 
https://maestro-prod.westus2.cloudapp.azure.com/swagger/ui/index.html#/Repository/Repository_SetMergePolicies

There will eventually be support for this in darc. but it's lower priority at the moment.

**Comment by natemcmaster** [comment]
Can we leave this open until there is documentation and darc support? I suspect other teams will hit this, too. 

Also, from my perspective as a user, "use the REST API manually" feels equivalent to being told "the compiler is busted, but you can write machine instructions instead." Sure, it's a solution, but it means the tools have a deficiency.

**Comment by markwilkie** [comment]
I agree this should be documented - even if it's ugly.

The tools (darc in this case) is still deficient in some ways.  Pretty sure everyone agrees on that point, but we'll get there.

**Comment by mmitche** [comment]
This is done.
