### ISSUE TITLE
Automate validation of symbols

### ISSUE THREAD

**Issue by shawnro** [dotnet/arcade#1874]
Ensuring that symbols are correct is something that is currently done manually.  We should evaluate whether/how we can automate the checks to ensure everything exists and is correct

cc:  @markwilkie, @mmitche

**Comment by markwilkie** [comment]
@mikem8361 - is symbol validation part of the stuff you wrote?  I seem to recall I asked this before, but I can't remember your answer, sorry....

**Comment by mikem8361** [comment]
Yes, I work on the symbol uploader and downloader support. I didn't integrate into Arcade.  As far as this work item I have no clue when we will have any time to do this.

**Comment by mikem8361** [comment]
Symchk doesn't work with portable pdbs or xplat bins. I'm not sure the exact requirements they are asking for.

**Comment by dagood** [comment]
I wrote a custom tool a while back that is used on release days to validate symbol availability and correctness. Things it does that symchk (as far as I know) doesn't:
* Look for cross-indexed CoreCLR symbols and fail if they aren't correct.
  * This is very important, because it breaks many debugging scenarios when we don't do it right. This is broken unfortunately often.
* Substantial retry logic. The services can be flaky at times.
* Parallelization.
* Niceish and detailed report formatting.

However, my tool doesn't:
* Have a reasonable codebase or way to execute it.
* Handle portable PDBs (as far as I know).
* Handle xplat bits.

A few related issues:
* https://github.com/dotnet/arcade/issues/173 "[Publishing] Automatic post-build symbol availability validation"
* https://github.com/dotnet/arcade/issues/167 "[Publishing] As a product owner, my official build verifies symbol packages are complete"

**Comment by danmosemsft** [comment]
cc @leculver in case he has prior art.

**Comment by markwilkie** [comment]
@mikem8361 - Arcade aside, what's the recommendation for verifying symbols?

**Comment by mikem8361** [comment]
It is not scheduled or funded.  And yes I hope others can help out.

**Comment by leculver** [comment]
@danmosemsft I have a ton of prior art and can put together symbol server tools pretty quickly on demand (minus portable PDBs, I don't touch those).  However, the tool @dagood has sounds like exactly what I'd put together if it was needed.  I'd rely on his art here.  We can always clean it up/code review if the above "_Have a reasonable codebase or way to execute it._" is a concern.

Also, as an FYI to all:  One requirement for checking in any code into the Visual Studio ecosystem (changing VS itself) is to have PDBs and managed binaries on the **internal symbol server http://symweb** for Watson/security related purposes (any symbol server other than symweb doesn't count).  It's also devdiv policy that any shipping managed binaries be indexed this way.

(Also I'm heads down for a while, but happy to contribute if it doesn't need to be driven by me or take up too many hours.)

**Comment by markwilkie** [comment]
Thanks @leculver!  Sounds like between @mikem8361, @dagood , and @leculver, we should be able to get some shared symbol validation stuff put together.

I'll make sure this gets triaged appropriately.  Expect to hear more from me relatively soon.

**Comment by dagood** [comment]
[ReleaseTool/Documentation/push-symbols.md](https://devdiv.visualstudio.com/Personal/_git/dagood?path=%2FReleaseTool%2FDocumentation%2Fpush-symbols.md&version=GBmaster&_a=preview) is my tool's doc, and here's [Program.cs](https://devdiv.visualstudio.com/Personal/_git/dagood?path=%2FFetchSymbolPackageSet%2FCheckArchived%2FProgram.cs&version=GBmaster&_a=contents) and the [current baseline](https://devdiv.visualstudio.com/Personal/_git/dagood?path=%2FFetchSymbolPackageSet%2FCheckArchived%2FResultCsvInfo.cs&version=GBmaster&line=67&lineStyle=plain&lineEnd=171&lineStartColumn=1&lineEndColumn=1). It uses [this copy of clrmd with some hacks](https://devdiv.visualstudio.com/Personal/_git/dagood?path=%2FFetchSymbolPackageSet%2Fclrmd&version=GBmaster), but Git history there doesn't include https://github.com/Microsoft/clrmd/compare/master...dagood:check-symbol-existence.

**Comment by markwilkie** [comment]
related to #1933
