### ISSUE TITLE
There should be support to easily choose the name of the binary log

### ISSUE THREAD

**Issue by zsd4yr** [dotnet/arcade#1978]
Opening at request of https://github.com/dotnet/arcade/pull/1972#pullrequestreview-199839802

Our repository calls build.ps1 during multiple phases in the same job. during CI. We would like a way to easily name the resulting binary log. We do this in order to separate out the build steps to be more modular and clean.  See the example below 

```yml
       # Build
       - script: eng\cibuild.cmd
          -prepareMachine
          -configuration $(_BuildConfig)
          $(_OfficialBuildIdArgs)
          -build
        displayName: Build

      # Run unit tests
      - script: eng\cibuild.cmd
          -configuration $(_BuildConfig)
          $(_OfficialBuildIdArgs)
          -test
        displayName: Run Unit Tests

      # Create Nuget package, sign, and publish
      - script: eng\cibuild.cmd
          -configuration $(_BuildConfig)
          -bl SignPackPublish
          $(_OfficialBuildIdArgs)
          -sign $(_SignArgs)
          -publish $(_PublishArgs)
        displayName: Pack, Sign, and Publish
```

We do not wish to change the way we are building to call build.sh instead (see workaround https://github.com/dotnet/arcade/blob/master/azure-pipelines.yml#L133)

**Comment by tmat** [comment]
What is the reason you need to run cibuild.cmd multiple times? Why not invoke it once with all `-build`, `-test`, `-sign` and `-publish` arguments? The script is designed to run these in phases already. There should be no need to separate them to multiple invocations.

**Comment by zsd4yr** [comment]
It is cleaner in the CI to run them separately. It also makes the logs easier to read, especially for our external contributors.

**Comment by AdamYoblick** [comment]
What Zach said. We’d like the CI steps to be clear and doing it all in one step isn’t. When there’s a failure, it’s much easier to track down when you see the test step failed for example. 

Being able to specify the log name seems like a pretty standard request in my opinion. :)

**Comment by tmat** [comment]
I disagree. Please follow Arcade guidelines and build everything in one step. We are not gonna support this pattern.

**Comment by safern** [comment]
Chiming into this old discussion. In corefx we also split our restore and build step. The reasons to do that, is because in our official builds for example, we need to restore some internal tools like `IBCMerge` which in order to achieve the restore has to be done as an extra build step using the `dotnet` task to restore. 

The `dotnet` task, needs a `dotnet` CLI to be installed in the machine and in the path. However, we didn't want to use the `DotnetCoreInstall` task as an extra step, as we didn't want to end up with two different sources installing dotnet core and potentially when we update our dotnet version in the `global.json` then we would need to update the version on the YAML. 

Of course, we could add an extra step into our YAML file, that reads the version from `global.json` and sets a variable and we use that in order to install the `dotnet` through azure's task, but to me, that seems like too much overhead in order to avoid splitting the restore and build task, just because we don't want to allow repos to specify the binlog name.

Also, it is nice to be able to have a binlog of a `-test`, `-restore`, `-build` phase if repos want to split it out, when getting one binlog for all the steps together, for repos like corefx where we build 400 or so projects, they can get quite large and they're really hard to look at afterwards.

I just opened a PR exactly doing what people tried to do in the past here: https://github.com/dotnet/arcade/pull/3859

cc: @ViktorHofer @ericstj

**Comment by AdamYoblick** [comment]
Just for reference, the solution we went with after @zsd4yr did some experimenting was to pass /bl to cibuild.cmd which overrides the binary log file.

Unfortunately, the artifacts dir is defined in build scripts and is not accessible in yaml, so we ended up hardcoding it in the interest of speed.

For example:

```
        # Run Unit Tests
        # Tests are run with /m:1 to work around https://github.com/tonerdo/coverlet/issues/364
        - script: eng\cibuild.cmd
            -test
            -configuration $(_BuildConfig)
            $(_OfficialBuildIdArgs)
            /p:Coverage=$(_Coverage)
            /bl:$(BUILD.SOURCESDIRECTORY)\artifacts\log\$(_BuildConfig)\Test.binlog
            /m:1
          displayName: Run Unit Tests
```

**Comment by AdamYoblick** [comment]
Ahh I should have read your PR - yeah we did what you mentioned there 😆

**Comment by chcosta** [comment]
> in our official builds for example, we need to restore some internal tools like IBCMerge which in order to achieve the restore has to be done as an extra build step using the dotnet task to restore.

Does anyone remember why internal tools isn't just supported directly by Arcade? I presume that's because of some authentication issues that needed to be handled separately?  @jcagme, does anything you're doing with feed authentication (or other recent changes) make this more reasonable to be a thing that Arcade just supports?  ie, pass some property to Arcade and it will try to restore from your specified secure feed?

**Comment by tmat** [comment]
@safern Why does this not work? https://github.com/dotnet/arcade/blob/master/Documentation/ArcadeSdk.md#restoring-internal-tools

**Comment by safern** [comment]
> @safern Why does this not work?

That works and this is how we actually restore internal tools in corefx, but as I stated above, you need to have a dotnet CLI installed in order to run the restore step:

https://github.com/dotnet/corefx/blob/937e7d6d7eb6f1413aa48d14961d8f0c8a061e0e/eng/pipelines/corefx-base.yml#L136-L146

> The dotnet task, needs a dotnet CLI to be installed in the machine and in the path. However, we didn't want to use the DotnetCoreInstall task as an extra step, as we didn't want to end up with two different sources installing dotnet core and potentially when we update our dotnet version in the global.json then we would need to update the version on the YAML.
> 
> Of course, we could add an extra step into our YAML file, that reads the version from global.json and sets a variable and we use that in order to install the dotnet through azure's task, but to me, that seems like too much overhead in order to avoid splitting the restore and build task, just because we don't want to allow repos to specify the binlog name.

**Comment by tmat** [comment]
`NuGetCommand@2` doesn't use dotnet cli. It uses NuGet.exe that's provided by the Pipelines Task.
