### ISSUE TITLE
[darc/maestro++] Product diff command

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2112]
We want a product diff command.  Basically this would take two input shas/repos (like get-dependency-graph does), then determine the commit diff between the two trees.

This should filter dependency update commits so that we only see 'real' changes.

/cc @jcagme

**Comment by jcagme** [comment]
Great! @nguerrera and I talked about generating something like this that would be included in a "report" but in this case we would take a sha included in the graph and compare it to HEAD in <branch> to determine what commits are in the repo but didn't make it to that graph.

@nguerrera since we don't have an ETA for this you could still move forward by constructing the `compare ...` link that we talked about.

**Comment by mmitche** [comment]
@jcagme @nguerrera I'm almost done with the "how far behind" bit (it's not hard).  It will be included in the firts coherency PR which i hope to have out today.  It would be great to find out what the actual functional diff between two trees is though.

**Comment by nguerrera** [comment]
Awesome. I haven't had time yet to write the thing @jcagme and I discussed on Frioday, so the more that can be provided from the system itself the better. :) Maybe we can chat today about what this will do and what extras we might want?

**Comment by mmitche** [comment]
Sounds good to me.

**Comment by jcagme** [comment]
If at all possible could we talk after lunch so I'm in? :)

**Comment by markwilkie** [comment]
@mmitche - did this get addressed w/ your latest PR?

**Comment by mmitche** [comment]
No.  This has yet to be implemented.

**Comment by mmitche** [comment]
Duplicate of #2167
