### ISSUE TITLE
Look into ApiCompat bug with wrong Core Assembly

### ISSUE THREAD

**Issue by wtgodbe** [dotnet/arcade#2119]
See https://github.com/dotnet/corefx/commit/adf29843831d7c731f5fc72435bc4cbf979cdb55#diff-9b0d0fe2c10c3dbfd8e27a659830aad0R12, https://github.com/dotnet/corefx/pull/35572

APICompat may be picking the wrong Core Assembly in some cases, we should investigate/if why this is the case. One hint path may be to look at why ApiCompat gives different results on CoreFx UAPAOT for `BuildAllConfigurations` builds vs. `uapaot` builds

CC @ericstj

**Comment by ericstj** [comment]
Some notes on why this is happening.

The default implementation in CCI tries to compute the core assembly by looking at assemblyies loaded into the environment that can claim they know what the core assembly is.
https://github.com/microsoft/cci/blob/399c407883746cd207386dc440606d83e8deb818/CoreObjectModel/MetadataHelper/Core.cs#L181

Each assembly computes what it thinks is the core assembly
https://github.com/microsoft/cci/blob/399c407883746cd207386dc440606d83e8deb818/PEReaderAndWriter/PEReader/PEFileToObjectModel.cs#L272-L342
1. examining typerefs for key types (like Object) and taking the assembly ref that has the most of these key types
2. otherwise checks if the assembly itself defines System.Object
3. otherwise checks if the assembly references System.Runtime and returns that
4. otherwise checks if the assembly references mscorlib and returns that

The problem with this implementation lies [here](https://github.com/microsoft/cci/blob/399c407883746cd207386dc440606d83e8deb818/CoreObjectModel/MetadataHelper/Core.cs#L173-L184):
```c#
foreach (IUnit unit in this.unitCache.Values) {
    Contract.Assume(unit != null);
    AssemblyIdentity coreId = unit.CoreAssemblySymbolicIdentity;
    if (coreId.Name.Value.Length == 0) continue;
    this.coreIdentities.Add(coreId);
    if (result == null || result.Version == dummyVersion ||
        (result.Version < coreId.Version && coreId.Version != dummyVersion) ||
        result.Version == coreId.Version && unit.UnitIdentity.Equals(coreId)) {
        result = coreId;
        referringUnit = unit;
    }
}
```
To unpack that condition it behaves as follows, when considering a new candidate core assembly it will choose it if
1. No core assembly is known.
2. A core assembly is known but we don't know its version
3. A core assembly is known, but its version is less than the current candidate (note that name of the assembly is ignored, so this is an illegitimate comparison).
4. A core assembly is known, its version is the same as the current candidate, and the current candidate is from an assembly that claims itself is the core assembly. (again an illegitimate check).

Now CCI.Extensions hit this bug and decided to re-implement GetCoreAssemblySymbolicIdentity:
https://github.com/dotnet/arcade/blob/04f4b34837651ad724f48362285f0a5d2ffa4a90/src/Microsoft.Cci.Extensions/HostEnvironment.cs#L221-L236

The code here that is honoring the assembly which believes to be itself the core assembly is good, that'll catch the cases where we've loaded an actual core assembly to the environment, but we haven't always loaded it!  In the case of APICompat, we only load the matching contracts pre-emptively which in the case of a .NETStandard comparison will not load the actual core assembly, but only netstandard (which thinks its core assembly is System.Runtime).  So this fix fails and it falls back to CCI's implementation.  That enumerates through the loaded units, sees one assembly which thinks System.Runtime is the core assembly and chooses it (version 4.2.n.0).  Even if I try to workaround it by forcing other assemblies to be loaded (by including them in the APICompat pass) it will fail since once it has selected a System.Runtime it will never prefer System.Private.CoreLib since its version is lower.  Since we never proactively load System.Private.CoreLib as we are not running APICompat against this as a contract, we'll never satisfy the CCI.Extensions workaround case and are always hit the CCI bug.

I'll improve CCI's workaround to push down the stack of CoreAssemblies, for a given unit try to proactively load its claimed core assembly, before we then do the `assembly.AssemblyIdentity.Equals(assembly.CoreAssemblySymbolicIdentity)` check.
