### ISSUE TITLE
Finding a build error from PR validation is a harrowing experience

### ISSUE THREAD

**Issue by rynowak** [dotnet/arcade#2142]
I don't have specific ideas about what we could do about this - hopefully some others do. I don't think the experience we currently have for PR validation with AZDO is very good and it seems like it should be possible to make it better.

In particular you have to dig all the way into the build log and scroll to the bottom to see what's wrong. The UX for this whole end to end just seems like it's not optimized for what we need it to do, which is to present all of the error information clearly.

At any point this experience would be made much better by presenting an actual error message instead of "build failed because build.cmd exit code ...". 

## Example

1. Let's start here: https://github.com/aspnet/AspNetCore-Tooling/pull/278 This PR has failing validation (right now).

![image](https://user-images.githubusercontent.com/1430011/53596008-98990400-3b53-11e9-9f62-c6e35ff6a78f.png)

2. So I click on ["details"](https://github.com/aspnet/AspNetCore-Tooling/pull/278/checks?check_run_id=70617922) for one of the failing builds

![image](https://user-images.githubusercontent.com/1430011/53596044-b2d2e200-3b53-11e9-824e-128bac423347.png)

3. So I click on ["7 errors / 6 warnings"](https://dev.azure.com/dnceng/public/_build/results?buildId=110205)

![image](https://user-images.githubusercontent.com/1430011/53596092-d5fd9180-3b53-11e9-8293-8cc5a4b09c95.png)

4. It has auto-selected the top build job which passed. So I click on one of the failed ones

![image](https://user-images.githubusercontent.com/1430011/53596168-00e7e580-3b54-11e9-8eb0-32bafb7f9c2f.png)

5. Now I have to click on "Build" to see the failing step

![image](https://user-images.githubusercontent.com/1430011/53596242-22e16800-3b54-11e9-8ad7-07bc39eb78c4.png)

6. Now I have to scroll all the way to the bottom, and I have to be careful to interact with the leftmost of the 2 scrollbars in the log window.

![image](https://user-images.githubusercontent.com/1430011/53596281-40163680-3b54-11e9-9549-8d145aa3ba4f.png)

Now I can see the error messages, well about 20 characters of them. 

7. Now I can carefully scroll from left to right to try and parse the error messages

## Bonus

The summary window is equally unhelpful

![image](https://user-images.githubusercontent.com/1430011/53596545-d3e80280-3b54-11e9-92ff-a8d8757e09f9.png)

**Comment by tmat** [comment]
Agreed. @rainersigwald has been looking into some improvements:
https://github.com/dotnet/arcade/issues/2038
https://github.com/dotnet/arcade/issues/2036

**Comment by markwilkie** [comment]
@rynowak - would the linked issues Tomas referenced make things "ok" for you?  Trying to reason about the right disposition for this issue and am searching for the right actionable path forward.

**Comment by rynowak** [comment]
It's not incredibly from the linked issues what user experience is being proposed. Ideally I'd like this page to show a clear error message instead of `bash exited with code '1'`:

- Compiler error message
- Test failure output

Something that indicates the actual cause the build failure

![image](https://user-images.githubusercontent.com/1430011/54846312-c4ae2d80-4c98-11e9-9842-7037f874003c.png)

**Comment by rainersigwald** [comment]
That's the goal of those other bugs--to get Arcade back to parity with the vanilla Pipelines experience for build errors (#2036) and to improve the Arcade-specific script errors to play nicely (#2038).

For example, I just hooked up some tests here: https://github.com/Microsoft/MSBuildSdks/pull/75/checks?check_run_id=83161918

and it has pretty readable indications around the test failures:

![image](https://user-images.githubusercontent.com/3347530/54846739-8c174f80-4caa-11e9-9650-cd9be7f429cf.png)

The only separate work item I can think of is tests, too; I'm not sure why they don't already have a nice experience since the Pipelines test tab works already.

**Comment by markwilkie** [comment]
> The only separate work item I can think of is tests, too; I'm not sure why they don't already have a nice experience since the Pipelines test tab works already.

Thanks @rainersigwald.  Do you have any specifics regarding your quote?  (also adding @alexperovich who I seem to recall did some plumbing work to get Helix reporting better if that's what you're referring to)

**Comment by alexperovich** [comment]
Yea, Helix tests all report on the Test Tab in the build. If those failures aren't surfaced to the PR in a nice way we should work with AzDev to fix that.

**Comment by rainersigwald** [comment]
Looks like this was fixed at some point. https://github.com/Microsoft/msbuild/pull/4162/checks?check_run_id=62585039, for example, lists test failures semi-nicely:

![image](https://user-images.githubusercontent.com/3347530/54850930-7576f580-4cb6-11e9-8ce4-5659376c9175.png)

These aren't Helix tests, just unit tests run in the Arcade-driven build.

One wrinkle: the test failures are only available in the overall job; each individual job will be marked as failed due to `Process completed with exit code 1.`. That should be slightly better with #2036, but will still be a bit wonky.

**Comment by markwilkie** [comment]
@mjanecke is working on https://github.com/dotnet/arcade/pull/2374 which should also help.  @rainersigwald - do you think that between #2036 and https://github.com/dotnet/arcade/pull/2374 we're at a better place?

**Comment by rainersigwald** [comment]
I think #2038 is needed too, for things outside the MSBuild invocation.

**Comment by markwilkie** [comment]
ACK

**Comment by missymessa** [comment]
I feel like Build Analysis solves this problem? Please re-open if more work is needed in this area.
