### ISSUE TITLE
Make Source-build build status report in MC as a peer to prodcon builds

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#236]
@dleeapho commented on [Thu Mar 08 2018](https://github.com/dotnet/core-eng/issues/2863)

Part of https://github.com/dotnet/source-build/issues/145
As part of this we need to:
- standup a VSTS mirror (security best practice)
- implement a pipebuild rolling for source-build builds

---

@Chrisboh commented on [Thu May 31 2018](https://github.com/dotnet/core-eng/issues/2863#issuecomment-393663798)

Need more information on how we should triage this.  Waiting until next triage meeting to get input from Dan.

---

@dleeapho commented on [Thu Jun 07 2018](https://github.com/dotnet/core-eng/issues/2863#issuecomment-395553091)

Per triage discussion, the prereq to this is to make source-build builds report telemetry for MC https://github.com/dotnet/source-build/issues/595

**Comment by JohnTortugo** [comment]
Would it be interesting to have this in Maestro++ instead?

/cc @mmitche

**Comment by Chrisboh** [comment]
We have evolved a long ways since the initial writing of this issue.  In today's world source build should be no different then the rest of our repos and leverage AzDo for both build and test reporting.  I think that is the case today and we should be able to close this issue.  @JohnTortugo I think you are poking on the dependency flow for scoure build.  For that I am less sure and we should follow up with @dleeapho to see what gaps are there we should help with.

**Comment by JohnTortugo** [comment]
@Chrisboh - Yeah, you're right. I misunderstood this issue as if it were asking for dependency flow status.

@dleeapho @dseefeld @dagood - are you ok to closing this issue?

**Comment by dagood** [comment]
> In today's world source build should be no different then the rest of our repos and leverage AzDo for both build and test reporting. I think that is the case today and we should be able to close this issue.

I think this misses the main point of the issue--it's about elevating the visibility of source-build so that people care when it isn't working. It seems from my perspective that nowadays, visibility is simply "do we have a Core-SDK build right now?" We need to improve this, but I don't know if it can be summed up in a public Arcade issue. (@dleeapho correct me if I'm wrong.)

I think you're thinking along the right lines, @JohnTortugo. If people pay attention to Maestro++, then that would be a good place to make sure it's visible. (I don't see it currently, and even so, I imagine Core-SDK is what people look at on that site.)

**Comment by mmitche** [comment]
@dagood If we integrate source build into our official builds (something that builds in PR, and in parallel with our official builds, like a job that runs in parallel), then won't we implicitly be raising the visibility of source-build? If your build fails source build, your build fails. That would also implicitly show up on Maestro

**Comment by dagood** [comment]
@mmitche Yes, but AFAIK we don't plan on that for our 3.1 builds, which probably need to be more visible.
