### ISSUE TITLE
Target InitializeStandardNuspecProperties failing due to missing 'RepositoryCommit' property build failures in 'official/dotnet/core-sdk/refs/heads/master' - '20190327.2'

### ISSUE THREAD

**Issue by robertborr** [dotnet/arcade#2368]
@dotnet-mc-bot commented on [Wed Mar 27 2019](https://github.com/dotnet/core-eng/issues/5714)

There were a set of failures during this build. Here is a summary of these:
* https://dnceng.visualstudio.com/internal/_build/results?buildId=135987
  - **Agent:** a0000T6
  - **Error log:** F:\vsagent\100\s\.packages\microsoft.dotnet.arcade.sdk\1.0.0-beta.19171.6\tools\Workarounds.targets(0,0): error : RepositoryCommit must be specified [F:\vsagent\100\s\src\Microsoft.Dotnet.Sdk.Internal\Microsoft.Dotnet.Sdk.Internal...

@robertborr

**Comment by robertborr** [comment]
ref: https://github.com/dotnet/core-sdk/pull/1134  - same issue happened in that PR

**Comment by MattGal** [comment]
The error seems to be a legitimate one that they've worked past (appear to no longer be using the workaround task at all).  Regardless, Core-SDK's master and PR builds are green now, the error was a legitimate "noone provided this property" error, so I'd recommend closing. 

@robertborr please attempt to make titles of new issues created on your behalf describe the problem.  For instance "Target InitializeStandardNuspecProperties failing due to missing 'RepositoryCommit' property" would make this issue far more searchable and understandable.
