### ISSUE TITLE
Build fails due to missing RoslynTools.MSBuild 16.0.0-alpha

### ISSUE THREAD

**Issue by merriemcgaw** [dotnet/arcade#2384]
@ArrowCase commented on [Sun Mar 24 2019](https://github.com/dotnet/winforms/issues/628)

I wasn't sure whether this issue belongs here or in [dotnet/arcade](https://github.com/dotnet/arcade). Please feel free to move it.

Steps to reproduce: Clone repository, run build.cmd.

Results:

```
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview3-010436/dotnet-sdk-3.0.100-preview3-010436-win-x64.zip
dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-preview3-010436/dotnet-sdk-3.0.100-preview3-010436-win-x64.zip
dotnet-install: Adding to current process PATH: "C:\Users\user\source\repos\winforms\.dotnet\". Note: This change will not be visible if PowerShell was run as a child process.
dotnet-install: Installation finished
Downloading vswhere
Downloading RoslynTools.MSBuild 16.0.0-alpha
No package matching package identifier RoslynTools.MSBuild and version 16.0.0-alpha was found in the given feed.
```

Version 16.0.0-alpha of the package indeed [does not appear to exist](https://dotnet.myget.org/F/roslyn-tools/api/v2/package/RoslynTools.MSBuild/16.0.0-alpha), but [16.0.0-rc1-alpha does](https://dotnet.myget.org/feed/roslyn-tools/package/nuget/RoslynTools.MSBuild).

Additionally, running `build` a second time results in a different error:

```
Exception calling "Start" with "0" argument(s): "The system cannot find the file specified"
System.Management.Automation.MethodInvocationException: Exception calling "Start" with "0" argument(s): "The system cannot find the file specified" ---> System.ComponentModel.Win32Exception: The system cannot find the file specified
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at CallSite.Target(Closure , CallSite , Object )
   --- End of inner exception stack trace ---
   at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
at Exec-Process, C:\Users\user\source\repos\winforms\eng\common\tools.ps1: line 69
at MSBuild, C:\Users\user\source\repos\winforms\eng\common\tools.ps1: line 476
at InitializeToolset, C:\Users\user\source\repos\winforms\eng\common\tools.ps1: line 422
at Build, C:\Users\user\source\repos\winforms\eng\common\Build.ps1: line 76
at <ScriptBlock>, C:\Users\user\source\repos\winforms\eng\common\Build.ps1: line 125
at <ScriptBlock>, <No file>: line 1
```

---

@zsd4yr commented on [Wed Mar 27 2019](https://github.com/dotnet/winforms/issues/628#issuecomment-477355735)

@OliaG @merriemcgaw would one of you kindly move this to dotnet/arcade ?

**Comment by zsd4yr** [comment]
@MattGal this is what we discovered related to Roslyn.MSBuild changing their URLs and that it was hardcoded in tools.ps1

**Comment by zsd4yr** [comment]
I am going to work around by including `xcopy-msbuild` in my global json but for anyone else using Arcade with vs.version = 16.0, this will fail
```json
  "tools": {
    "dotnet": "3.0.100-preview4-010924",
    "vs": {
      "version": "16.0"
    },
    "xcopy-msbuild": "16.0.0-rc1-alpha"
}
```

**Comment by MattGal** [comment]
Yup.  Seems like explicitly specifying values is the way to go anyways, but perhaps the workaround for users not specifying would be to just append * instead of the other stuff.

**Comment by tmat** [comment]
We can't just append `*` - that would make the build non-deterministic. 

The reason why the build is failing is that you are building on a machine that does not have VS2019 yet you require VS2019 to be present. The build falls back to a default version of `xcopy-msbuild` package because none was specified explicitly. This is by design. It would indeed be better if the package was named `16.0.0-alpha`, so that the default fallback just works.

/cc @jaredpar

**Comment by MattGal** [comment]
@jaredpar when helping @zsd4yr , I noticed that if the package version wasn't specified, there are powershell scripts that just determine the VS version, and concatenate this with ".0-alpha"  for the version of this package.  Somewhere between when that script was written and now, he packages started being versioned in such a way that this assumption would need to be changed to add ".0-rc1-alpha" to be true.    Since the non-numeric part of the version changed, these scripts can no longer make an educated guess about the best package to pick.

IMO, educating folks who use this package to specify the property (which Zach did) makes the most sense.

**Comment by tmat** [comment]
> Since the non-numeric part of the version changed, these scripts can no longer make an educated guess about the best package to pick.

Exactly, because the script doesn't know to append "rc1". It only knows what VS version the repo needs (e.g. "15.9", "16.0"). 

I don't think we need to change anything. The default will work once we create "16.0.0-alpha" package and if anyone needs anything else they can specify it explicitly. I'll update [doc](https://github.com/dotnet/arcade/blob/master/Documentation/ArcadeSdk.md#globaljson-nugetconfig) - it doesn't mention xcopy msbuild.

**Comment by jaredpar** [comment]
Note: I just uploaded the 16.0 RTM package with name 16.0.0-alpha. Here is the PR in Roslyn where I'm verifying it: https://github.com/dotnet/roslyn/pull/34676

**Comment by tmat** [comment]
Added a doc: https://github.com/dotnet/arcade/pull/2401

**Comment by kelsosharp** [comment]
> The reason why the build is failing is that you are building on a machine that does not have VS2019 yet you require VS2019 to be present. 
> 
> /cc @jaredpar

This is incorrect, I am running Visual Studio 2019 and I also have this issue

**Comment by kelsosharp** [comment]
Did this get regressed? I just downloaded the aspnetcore and now I have the same issue, running VS 
2019
