### ISSUE TITLE
[darc/maestro++] Some coherent updates listed multiple times

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2462]
When coherent parent is used in a chain, some updates are listed multiple times in the PR description:

https://github.com/aspnet/EntityFrameworkCore/pull/15272

Should list each dependency only once. This symptom means that the returned dependency updates from GetRequiredCoherencyUpdates contains multiple of the same dependency. This is what should be fixed.

**Comment by dougbu** [comment]
This issue also adds noise when using `darc update-dependencies` on the command line

**Comment by dougbu** [comment]
On a related note, the final commit message can get extraordinarily long when dependency commits pile up. See for example https://github.com/aspnet/AspNetCore/commit/17b6baa0bd87e507ecad1323074782048de176a2

It would be wonderful if the bot edited the squash commit's message to mention only the last update from a repo. While the above looks worse because updates from two repos are batched together, redundant and long commit messages can happen anywhere.
