### ISSUE TITLE
Powershell Core

### ISSUE THREAD

**Issue by jaredpar** [dotnet/arcade#2483]
Today in arcade we have quite a bit of infrastructure contained in our scripting layer. Every line of code in that layer we pay double for because we have to write it in Powershell and Bash. 

As I'm updating the bash side for the Azure logging change it makes me wonder: why not Powershell Core? It seems to have a number of advantages for us: 

1. Cross platform.
1. .NET Core based so it's not a new large dependency, just a layer on top.
1. Low migration cost: most of our existing PS1 scripts should just work. 

I have as much of a tortured history with Powershell as anyone. But I think it makes sense to consider here.

**Comment by tmat** [comment]
I don't think we can use PowerShell Core since that requires .NET Core, whose acquisition is the only thing that the bash scripts (tools.sh, build.sh) are needed for in the first place. We should have more bash scripts beyond what's necessary to locate/install dotnet. Everything else should be done in msbuild.

The only bash scripts I can think of that could be converted to PowerShell Core/msbuild are those that initialize native tools https://github.com/dotnet/arcade/tree/master/eng/common/native

**Comment by ViktorHofer** [comment]
Additionally, the test scripts that run on helix machines shouldn't use powershell scripts either. We want to support flavors that don't have a powershell variant yet.

**Comment by markwilkie** [comment]
@jaredpar - closing as every time this comes up, it always sounds nice, but doesn't ever seem feasible in the end.  However, if you see a clear path forward, feel free to reopen of course.
