### ISSUE TITLE
Define PKPIs (Product KPIs)

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#2629]
Define a set of product KPIs that can be used to determine the health of the product. Should (mostly) be applicable on each individual repo.  Examples include:
- [ ] Time to coherency at a node given current dependency state
- [ ] Number of builds/day 
- [ ] PR build time
- [ ] Official build time
- [ ] PR/Official pass rates
- [ ] PR Retry rates 
- [ ] Existence/non-existence of dependency flow cycles
- [ ] Staleness of dependencies vs latest in channel based on expected flow 
- [ ] Number of "stuck" PRs in a subtree.

**Comment by markwilkie** [comment]
One of the questions I keep hearing asked is "is the product worth testing now"?

To help, I'm wondering if it makes sense to have sort of metric (letter grade??) which reflects the state of coherency.

Factors might be:
- How far down graph the incoherency goes.  For example, coreclr would have a lot for "weight" than core-setup
- "bit staleness", again heavily weighted by which repo we're talking about.
- How long it will take to attain coherency (you've already identified this).  The idea here is that the longer it take to achieve coherency, in theory the less "valid" the product is.
- Stuck flow/dependency PRs.  This is related to bit staleness, but in my mind of a flow PR can't be merged, the "health" of the product should be much lower because that likely points to something else that's wrong.
- An important SHA not all the way through.  This requires knowing (of course) which SHA's are important.  But in the end-game, it seems conceivable that tactics/shiproom could mark SHAs as important, and that would directly affect the health of the product.
- Which channel.  The dev channel would have a much higher tolerance - and thus a better "grade" given the state of these factors than the shipping channel for example. 

I get the fact that this would not be bullet proof in any way.  But perhaps there's a way to at least get a quick "sense" of the state?  I could image that ML could be useful here as well so the "grade" gets better and better over time as it learns.

**Comment by mmitche** [comment]
@ericstj, @zsd4yr @nguerrera and I had thoughts on the coherency bit.  I do not think you can apply any sort of generic graph level coherency check and get useful results because knowledge of what constitutes meaningful coherency requires knowledge of how the product is constructed.  To me there are two metrics for this that are interesting:
- Staleness (can be stale and coherent)
- Binary level compatibility

The binary level compatibility check should be done on the SDK level.  The SDK knows which specific runtimes are going to be packed up and all the ancillary input binaries (e.g. roslyn, msbuild, windowsdesktop, etc.) will run on those runtimes. What it needs to do is an API level compatibility check of the runtimes that will actually be used against the runtimes that the inputs were built/tested against.

To me, the staleness check is perhaps more interesting than the coherency check. Validation happens often against master on wildly incoherent builds, and I've heard of few (if any) problems resulting from that. Even then, the staleness check is tough, as what is "important" changes over time.

Stuck/flow

**Comment by zsd4yr** [comment]
For staleness, the commit hash in a repo gets burned into any package produced via arcade (transport or final); and this could be tracked through the flow to see how far _behind_ the bits in the SDK are from master in the source repos at any given time

**Comment by shawnro** [comment]
@mmitche I want to clarify your statement "I've heard of few (if any) problems resulting from that"

You're saying that doing validation on wildly incoherent builds is fine?  Are teams finding real issues with these builds?  Do we know ratio of issues caught in this state vs not caught until we get to full coherency?

**Comment by mmitche** [comment]
@shawnro Yeah. Richa's teams test these all the time. Either the issues aren't getting surfaced up to me, or they simply aren't that prevalent.  I'll follow up with Richa but my thinking is that it's the latter case.
