### ISSUE TITLE
Does helix determine a successful test run by inspecting the ErrorCode if EnableXUnitReporter is set to false?

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#2656]
See title. In our AllConfigurations leg in corefx we don't produce a test results file. We would like to not use MC for it anymore and switch everything over to AzDO.

1) Does Helix fail a test run if the ErrorCode is non-zero?
2) How do we get to the infra logs if such a test run fails? Do we still need to click the link and use MC for it or are those logs accessible from AzDO?

@alexperovich @MattGal @safern

**Comment by MattGal** [comment]
> Does Helix fail a test run if the ErrorCode is non-zero?

Work items that return a non-zero exit code are considered to be failing, though if you have some special reason for this you can simply either wrap your calls which return other values in a script which makes the final decision for the user (i.e. "if it's X, Y, or Z, we call it pass and return 0, otherwise we return the value it is...).  The Arcade waiter code will follow this expectation.

> How do we get to the infra logs if such a test run fails? Do we still need to click the link and use MC for it or are those logs accessible from AzDO?

Logs are only currently available from the Helix API, though I believe anything logged in the appropriate TRX / XUnit manner (i.e. as interleaved CDATA) _might_ get rendered on VSTS.

**Comment by ViktorHofer** [comment]
Cools thanks for letting me know. Just wanted to make sure that a non-zero error code implies a failure in the test run and is not simply swallowed.

> Logs are only currently available from the Helix API, though I believe anything logged in the appropriate TRX / XUnit manner (i.e. as interleaved CDATA) might get rendered on VSTS.

And just console outputs that we would like to see in AzDO to investigate failures? Is there a way to transport that over?

**Comment by MattGal** [comment]
I don't think so currently; @alexperovich can give a more definitive answer as he implemented this part.

**Comment by alexperovich** [comment]
There is currently a bug with getting logs in azdev for failed work items that don't have test results. For a failing test there will be a link to the logs in the attachments tab of the test.


-------- Original message --------

**Comment by ViktorHofer** [comment]
Great. Can you please post the link to the bug? Is there an ETA when this will be available?

**Comment by alexperovich** [comment]
Bug is here https://github.com/dotnet/core-eng/issues/6162

**Comment by ViktorHofer** [comment]
Thanks, closing as the questions are answered.
