### ISSUE TITLE
Import Roslyn-tools SignTool into Arcade

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#266]

**Comment by weshaggard** [comment]
While porting over the signing stuff we will need to incorporate the aggregate of the strong names defined in:
https://github.com/dotnet/roslyn-tools/blob/0bce8ad78a0afe6d03e6ba95c3a9e9729cbc00c9/src/RepoToolset/tools/StrongName.targets
https://github.com/dotnet/buildtools/blob/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/sign.targets

We should also figure out how to reconcile the need for the checked in signtooldata file, see https://github.com/dotnet/arcade/issues/58. 

We should also highly consider converting the signtool to an msbuild task instead of a separate exe like it is today. It already has to depend on msbuild see (https://github.com/dotnet/roslyn-tools/blob/0bce8ad78a0afe6d03e6ba95c3a9e9729cbc00c9/src/RepoToolset/tools/Sign.proj#L36) so why not just use the msbuild we are using everywhere else. At a min we ensure we don't require VS and the version of msbuild that comes with it like is currently happening. https://github.com/dotnet/roslyn-tools/blob/0bce8ad78a0afe6d03e6ba95c3a9e9729cbc00c9/src/RepoToolset/tools/Sign.proj#L23

@tmat any reason the signtool isn't an msbuild task?

**Comment by JohnTortugo** [comment]
Just an update: as per talk with @maririos she told me that the SignTool conversion to MSBuild Task was discussed with @tmat and he agreed to it.

**Comment by jaredpar** [comment]
@weshaggard 

> any reason the signtool isn't an msbuild task?

No particular reason. When I wrote SignTool originally it just fit better as an EXE into our build than a build task.

> We should also highly consider converting the signtool to an msbuild task instead of a separate exe like it is today. 

Don't have any objections to adding an MSBuild task but would prefer to keep the EXE. It's handy in a number of cases. 

> We should also figure out how to reconcile the need for the checked in signtooldata file, see #58.

Still not sure what we should reconcile here. The only people objecting to a checked in file are those who haven't used the tool. There are no complaints from those who are using it (and there are plenty of users now).

**Comment by weshaggard** [comment]
>Still not sure what we should reconcile here. The only people objecting to a checked in file are those who haven't used the tool. There are no complaints from those who are using it (and there are plenty of users now).

Lets continue this discussion in #58.

**Comment by rainersigwald** [comment]
Note that you can load a task from any managed assembly, even a `.exe`, so one could conceivably just add a class to the existing executable and load it from there to keep both.

**Comment by JohnTortugo** [comment]
@weshaggard & @jaredpar after @rainersigwald comment, do you agree to keep the .exe and create a MSBuild target to wrap it? If so, I could start moving this into Arcade.

**Comment by weshaggard** [comment]
I don't know enough about how it is currently implemented to say if that is the best option or not. I do agree that as much of the logic as possible should be shared. One challenge you will likely have keeping it only as an exe is that we will need a task library that can be loaded into .NET Core msbuild and exe's are generally .NET Framework and cannot be loaded in .NET Core because of their dependencies.

**Comment by maririos** [comment]
I created issue https://github.com/dotnet/arcade/issues/273 to use it for the discussion about convert or not convert the signtool to an msbuild task. Once that is clear, we can proceed on the implementation.

**Comment by maririos** [comment]
Also, created issue https://github.com/dotnet/arcade/issues/272 for the strong names work. 

Note that all of the issues are now in the Signing Package Ready for Consumption epic
