### ISSUE TITLE
dotnet-arcade-validation-official build is not always triggering

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#2691]
https://dnceng.visualstudio.com/internal/_build?definitionId=282 is not triggering for every build. Are rolling build triggers not enabled or is there another mirror between?

A change that built successfully in arcade-official-ci (https://dnceng.visualstudio.com/internal/_build?definitionId=6) at 2019-05 4·05am is still not published to BAR ".NET Tools - Latest" as no build is triggered in the validation build definition. Now: 2019-05-04 1:43pm

**Comment by markwilkie** [comment]
@JohnTortugo - can you ptal?

cc/ @jcagme @mmitche

**Comment by riarenas** [comment]
Do you have an example of a build that didn't get through?

The full process is:
1. PR gets merged and mirrored
2. Internal build runs from the mirror
3. https://dnceng.visualstudio.com/internal/_release?definitionId=39 runs for the build
4. Once steps 1-3 happen, a Dependency update PR is opened against https://github.com/dotnet/arcade-validation
5. Once the PR is merged, that is when the internal arcade-validation build runs and moves the arcade build to the new channel.

Having a build number for where you saw this not happening would help a lot to determine where an what went wrong

**Comment by ViktorHofer** [comment]
I did include logs. Aren't they useful enough?

**Comment by riarenas** [comment]
I apologize, I think I simply misinterpreted this comment
> A change that built successfully in arcade-official-ci (https://dnceng.visualstudio.com/internal/_build?definitionId=6) at **2019-05 4·05am** is still not published to BAR ".NET Tools - Latest" as no build is triggered in the validation build definition. Now: 2019-05-04 1:43pm

At first I thought you meant a build that finished 4:05am, so that confused me a little since I couldn't find any builds within that time frame, but I think I just misread, and I'm guessing that the build in question is: https://dev.azure.com/dnceng/internal/_build/results?buildId=179420 since it fits the time frame of 5 am on 2019-05-04

1. The linked build produced build 20190504.1, which triggered the release here: https://dnceng.visualstudio.com/internal/_releaseProgress?_a=release-pipeline-progress&releaseId=7058

2. Once that release finished, this PR was opened : https://github.com/dotnet/arcade-validation/pull/367

3. The PR failed to build with what appeared to be a transient failure: https://dev.azure.com/dnceng/public/_build/results?buildId=179281

4. There were no more arcade builds during 5/4, so the PR sat there in a failed state until the next arcade build happened on 5/5, the PR was updated, the gates ran again, and succeeded, and that's when the PR was merged, and triggered this build: https://dev.azure.com/dnceng/internal/_build/results?buildId=179537

I think in general we need to be more resilient to transient failures, not just in arcade-validation but across the board, and make it obvious to see when updates are getting applied.
The arcade-validation gates did the right thing in this case as the PR build failed, and we don't automatically know how to differentiate between a transient failure, or a real break introduced by the new Arcade version.

I'm going to take a look at the validation process docs to see if it makes sense to add all the steps that I checked to determine what happened.
