### ISSUE TITLE
Convert or not convert the signtool to a msbuild task

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#273]
Goal:  Logic as possible should be shared

Possibilities:
1. **Convert the signtool to an msbuild task instead of a separate exe**
It already has to depend on msbuild see (https://github.com/dotnet/roslyn-tools/blob/0bce8ad78a0afe6d03e6ba95c3a9e9729cbc00c9/src/RepoToolset/tools/Sign.proj#L36) 
At a min we ensure we don't require VS and the version of msbuild that comes with it like is currently happening. https://github.com/dotnet/roslyn-tools/blob/0bce8ad78a0afe6d03e6ba95c3a9e9729cbc00c9/src/RepoToolset/tools/Sign.proj#L23

2. **Load MSBuild task from the executable**
One challenge you will likely have keeping it only as an exe is that we will need a task library that can be loaded into .NET Core msbuild and exe's are generally .NET Framework and cannot be loaded in .NET Core because of their dependencies

3. **Convert but leave the EXE**

Cc: @weshaggard @jaredpar @rainersigwald

**Comment by JohnTortugo** [comment]
I was able to build the SignTool targeting net461 and netcoreapp2.0. I'll try to add a MSBuild task to the package and test it. With that we would be able to keep the .exe and the .net core DLL. 

What do you guys think?

**Comment by tmat** [comment]
Although it might be nice to have a build task that implements signing this instead of an .exe, I think we more important things to spend time on than converting .exe to a build task. The current sign tool implementation works fine in more than 20 repos. I don't see a point in changing it at this point. In future, we can certainly improve on it.

**Comment by weshaggard** [comment]
One of our goals is to eliminate our need for depending on VS during our builds and as such we need a tool that can run against the dotnet cli msbuild which today the signtool exe cannot do because it requires the msbuild installed with VS. So unless I'm missing something that will block that goal so I tend to disagree about the priority of moving this to a build task that can be consumed like everything else in arcade.

**Comment by jaredpar** [comment]
> today the signtool exe cannot do because it requires the msbuild installed with VS. 

To be specific: it requires a desktop MSBuild installation. There is no VS requirement in signtool. 

This requirement though is pretty thin. At one point @tmat sent a PR to make it work with `CLI` and we just didn't really have a use case for it at the time. Making that work though is a pretty trivial effort. 

That being said I don't really care if it's an MSBuild Task + EXE. That's also a small amount of work. Probably as much as the time we've spent debating it. 😄

**Comment by markwilkie** [comment]
> Probably as much as the time we've spent debating it.

lol

**Comment by maririos** [comment]
Looks like option 3 it is => Convert but leave the EXE.
We'll try this approach and report if there are concerns/problems during the process that might affect the decision

**Comment by tmat** [comment]
Sounds good.

**Comment by tmat** [comment]
Actually, I take it back. I think there is some confusion about this tool that needs to be clarified:

The tool is used by RepoToolset in repos that do not have desktop msbuild dependency (or VS dependency), such as SymReader. The entire SymReader build runs fine on a clean machine. 

How does signing work in that case? The signing tool has 2 modes - validation-only mode and real signing mode. The former does not depend on desktop msbuild. It can be run on any Windows machine. It validates that the information in .json file matches the binaries and packages produced by the build.
 
The real-signing requires desktop msbuild. That's because the Microbuild signing plugin is desktop only. 

We can make the sign tool run in validation mode on non-Windows machine by porting the tool to msbuild task that targets `netcoreapp2.0` and `net461`. That would give developers who work in Mac/Linux the ability to validate signing on their local machine. It's nice to have, but at this point I don't think that's the most important feature to have.

**Comment by mmitche** [comment]
@tmat The Microbuild signing plugin will be getting Linux/Mac support, so I don't think any decisions should be made based on assuming there will be a desktop MSBuild installation.

**Comment by weshaggard** [comment]
@tmat do you know if there exists any tools to take our file list which is currently an msbuild item group and convert them to the signtooldata.json file that the signtool currently expects? 

If not I'd like to avoid writing that throw away code and instead just move it to taking the list as an item group from msbuild and get us closer to where we want to be.

**Comment by weshaggard** [comment]
Perhaps the full file list will not be needed but a list of containers (msi, nupkg, vsix) or a least a directory that has those needs to be passed in. If we have a way to pass that in that doesn't require us to generate the signdatatool.json then I can live with this not being an msbuild task right now.

**Comment by tmat** [comment]
Yup, having a parameter that takes a list of containers would be reasonable.
