### ISSUE TITLE
Unifying Microsoft.CodeAnalysis.CSharp across MsBuild, Corefx, Arcade and sourceBuild

### ISSUE THREAD

**Issue by Anipik** [dotnet/arcade#2748]
Msbuild Currently uses 2.1.0 version of Microsoft.CodeAnalysis.CSharp which restricts the use of any higher version of this assembly  by the projects that also defines msbuild tasks.
eg Microsoft.Dotnet.GenFacades

The newer versions of these package are required in order to access the new language features like ref structs.

Similar is the situation is with arcade and sourcebuild. Arcade is using 2.9.0 and SourceBuild is using 3.0 preview version

cc @chcosta @tmat @ericstj @danmosemsft 

Related Issue https://github.com/dotnet/arcade/issues/2669

**Comment by markwilkie** [comment]
@Anipik - could you expand a bit on what your ask might be?  My simplistic answer is - make sure the different pieces of the build stay reasonably up to date w/ msbuild.  thoughts?  For example, update genfacades in this case...

**Comment by ericstj** [comment]
@markwilkie our tasks are up to date.  The problem is that we cannot update the dependencies because MSBuild pins the versions to those in its deps file.  This prevents a task from depending on any newer version that is already referenced by MSBuild.  This is related to https://github.com/microsoft/msbuild/issues/1754. 

Here's the latest MSBuild.deps.json: https://gist.github.com/ericstj/43ec3eab56eff774febab0fb107bfbd7

Notice things like: `Microsoft.CodeAnalysis.CSharp/2.1.0`, `Newtonsoft.Json/10.0.3`, `NuGet.Frameworks/5.1.0-rtm.5921`

These are all dependencies that are used by tasks that build out of arcade and are non-source-built versions of the dependencies.  The tasks in arcade have to keep their dependencies equal to or less than these versions otherwise we'll have load failures in the non-source-built case, however these assemblies are all flagged as pre-builts by source build.

/cc @nguerrera @rainersigwald

**Comment by nguerrera** [comment]
msbuild.deps.json gets rewritten in CLI so some of the issues can be on the CLI repo here. For the older version of roslyn, i think at one point when roslyn moved to its own subdirectory for the build part, then something else in CLI pulled in a stable version. (The real roslyn runs out of proc.) Everything in CLI root dir is unified to same deps, which can cause msbuild.deps.json to include things that msbuild doesn't actually depend on itself. It is quite a mess. Fixing microsoft/msbuild#1754. would be a good start. Ultimately, loading everything into same ALC cannot work out no matter how much we clean up here because that prevents loading multiple versions SxS, which is the only thing that's going to scale for arbitrary build task plugins.

**Comment by nguerrera** [comment]
Tactically, we can probably fix it so that the root, deps copy of Microsoft.CodeAnalysis.CSharp is the same as the version of roslyn a given SDK uses for compilation. Would that be sufficient for the short term? If so, file an issue on dotnet/cli.

**Comment by ericstj** [comment]
At steady state that would help, however I think that technically we can be in a torn state where Arcade is consuming a newer version of roslyn than has been ingested into CLI due to the way that the dependencies flow.  Maybe we just live with that for now...  /cc @mmitche

**Comment by chcosta** [comment]
As discussed today, this can be unified after @nguerrera's change to move Roslyn out of proc flows to Arcade.  FYI @ericstj as a reminder.

**Comment by nguerrera** [comment]
My changes are in as of .NET Core SDK 3.0.100-preview7-012271 or greater

**Comment by markwilkie** [comment]
I'm interpreting the discussion here as this issue has been resolved.  However, please reopen if I'm confused.
