### ISSUE TITLE
Helix should be able to report multiple results for unreliable tests

### ISSUE THREAD

**Issue by llongley** [dotnet/arcade#2773]
We have some UI tests that very occasionally fail due to timing issues, and it would be really great if we were able to report unreliable tests when reporting test results from Helix, rather than only being able to report a binary pass/fail result.  There are two options, both of which would be acceptable for our needs, though the former of the two would be even better:

1. Being able to report how many times a test passed when we ran it multiple times (e.g., running it once, seeing that it fails, then running it ten times to see if it's a genuine failure or just an unreliable test - if we could report "7 of 11 runs passed", that'd be ideal); or
2. Being able to report "Passed on rerun" from Helix tests if we ran a test once, it failed, and then it passed at least once upon being re-run.

**Comment by markwilkie** [comment]
cc/ @mjanecke and @Chrisboh who probably have comments.

**Comment by Chrisboh** [comment]
So there are a few challenges with the 2 options that you recommended.  the first is we did add the feature to rerun tests multiple time within Helix but after using it for a while we found it was only hiding real issues within the product.  The other challenge we have is with the reporting of the test results to AzDo.  Due to the fact that reruns happen on different machines there was no sane way to report the results to AzDo correctly with the API's that exist today.  

Instead we are looking into ways we could address flaky tests.  The first is you can use the AzDo feature that is on for dnceng to mark a test as flaky.  Doing this will ensure that test case will not fail the build if it fails.  I am aware there are some challenges in this approach but would love to hear any feedback here you have around this as the AzDo team is working on this feature right now.  Another approach we are looking at is to see if we can do something at the XUnit level to run the test and take the current result and the previous X results to determine a pass / fail threshold.  This is still very early thinking and we haven't thought through all the details here but I hope it gives you a sense where our heads are at.

**Comment by markwilkie** [comment]
@llongley - given the work that @Chrisboh is shepherding through, is there anything actionable on this issue?

**Comment by kmahone** [comment]
We were able to work-around this issue by uploading a file containing the test re-run data and then using the Helix REST api to query for that file from the Pipeline machine. This lets us collect the required data about unreliable tests. 

So I think this issue can be Closed.

**Comment by ChadNedzlek** [comment]
Closing.
