### ISSUE TITLE
Arcade update is breaking dotnet/toolset

### ISSUE THREAD

**Issue by livarcocc** [dotnet/arcade#2864]
We are taking an arcade update here: https://github.com/dotnet/toolset/pull/1028/files

Build logs are here: https://dev.azure.com/dnceng/public/_build/results?buildId=198046

It is now failing out build saying it can't understand a --publish switch.

Did something happen in arcade do cause this breaking change? The PR has no other changes but arcade.

cc @markwilkie

**Comment by JohnTortugo** [comment]
@chcosta

**Comment by jcagme** [comment]
Might be caused by https://github.com/dotnet/arcade/pull/2766?

@livarcocc, are you guys using the SDK in a "special" way? Asking since other repos took the same change and their Linux legs succeeded, for example:

https://github.com/dotnet/arcade-validation/pull/431
https://github.com/dotnet/corefx/pull/37860
https://github.com/dotnet/core-setup/pull/6503

At the same time core-sdk presents the same issue: https://github.com/dotnet/core-sdk/pull/2005

@riarenas, arcade-validation took the change and everything passed, just maybe we should think about adding a scenario that mimics that in toolset/core-sdk?

**Comment by chcosta** [comment]
I'll take a look

**Comment by livarcocc** [comment]
We invoke the build step on our CI like this:

```
- script: ./build.sh
                  $(TestParameter)
                  --pack --publish --ci
                  --noprettyprint
                  --configuration $(_BuildConfig)
                  $(_DockerParameter)
                  --architecture $(_BuildArchitecture)
                  $(_LinuxPortable)
                  $(_RuntimeIdentifier)
                  $(_BuildArgs)
                  $(_AdditionalBuildParameters)
```

Does this qualify as "special way"?

**Comment by chcosta** [comment]
@livarcocc , no, the "special way" is the argument parsing which is happening in run-build.sh.

https://github.com/dotnet/toolset/blob/master/run-build.sh#L28-L62

But, this highlights that we can be more robust here and I've prepared a fix.
