### ISSUE TITLE
DARC updates create unreasonably long change descriptions

### ISSUE THREAD

**Issue by ericstj** [dotnet/arcade#2884]
Example: https://github.com/dotnet/core-setup/commit/0b66d1682d8cf9541c96c445a4eb5fd35222ca7d#diff-74e6a8b111ea7da1a7d0a596f4c35208

Change descriptions that duplicate the content of change itself are not helpful.

We're going to have a lot of these change descriptions in all of our repos.  Please keep them brief.

I'm ok with PR details that are larger.

I'm not sold on the usefulness of appending the details of multiple commits when merging.  Shouldn't DARC be squashing and force pushing when updating an unmerged branch?

/cc @mmitche @jcagme

**Comment by markwilkie** [comment]
@riarenas is working on fixing this and I'll let him update this w/ the tracking issue.

**Comment by riarenas** [comment]
I have added the change description considerations to #2219. It makes sense to tackle it along with making the PR description shorter as well.

It's definitely not useful to have such a long change description, especially since when the commit is merged, it's not interesting to see the intermediate versions that happened while the PR was open, since the merged branch never really saw that final version.
