### ISSUE TITLE
Get-only properties are emitted as readonly in CoreFx ref assemblies

### ISSUE THREAD

**Issue by WinCPP** [dotnet/arcade#3010]
Get-only properties are generated as readonly properties when auto-generating `ref` assemblies. The autogeneration steps are as mentioned in [updating-ref-source.md](https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/updating-ref-source.md). This causes multiple changes in the ref assembly code; not sure if it is legit and should be accepted.

E.g.
```
-        public bool AllowTrailingCommas { get { throw null; } set { } }
-        public System.Text.Json.JsonCommentHandling CommentHandling { get { throw null; } set { } }
+        public bool AllowTrailingCommas { readonly get { throw null; } set { } }
+        public System.Text.Json.JsonCommentHandling CommentHandling { readonly get { throw null; } set { } }
```
And another one with subtle difference
```
-        public System.Buffers.ReadOnlySequence<byte> ValueSequence { get { throw null; } }
-        public System.ReadOnlySpan<byte> ValueSpan { get { throw null; } }
+        public readonly System.Buffers.ReadOnlySequence<byte> ValueSequence { get { throw null; } }
+        public readonly System.ReadOnlySpan<byte> ValueSpan { get { throw null; } }
```
Entire diff can be found [here](https://gist.github.com/WinCPP/a1c194ee634bcbc2b91884c8b88edbfe).

Creating this issue based on discussion in dotnet/corefx/issues/36125 in following comments,
_@WinCPP in https://github.com/dotnet/corefx/issues/36125#issuecomment-500109703_
_@ahsonkhan in https://github.com/dotnet/corefx/issues/36125#issuecomment-500173705_

**Comment by tannergooding** [comment]
Auto properties on mutable structs have their getter marked readonly starting with C# 8. This is part of the 'readonly members' feature and avoids hidden copies when invoking these members on static readonly instances or on instances passed by `in`.

**Comment by tannergooding** [comment]
More details on this feature and its design can be found here: https://github.com/dotnet/csharplang/blob/master/proposals/readonly-instance-members.md

**Comment by tannergooding** [comment]
The `readonly` keyword should be kept as part of the reference assemblies in order to maintain the perf benefits provided by this new feature.

**Comment by tannergooding** [comment]
It's also worth noting that it was already deemed acceptable for a member to be perceived as readonly.

That is, you can still have a backing field be lazily initialized (such as via unsafe code) and the corresponding getter marked readonly. The requirement should just be that it is externally perceived as readonly and that the result returned is "deterministic" (i.e. it should, from the caller's perspective, be no different than had you initialized everything in the constructor immediately, rather than lazily).

**Comment by WinCPP** [comment]
@ahsonkhan Given above inputs by @tannergooding , I think I will retain the `readonly` keyword in the places where it is being generated. Appreciate your thoughts.

If ok, then we may want to close this issue.

**Comment by ahsonkhan** [comment]
I will have to spend some understanding this feature a bit better, particularly potential drawbacks (https://github.com/dotnet/csharplang/blob/master/proposals/readonly-instance-members.md#drawbacks), so let me get back to you.

In the meantime, however, **I am OK with retaining the readonly keyword** so that the auto-generated ref is cleaner. We can re-adjust in the future if necessary.

> If ok, then we may want to close this issue.

Sure, makes sense. Thanks @tannergooding for providing the relevant info.

**Comment by tannergooding** [comment]
> I will have to spend some understanding this feature a bit better, particularly potential drawbacks (https://github.com/dotnet/csharplang/blob/master/proposals/readonly-instance-members.md#drawbacks), so let me get back to you.

The drawbacks are just the same as not having the attribute, there are some cases which may still have hidden copies due to how the compiler handles things. This is more a concern about the implementation within a member marked `readonly` though, and in that you will get an compiler error if you try to invoke a non-readonly method (which just forces you to create an explicit copy).

Also, to summarize what @ahsonkhan asked me offline.
* The attribute can exist for downlevel as well. Compilers that don't understand the attribute will simply ignore it. So, something using C# 7.3 will consume the ref assembly that has the attribute and it will ignore it and potentially create hidden copies in applicable scenarios (the same as if the attribute didn't exist at all). C# 8.0 and higher will consume the ref assembly and recognize the attribute, eliding the hidden copies in applicable scenarios.

**Comment by WinCPP** [comment]
Thanks @tannergooding for the info. Closing this issue as discussed above.
