### ISSUE TITLE
Packages (by team) which should be shared to start

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#32]
**ASP**
- ~~DownloadFile~~
- ~~ZipArchive~~
- ~~UnzipArchive~~
- GenerateFileFromTemplate
- ~~ComputeChecksum~~
- Chmod

**Roslyn/CLI**
- Repack
- [x] Signtool

**CoreFx/CoreCLR**
- BlobFeed 
  -   VersionTools/Dependency update
  -   Repo Tools
  -   ILAsm
- ILLinker

**Comment by maririos** [comment]
@natemcmaster from the things that are under the ASP list, are those packages or scripts something we are going to move to Arcade because other repos will consume it?

@weshaggard I see that ILLinker is used in corefx, coreclr and source-build. Is the idea here to move the reference for the package to Arcade (probably SDK?) so that the repos that use it have the same version and configuration?

**Comment by natemcmaster** [comment]
Since opening this, the following aspnet tasks have become first-class MSBuild tasks:
* ZipArchive (named Zip in MSBuild)
* UnzipArchive (named Unzip)
* DownloadFile
* ComputeChecksum (named GetFileHash)

The only remaining task which may be useful to share is [GenerateFileFromTemplate](https://github.com/aspnet/BuildTools/blob/release/2.1/modules/BuildTools.Tasks/GenerateFileFromTemplate.cs). This is not currently available as a package, but is bundled in KoreBuild. I'd be happy to have this become part of MSBuild or an Arcade task library.

**Comment by weshaggard** [comment]
ILLinker is currently in an independent repo and at least for the time being should remain there. I expect that to be an option package that corefx/coreclr pull in and not be part of the SDK.

To get an  idea of some of the buildtools -> arcade tasks you can check out our project board at https://github.com/dotnet/corefx/projects/3.

**Comment by maririos** [comment]
Thanks @natemcmaster . Could you elaborate more on the need and who will use GenerateFileFromTemplate?

**Comment by maririos** [comment]
> To get an idea of some of the buildtools -> arcade tasks you can check out our project board at https://github.com/dotnet/corefx/projects/3.

Thanks for pointing me there @weshaggard . That helps to solve other questions.

**Comment by natemcmaster** [comment]
We use GenerateFileFromTemplate for simple named-variable substitution during the build. We use it in a dozen or so places when we need to generate static content during build time. Example usage:
```xml
<GenerateFileFromTemplate TemplateFile="MyFile.cs.in" OutputPath="obj/MyFile.cs" Properties="Var=$(SomeValue)" />
```
```
// MyFile.cs.in

public class Class1
{
   public string GetVar() => "${Var}";
}
```

**Comment by alexperovich** [comment]
That is #204.

**Comment by maririos** [comment]
Created issue #348 for porting Repack to Arcade

**Comment by markwilkie** [comment]
Looks like the items that should be tracked are being tracked.  Closing
