### ISSUE TITLE
[darc/maestro++] Maestro++ should convey auto-merge info using the checks API (Summer internship project)

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#3326]
Rather than using comments, which are tough to deal with in a big thread, Maestro++ should use the checks API to convey info about the auto-merge state.

The issue with the comment is that if the comment falls off the current screen, it's tough to find and get status, so we have Maestro++ update or create a new comment (update if the comment is the latest).  This results in a bunch of noise.

**Comment by wtgodbe** [comment]
Is there an ETA on this? The dotnet-maestro comments are a big headache on PRs with any significant amount of discussion

**Comment by mmitche** [comment]
no ETA.  I'll see what I can do.

**Comment by tkapin** [comment]
We have identified this task as a good project for our summer intern, who should start as of 01-July-2020 (i.e., in 6 weeks). I don't have an exact ETA for completion as it really depends on how fast he should be able to ramp up, but I assume it should get done sometimes in the Q3 timeframe.

**Comment by mmitche** [comment]
Because the checks API is fairly versatile, this could be extended into a generic Maestro app which does some other interesting things:
- Indicate where (if anywhere) the change will flow once the change is merged and the official build runs.
- Button to disable auto-merge. Today this is done by requesting changes on a PR.
- Link to corresponding official build after merge.

**Comment by tkapin** [comment]
Converted to epic as this will be the main project for our summer internship.

**Comment by lwintjen** [comment]
The issue has been solved since the rollout of yesterday (8/26/2020), the implementation of the checks has been pushed to production.

A working example of this implementation is visible [on this PR](https://github.com/dotnet/arcade/pull/6054/checks). The logic didn't change (polling every 5mins) but instead of updating a comment, we update the status of the checks. We might still have the comments on PRs that have been created before the release of this feature. These comments won't be updated anymore by maestro and the checks have been created instead (so it didn't break anything).

We can now close this issue as this is done.

**Comment by tkapin** [comment]
Repoening as this issue represents our summer internship project, which hasn't ended yet.

**Comment by MattGal** [comment]
is this issue supposed to be an epic too?

**Comment by tkapin** [comment]
Since the summer internship project has been delivered, I'm closing this epic as discussed on the last epics review (on Tue 10-Nov-2020).
