### ISSUE TITLE
Remove builds from a Maestro channel

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3364]
@vatsan-madhavan asked for all builds that contains the packages "Microsoft.NET.Sdk.WindowsDesktop" and "Microsoft.DotNet.Arcade.Wpf.Sdk" be removed from the ".Net Tools - Latest" channel. I told him that this is not possible using Darc/Maestro API but could be done directly in BAR.

Do you see any problem with this @mmitche @riarenas @jcagme ?

@vatsan-madhavan please fill in any detail that I might have miss{ed, understood}.

**Comment by vatsan-madhavan** [comment]
Context: 

Around Preview4/Preview5 timeframe, when I was prototyping the switch of WPF repo from dotnet-trusted to the Arcade SDK and dotnet-wpf-int, I was using ".NET Tools - Validation" channel for some testing. I had accidentally published a few packages to ".NET Tools Latest" at that time in error. I'd like to some assistance in cleaning up the channel so that those packages are removed. 

These packages are listed in WPF's global.json, and every time we run darc like `darc update-dependencies -c ".NET Tools - Latest"`, it brings down stales packages from preview5 timeframe, which we have to carefully undo. I'm hoping that this cleanup will fix this ongoing mess I created.

**Comment by jcagme** [comment]
Well, the latest build of https://github.com/dotnet/wpf on "".NET Tools - Latest" contains only preview5 assets. I don't want to remove metadata from BAR since it might lead to random scenarios, not just for wpf but maybe other repos as well. 

@vatsan-madhavan, I'd recommend that for those repos you get stale packages just, either, trigger a new build that publishes to ".NET Tools - Latest" or find a build (in a different channel) that has the versions you actually need and also add it to ".NET Tools - Latest". With this you'll get the packages you want when updating dependencies.

Happy to help if needed!

**Comment by vatsan-madhavan** [comment]
There are no other legitimate consumers for those packages besides wpf. Removing metadata related to those specific packages should not affect any other scenarios. 

We don't use - nor want to use - ".NET Tools - Latest" channel for these packages. These packages are published to ".NET Core 3 Dev" channel normally. Changing channels is not something we want to do either. 

The problem here really is simple - the presence of these packages in BAR metadata is nuisance for us. 

Consider this in dotnet-wpf-int repo: 

```
λ darc update-dependencies -c ".NET Tools - Latest"
git diff global.json
diff --git a/global.json b/global.json
index 1c68dea6d..d96793d7a 100644
--- a/global.json
+++ b/global.json
@@ -12,9 +12,9 @@
     }
   },
   "msbuild-sdks": {
-    "Microsoft.DotNet.Arcade.Sdk": "1.0.0-beta.19373.5",
-    "Microsoft.DotNet.Arcade.Wpf.Sdk": "4.8.0-preview8.19373.10",
-    "Microsoft.NET.Sdk.WindowsDesktop": "3.0.0-preview8.19373.10"
+    "Microsoft.DotNet.Arcade.Sdk": "1.0.0-beta.19373.6",
+    "Microsoft.DotNet.Arcade.Wpf.Sdk": "4.8.0-preview5.19222.1",
+    "Microsoft.NET.Sdk.WindowsDesktop": "3.0.0-preview5.19222.1"
   },
   "native-tools": {
     "strawberry-perl": "5.28.1.1-1",
```

Because we now inadvertently published packages in ".NET Tools - Latest" channel, we now get stale updates for `Microsoft.DotNet.Arcade.Wpf.Sdk` and `Microsoft.NET.Sdk.WindowsDekstop`, in addition to getting updates for Arcade SDK itself. The extra updates are unwanted, and cause build failures. 

The only way to fix this is not manually undo those lines from global.json, or immediately follow-up this update with another one like this:
```
darc update-dependencies -c ".NET Core 3 Dev"  
git diff global.json

diff --git a/global.json b/global.json
index 1c68dea6d..e4d170fd2 100644
--- a/global.json
+++ b/global.json
@@ -12,7 +12,7 @@
     }
   },
   "msbuild-sdks": {
-    "Microsoft.DotNet.Arcade.Sdk": "1.0.0-beta.19373.5",
+    "Microsoft.DotNet.Arcade.Sdk": "1.0.0-beta.19373.6",
     "Microsoft.DotNet.Arcade.Wpf.Sdk": "4.8.0-preview8.19373.10",
     "Microsoft.NET.Sdk.WindowsDesktop": "3.0.0-preview8.19373.10"
   },

```

This fixes up the versions by getting us the latest preview8 updates.

**Comment by jcagme** [comment]
I see, so when you update dependencies from ".NET Tools - Latest" you expect only to get Arcade related packages but you end up getting the WPF packages put in that channel by mistake?

I removed the channel from the build. Metadata still exist for that build but it is simply not in this channel.

Please try and if things work let me know so I can proceed to close the issue.

**Comment by vatsan-madhavan** [comment]
That seems to have worked. 

```
λ darc update-dependencies -c ".NET Tools - Latest"
Looking up latest build of https://github.com/dotnet/wpf on .NET Tools - Latest
Looking up latest build of https://github.com/dotnet/arcade on .NET Tools - Latest
Updating 'Microsoft.DotNet.ApiCompat': '1.0.0-beta.19373.4' => '1.0.0-beta.19373.6' (from build '20190723.6' of 'https://github.com/dotnet/arcade')
Updating 'Microsoft.DotNet.Arcade.Sdk': '1.0.0-beta.19373.4' => '1.0.0-beta.19373.6' (from build '20190723.6' of 'https://github.com/dotnet/arcade')
Updating 'Microsoft.DotNet.GenAPI': '1.0.0-beta.19373.4' => '1.0.0-beta.19373.6' (from build '20190723.6' of 'https://github.com/dotnet/arcade')
Checking for coherency updates...
Local dependencies updated from channel '.NET Tools - Latest'.

λ git diff global.json
diff --git a/global.json b/global.json
index 0c311beaa..fb1cfd8cc 100644
--- a/global.json
+++ b/global.json
@@ -12,7 +12,7 @@
     }
   },
   "msbuild-sdks": {
-    "Microsoft.DotNet.Arcade.Sdk": "1.0.0-beta.19373.4",
+    "Microsoft.DotNet.Arcade.Sdk": "1.0.0-beta.19373.6",
     "Microsoft.DotNet.Arcade.Wpf.Sdk": "4.8.0-preview8.19373.6",
     "Microsoft.NET.Sdk.WindowsDesktop": "3.0.0-preview8.19373.6"
   },
```

Thanks @jcagme!
