### ISSUE TITLE
Crossgen the Arcade toolset during bootstrapping

### ISSUE THREAD

**Issue by dagood** [dotnet/arcade#346]
BuildTools runs crossgen on itself after init-tools to help build perf. Arcade might need to do something similar. (Based on triage conversionation about https://github.com/dotnet/buildtools/issues/2102.)

@markwilkie

**Comment by weshaggard** [comment]
I would like to refrain from making a call on this until we figure out what all the tools look like. I think we will get a lot of the value by running on a shipped SDK and all those binaries are crossgen'ed, but if we end up overriding the compiler or other heavily used libraries it may become interesting to crossgen our tools as well. So I'd say lets get further along and measure before punting this issue. 

FWIW the biggest reason we needed to crossgen our tools was for linux when we were carrying our own copy of msbuild and compiler. We have since moved to using the msbuild/compiler in the SDK but haven't tested whether or not we still get big wins by crossgen'ing the rest of the tools or not.

**Comment by markwilkie** [comment]
Makes sense.  I'm going to close this for now and then we'll reopen if we need to.  (this doesn't strike me as something we'll forget if we need it)

I really like the idea of just running on a shipped SDK.  But as you say.....we'll see.  grin.
