### ISSUE TITLE
[darc/maestro++] Maestro++ hitting API rate limits

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#3595]
We are hitting api rate limits, generally during the 5am Arcade updates.  The rate limit for an app is 5k for server-to-server requests (what we use) + 50 for each member of an org, up to 12,500 max.  This is a ton.  Jenkins ran at 12,500 without issue for quite a long time.

**Comment by riarenas** [comment]
Interesting, so this causes us to lose track of any ongoing PRs if we end up getting a time out due to being rate limited, and then we end up creating multiple PRs for everyDay subscriptions.

Will be good to see if we can find the bulk of the operations that are being performed to see how we can mitigate this. 

I wonder if more people using the coherentParentDependeny attribute is causing us to build the dependency graph more often, which results in a lot of Github operations?

**Comment by mmitche** [comment]
> Will be good to see if we can find the bulk of the operations that are being performed to see how we can mitigate this.

This is the majority. 3400/9k between 5am and 6am or something like that.

**Comment by mmitche** [comment]
Should be mostly unblocked by https://github.com/dotnet/arcade-services/pull/582 but we probably need additional api call optimization.
