### ISSUE TITLE
Move Arcade (and consumer repos) to P8 SDK

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#3688]
Arcade is still using P6, and @dougbu brought this up yesterday.

@markwilkie to determine what the right timing to get the train rolling on this is.

**Comment by markwilkie** [comment]
Other than good hygiene, is there a known reason we should upgrade out of curiosity?

Regardless, I'm ok upgrading - AFTER a head's up is given to partners.

cc/ @mmitche

**Comment by markwilkie** [comment]
thoughts?

**Comment by mmitche** [comment]
I'm wary of this so late.

**Comment by dougbu** [comment]
The problem is, for those repos that haven't upgraded, functional tests aren't running with an SDK enough like customers will be using. I weigh catching problems our customers will hit before they do quite highly.

More generally, @Pilchie, @nguerrera, @livarcocc, @crummel, @JunTaoLuo, @wtgodbe and I had an interesting conversation recently that ended up focused on the disconnect between our recommendations to customers for daily build use (basically "grab the very latest from https://github.com/dotnet/core-sdk and have at it") and the lack of internal dogfood-ing with the latest SDK (because our global.json files move so slowly). The general opinion was Source Build should _not_ hold us back and our global.json files should change much more frequently.

At least setting the min bar at the last public SDK release helps the stragglers catch up.

**Comment by Pilchie** [comment]
Based on the repo-consolidation plan, I think we're instead moving to a model of separating testing out of the repo so that it could happen against a newly built SDK, so that might obviate the testing customer scenarios aspect of this point.

However, I *definitely* agree that our current source build position is untenable as it comes to SDKs.  We *have* to come up with a plan that allows teams to use the features that we build in the SDK.

**Comment by nguerrera** [comment]
It's more than testing. It's dogfooding. No matter how many tests we run against the final product, we should also be using recent bits to find things that we may not have covered in tests. It's not just to be able to pick up new features, it's to stress the existing ones that have undergone changes.

**Comment by mmitche** [comment]
We should use p9 now that it is published. This is definitely ask mode at this stage though. Let's talk about this in tactics tomorrow.

**Comment by riarenas** [comment]
We already moved repos to p9
