### ISSUE TITLE
[QCR][Validation ring] Add Symbol and SourceLink validation as one of the steps in the release process

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#3735]
Symbol and SourceLink validation add a considerable overhead to our builds and we don't need to execute them for every build anyway. The current issue is to add the execution of the SourceLink and SymbolValidation scripts as a step during one of the rings of the release process.

Some pointers for more context:

- https://github.com/dotnet/corefx/issues/40196#issuecomment-523571025
- https://github.com/dotnet/arcade/issues/2871#issuecomment-523215489

/cc @markwilkie @mmitche @leecow

**Comment by JohnTortugo** [comment]
Pinging @ericstj and @danmosemsft who showed interest in these validations.

**Comment by dagood** [comment]
I want to point out that *symbol completeness* should be checked as part of every build. It's completely local, so it should be fast and predictable, and catching symbol problems in daily builds is waaay better than waiting for a release and having to manually clean up (if possible for the specific problem!).

*Symbol availability* checks make total sense to move to a release ring, since they necessarily depend on the service and whatever delays are involved in publishing.

Completeness vs. availability described in https://github.com/dotnet/arcade/issues/2499. (And since I can't stress it enough: the current Arcade symbol validation checks are insufficient for the product, we must continue the manual check on each release until https://github.com/dotnet/arcade/issues/2499 is done.)

**Comment by danmosemsft** [comment]
@JohnTortugo should we do this work early in .NET 5? 

cc @markwilkie

**Comment by markwilkie** [comment]
Yes that's definitely the plan and @jcagme is on point.  @jcagme , could you share the timing once you get that worked out early next week please?

**Comment by jcagme** [comment]
Will do

**Comment by jcagme** [comment]
Worth looking at #2415 and and maybe #2499 as part of symbols. And #1873, #2519 and maybe #3069 as part of sourcelink

**Comment by adiaaida** [comment]
If no one is opposed, I am going to close this issue since we have added basic symbols and sourcelink validation to the pipeline, with the understanding that we have additional issues to tackle for the other parts of both.

**Comment by JohnTortugo** [comment]
Sounds good to me.
