### ISSUE TITLE
Arcade Helix SDK should not allow anonymous job submission without creator

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#4041]
@ChadNedzlek pointed this out to me that it's trivially easy to successfully send a job with no Creator... which while it should be hardened downstream is an easy fix in arcade too.

**Comment by ChadNedzlek** [comment]
Yeah, the API should reject them (we’ve needed them forever, but we just have missed it in the last version of the API), so we’ll not want to make it easy/possible to skip it client side

**Comment by MattGal** [comment]
Just want to add, it's important to do it in both places because it will save uploading job list / payloads then failing once the API is fixed.

**Comment by ChadNedzlek** [comment]
I don't think we should do anything client side here. Just call the server and let it return the error it's going to return. We don't need to duplicate all the error logic in both places, as that makes it hard to make changes (since the client and the server aren't synced together).

The server should be returning a nice clear error message saying the Creator is required, which should be more than enough to unblock people, since to fix it, they just add WithCreator to their call.

Not uploading the jobs in rare error cases isn't work duplicating the effort.  It will only happen when someone is messing around with the initial setup, and the error message is clear enough for them to unblock themselves.

We _repeatedly_ get bit by trying to add validation to the client when the server is already going to do it.
