### ISSUE TITLE
Helix SDK JobDefinition allows using the "WithFiles()" decorator but this creates non-archived payloads

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#4045]
Reported by @jaredpar .  Basically, you can with the Helix Arcade SDK call .WithFiles(string []) on a Job, and it "works" but not in the way expected, managing to include files without the automated zipping implicit in when this is used via a work item.

We should either make this fail or make the right thing (zip up and turn itno correlation payload) happen.

Since Jared just needed to move to `WithCorrelationPayloadFiles` I'm not marking this one as FR as it's less urgent.

**Comment by premun** [comment]
I was looking into this and it seems that the payload is already zipped:
https://github.com/dotnet/arcade/blob/471c65a91bb96f3ed3defc467112ffedd301d6e7/src/Microsoft.DotNet.Helix/JobSender/Payloads/AdhocPayload.cs#L21

@jaredpar can you send me an example of a failed job?

Is it possible that it was zipped but because of https://github.com/dotnet/arcade/issues/4089 it failed to get extracted correctly?

I have tried a sample job and it seems to zip/unzip files and [print them out fine](https://helixre107v0xd6tv7v8isja.blob.core.windows.net/results-d275c137ac0e4d0c89/Test%20work%20item/console.4be32c64.log?sv=2018-03-28&sr=c&sig=XG8NIq4IprWJaTfLwgOntBCAADRzWkKoI0/9cmrzfm4=&se=2019-10-24T13:09:40Z&sp=rl).

I also noticed in [the code with the workaround](https://github.com/jaredpar/arcade/commit/af3a7ae923c56dddf764bc8b3f21b1532c835727#diff-21cc9b42db7b4036514ac84dcb086161) that you are zipping a whole dir and the SDK also offers you a way to do that out of the box:
https://github.com/dotnet/arcade/blob/471c65a91bb96f3ed3defc467112ffedd301d6e7/src/Microsoft.DotNet.Helix/JobSender/IWorkItemDefinitionWithPayload.cs#L10

Or am I missing something?

**Comment by MattGal** [comment]
> Or am I missing something?

Yes, what Jared was doing was using the WithFiles() function on a Job definition, not a work item definition, and bypassing the zip behavior.  I was definitely able to reproduce this behavior at the time, ping me if you can't and I'll try to help you.

**Comment by premun** [comment]
@MattGal the only `WithFiles()` I have found is on `WorkItemDefinition` (and also in `IWorkItemDefinitionWithPayload`). Job has only `WithCorrelationPayloadFiles` which also uses `AdhocPayload` that zips files.

Based on the commit linked in this issue, commented out code is getting file names and using `WithFiles` on a work item and was replaced by manual zipping.

I am not sure which one we are talking about then.

**Comment by MattGal** [comment]
> @MattGal the only `WithFiles()` I have [found](https://github.com/dotnet/arcade/search?utf8=%E2%9C%93&q=WithFiles&type=) is on `WorkItemDefinition` (and also in `IWorkItemDefinitionWithPayload`). Job has only `WithCorrelationPayloadFiles` which also uses `AdhocPayload` that zips files.
> 
> Based on the commit linked in this issue, commented out code is getting file names and using `WithFiles` on a work item and was replaced by manual zipping.
> 
> I am not sure which one we are talking about then.

I'll make a repro then, my apologies for any confusion.

**Comment by MattGal** [comment]
@jaredpar  can't remember how he repro'ed this and I can't repro it, closing. ,
