### ISSUE TITLE
Automate product version switch over

### ISSUE THREAD

**Issue by markwilkie** [dotnet/arcade#4185]
It seems like it would be helpful to have Arcade support for the repetitive work of switching from one version to another.  (like for each preview)

Example support could be for things like:
- Branding strings
- Labels
- Branching (when needed)
- Etc.

**Comment by mmitche** [comment]
This was discussed a long while back and we decided not to pursue. The problem is that branding updates (what needs to happen before the next release) is a whole package of things, and it varies per repo and is not simple in quite a few cases. Primarily, the complexity is around corefx, winforms, wpf, extensions and aspnetcore (and maybe a couple others that I am not remembering).

The surface area of "common things that arcade could automate" is very small (maybe 0). Some examples:
- the SDK repos use a different branching and versioning structure (necessarily) than the core repos
- corefx, extensions, and aspnetcore use incremental servicing, and thus their branding update is involved and requires domain specific knowledge
- many repos individually version packages (rather than at the repo level) because of legacy interaction with the .net framework version numbers.

Some ideas of things that could **maybe** be automated:
- update a preview number in the master branch. That seems pretty minimal.
- Some tooling for branching might be useful, but it's highly unlikely to be "push button, update branching".  It's more going to be "here's a guess for what the branching for previewN could look like, modify as you need and then let the tooling create the branches"

**Comment by mmitche** [comment]
Related: https://github.com/dotnet/arcade/issues/2420

**Comment by markwilkie** [comment]
This work is happening in a concrete fashion through both ring promotion and dependency flow.  Closing this one.
