### ISSUE TITLE
darc update-dependencies --channel ".NET Core 5 Dev" fails to build

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#4289]
Reported by @RussKie :

Maestro's PR build failing to restore packages from Core-CLR : https://github.com/dotnet/winforms/pull/2278

I found it weird because:

- The repo's NuGet.config has the CLR feed which contains the package
- I was able to restore the package locally

/cc @mmitche @riarenas

**Comment by mmitche** [comment]
https://github.com/dotnet/coreclr/commit/833493193a849311b56026303bec2eaf11eb7d67#diff-3bd9381728e2fc923fcfaa12547c70bdR30  changed the suffix for the version properties in coreclr’s IL sdk, which would break any downstream repo using old the name, because it would default to 5.0.0, which doesn’t exist.

I fixed the PR in winforms to use the new name.

/fyi @ViktorHofer
