### ISSUE TITLE
NU5104 not being thrown when building runtime.native.System.IO.Ports

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4366]
The NU5104 error (stable package depends on prerelease) was not raised when packing runtime.native.System.IO.Ports.4.6.0.nupkg for release/3.0. This package ends up depending on pre-release versions of various OS specific libraries: https://www.nuget.org/packages/runtime.native.System.IO.Ports/4.6.0

When the pack task runs, it should be throwing out a NU5104.  I am not sure whether the lack of error is by design or not, but this should be investigated.

**Comment by markwilkie** [comment]
I presume this would be a nuget bug?

**Comment by mmitche** [comment]
Might be, or it may be that arcade is swallowing it.

**Comment by markwilkie** [comment]
@nkolev92 - any insight?

**Comment by nkolev92** [comment]
Is arcade calling the pack target explicitly, or using it's own pack implementation that works on top of the NuGet one? 

Looking at the package in question/dates I think the equivalent was discussed in https://github.com/NuGet/Home/issues/8827. 

We'd love for all dotnet/* repos in general to use the pack targets whenever possible instead of its own pack implementation that's built on top of NuGet's.

**Comment by garath** [comment]
@ericstj  Eric, what do you think should be done here?

**Comment by ericstj** [comment]
We use the PackageBuilder API and it doesn't enforce this.  This is a dup of https://github.com/NuGet/Home/issues/8827

**Comment by riarenas** [comment]
Closing as dupe
