### ISSUE TITLE
Orchestration of projects isn't possible with the current build logic

### ISSUE THREAD

**Issue by ViktorHofer** [dotnet/arcade#4436]
For more complex solutions (i.e. runtime repo) we need a more sophisticated build orchestration logic. We need to define dependencies between projects and build some of them in parallel and others serially. We could such necessary logic by overloading `ProjectToBuild` items with a `BuildOrder` attribute and batch on it.

cc @tmat @safern @joperezr

**Comment by tmat** [comment]
Can you give an example of the dependencies and requirements? Not saying this is not needed or useful, but I would like to see more details on why is this needed as opposed to using standard msbuild build mechanisms for expression dependencies (like `ProjectReference`, or `PackageReferece`), or moving some projects to infra repo. Note that the more we deviate from standard project build logic the less will standard VS tooling be useful in these repos.

**Comment by dagood** [comment]
> build some of them in parallel and others serially.

This is something the subset infra is designed for. If every project in a set of projects A is depended on by every project in a set of projects B, then A will run "serially" before B. If everything in C depends on all of B, then you have a serial sequence "A, B, C" where each set contains a bunch of projects.

This is done in practice by the installer (core-setup) signing infra. All installer bundle projects require the MSIs to be signed, so they wait on a one-round-trip "sign MSIs" project, which depends on each project that creates an MSI. Then each bundle project goes in parallel to package up the MSIs it cares about. "Build MSIs, Sign MSIs, Bundle MSIs" in sequence.

`ProjectReference` (and I guess `PackageReference`, but that's news to me) is a built-in way to declare these dependencies, but if those items have unwanted side effects, you can just `<MSBuild ...` the dependency project and the engine handles concurrency. (With some pretty simple caveats: the targets and properties need to be the same so it's a "hit" in the cache.)

I don't think that we *can't* go with a simple batching approach, for simplicity, especially in the short term. Perf may also be a consideration--I don't know how heavy these `<MSBuild ...` "locks" are. But I agree with @tmat the general solution for dependencies does cover this.

**Comment by jkoritzinsky** [comment]
The main issue I saw when trying to use dependencies expressed via `<MSBuild ...>` tasks was MSBuild didn't seem to wait for a target to finish before it started running it again in parallel on a different node, which the CoreCLR build is extremely fragile to (I never got a successful build in this state).

Additionally, even once I serialized it, the MSBuild cache for whatever reason didn't cache the result (probably since there is no up-to-date information in the CoreCLR project), causing it to build over 10 times and significantly slow down the overall dotnet/runtime build even though the builds were mostly incremental (some parts of the coreclr build aren't fully incremental yet).

**Comment by dagood** [comment]
Thanks for the notes. I don't understand the target locking expectation, but that just speaks to my ignorance of the CoreCLR build.

> the MSBuild cache for whatever reason didn't cache the result

I've only seen this if the global properties weren't the same between both MSBuild calls. (And in that case, they very reliably aren't cached. 🙂) I don't think we can rely on incremental builds for this, because they don't have any locking mechanism, unlike the projects.

**Comment by tmat** [comment]
@rainersigwald for recommendations.

**Comment by rainersigwald** [comment]
@jkoritzinsky can you share a binary log (https://aka.ms/msbuild/binlog) of a build where you were experiencing these problems, or a patch to replicate your experiment? I don't think I understand the problems you're describing.

**Comment by jkoritzinsky** [comment]
I'll need to recreate the setup I had, so it might be a bit, but I'll send over a binlog once I have a chance to try this again.

**Comment by markwilkie** [comment]
Closing this as it seems likely we were able to move on.  Feel free to reopen if more needs to be done.
