### ISSUE TITLE
Publishing should use correct default channel to determine which stages should run

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#4470]
Right now, if two branches with the same sha are pushed to a repo, e.g:
- internal/release/3.0
- release/3.0
(commits match)
And the following default channel is set up:
`https://dev.azure.com/dnceng/internal/_git/dotnet-winforms @ internal/release/3.1 -> .NET Core 3.1 Internal Servicing`

Then Maestro will correctly assign the build to the 3.1 internal servicing channel.  However, publishing will not run for that build, as the build's default channel association will mention the internal repo, but the github repo uri for the build will be valid.

In this case, publishing is skipped because the system incorrectly thinks that the build will not apply to the internal channel.

**Comment by mmitche** [comment]
@riarenas Can you take a look at this after your wpf-int investigation?

**Comment by riarenas** [comment]
Do you have an example build where you saw the incorrect behavior?

**Comment by mmitche** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=442020&view=results

**Comment by riarenas** [comment]
Testing fixes to the [PushMetadataToBuildAssetRegistry task](https://github.com/dotnet/arcade-services/blob/a3973f4f8cdb98f2f2ad07436dca207cb5bb5901/src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs#L102-L106) so that even if a repo has a valid GitHubBranch and GitHubRepository, we still check the default channels for the AzDO side. 

Also adding some additional logging so that we can easily tell which default channels we found to be a match.

**Comment by riarenas** [comment]
Currently trying to produce a published package of the maestro tasks that I can update arcade with, and then try another arcade build that should publish to the right channels.

**Comment by riarenas** [comment]
Having some issues getting the new publishing task to show the logs I'm expecting. Still working on this one.

**Comment by riarenas** [comment]
Change to the Maestro tasks in https://github.com/dotnet/arcade-services/pull/827. Will need a follow up PR to Arcade to consume the changes.
