### ISSUE TITLE
Ubuntu environment conflicts with arcade 

### ISSUE THREAD

**Issue by jaredpar** [dotnet/arcade#458]
Discovered this issue when I recently updated my Ubuntu box and started working on Roslyn. My build failed with lots of errors because the C# language version was 7.0 instead of 7.3 as is specified in our properties file. The problem appears to be a conflict with the properties used in RepoToolse / Arcade and environment variables defined in Ubuntu. 

Ubuntu now defines `%LANGUAGE%` for all terminals started from it's GUI. The value for me was `"en_US"`. This means though that `$(Language)` has a default value when MSBuild is invoked. As a result this block of MSBuild logic doesn't execute.

``` xml
  <PropertyGroup Condition="'$(Language)' == ''">
    <Language Condition="'$(MSBuildProjectExtension)' == '.csproj'">C#</Language>
    <Language Condition="'$(MSBuildProjectExtension)' == '.vbproj'">VB</Language>
    <Language Condition="'$(MSBuildProjectExtension)' == '.fsproj'">F#</Language>
    <Language Condition="'$(MSBuildProjectExtension)' == '.vcxproj'">C++</Language>
  </PropertyGroup>
```

This mean any specialization based on `$(Language)` in repos won't actually execute when building in Ubuntu GUIs (and I imagine a few others). I'm not sure what the best way to deal with this is.

**Comment by jaredpar** [comment]
CC @tmat

**Comment by nguerrera** [comment]
`$(Language)` is a real thing in core msbuild  targetsand can't be en_US

Here we seem to be trying to set it earlier than the language targets, which would just overwrite it.
https://github.com/Microsoft/msbuild/blob/0591c15d6c638cad38091fbe625dde968f86748d/src/Tasks/Microsoft.CSharp.CurrentVersion.targets#L40

So I think for this specific issue it is a reasonable fix to remove the condition.

Otherwise, revisit why arcade is setting Language and not leaving it up to the language targets.

**Comment by tmat** [comment]
Yes, the purpose is to set it early so that we can use language-specific conditions in props files.

I think we could remove the condition `Condition="'$(Language)' == ''"` on the property group above.
