### ISSUE TITLE
Noise in test failure of Arcade Helix SDK

### ISSUE THREAD

**Issue by wli3** [dotnet/arcade#4581]
-  Is this issue blocking
no

-  Is this issue causing unreasonable pain
no

Take [this](https://dev.azure.com/dnceng/public/_build/results?buildId=468597&view=ms.vss-test-web.build-test-results-tab&runId=14913186&resultId=100222&paneView=debug) for example. Every test failure has a counter part "xxx.dll Work Item" failure. It makes the test result hard to understand.

![image](https://user-images.githubusercontent.com/6993335/71696121-f9dbc600-2d68-11ea-9836-11f1360f56c6.png)

@alexperovich @MattGal

**Comment by MattGal** [comment]
This is a very tricky thing to solve because of the risk; in the case of the Work Item failures at the bottom, this is caused by the Helix work items returning non-0.  If the Helix work item both ends up returning a 0 exit code AND fails to report to Azure DevOps, then there will not be any "failing tests" reported, potentially resulting in passing.

My opinion: 

- The success of submitting results to Azure DevOps relies on a lot of factors and could be broken in a variety of ways outside our control.  Further the Work Item logs provide the full console and harness logs of the work items and is the only place to access this without hitting the Helix API.  I would prefer we keep things as-is but perhaps come up with a way to "nest" the work item failures into a single "test".
- The only way I'd want to exclude this is if the code running on the build agent pipeline were able to hit the AzDO API and successfully get some test result; if we're 100% certain that there are AzDO results of some kind that match this work item it'd be fine to exclude (though it would still remove some fidelity from the logging, i.e. the raw console spew which includes call stacks and errors)

**Comment by wli3** [comment]
Sorry for the delay. I missed the comment notification.

Any way to correlate them? Like having a guid for the "work item" failure and the log. And we can merge them into one.

**Comment by MattGal** [comment]
> Sorry for the delay. I missed the comment notification.
> 
> Any way to correlate them? Like having a guid for the "work item" failure and the log. And we can merge them into one.

At the point the fake work item is being created for failed work, we do know a GUID that is distinct for every Helix work item, so that could be done, however I question the utility of such a thing since a friendly name is going to be a lot easier on the human eye and brain than a workitem's GUID that varies with every single run.

**Comment by wli3** [comment]
It is more on once we have the guid, we should be able to link them together automatically, and remove the extra failure item. Looks like it is not straightforward to resolve them and it does not hurt the functionality. I'll close it for now. We don't have too much activity on master branch yet. If I heard more complain about this later. I'll reopen it.
