### ISSUE TITLE
Publish feed locked by Microsoft.Cci.Extensions

### ISSUE THREAD

**Issue by jaredpar** [dotnet/arcade#4636]
The official build of dotnet/runtime is failing during it's "Publish Assets" stage. The final error is a timeout but looking into the log we see that the publish step is encountering the following error repeatedly.

```
2020-01-15T11:12:23.1164649Z   Verifying https://dotnetfeed.blob.core.windows.net/dotnet-core exists.
2020-01-15T11:12:23.4591428Z   Found https://dotnetfeed.blob.core.windows.net/dotnet-core
2020-01-15T11:12:23.7714601Z   Waiting to obtain feed lock. Feed is locked by: Push of Microsoft.Cci.Extensions.5.0.0-beta.20064.7 since: 01/15/2020 06:00:46
2020-01-15T11:17:47.7517828Z   Waiting to obtain feed lock. Feed is locked by: Push of Microsoft.Cci.Extensions.5.0.0-beta.20064.7 since: 01/15/2020 06:00:46
2020-01-15T11:18:17.9931474Z   Waiting to obtain feed lock. Feed is locked by: Push of Microsoft.Cci.Extensions.5.0.0-beta.20064.7 since: 01/15/2020 06:00:46
```
Overall this takes 1+ hour to resolve and eventually causes that job to timeout. 

Example builds:
- https://dev.azure.com/dnceng/internal/_build/results?buildId=483734
- https://dev.azure.com/dnceng/internal/_build/results?buildId=483901

**Comment by dagood** [comment]
@MattGal @mmitche @jcagme @markwilkie

**Comment by riarenas** [comment]
This is due to what happened with https://github.com/dotnet/arcade/issues/4635.

The first attempt of https://dev.azure.com/dnceng/internal/_releaseProgress?releaseId=28721&_a=release-environment-logs&environmentId=88396 failed due to an AzDO problem with the agent during its publishing, which I believe left the lock in the feed in an inconsistent state.

The timing fits, but since there was a communication error with the agent, there are no logs at all for the publishing job. The feed was unlocked once the publishing job was finally cancelled after the default timeout of 6 hours.

@JohnTortugo is actively working on getting us away from the release pipelines for the publishing, and I reduced the timeout for the publishing pipeline job so that the feed won't be locked for so long.

**Comment by riarenas** [comment]
I'm closing this since the feed should be unlocked now, and it shouldn't stay locked this long anymore. Feel free to reopen if you see this again.

**Comment by riarenas** [comment]
Also for some more details:

Arcade is one of the few repos that still does actual publishing during the release pipeline due to how the build publishes only to the validation channel, and we only move it to the general consumption feeds after we've performed some validation of the SDK.

Most repos don't move from one channel to another during their normal flow, so all their final publishing happens in the publishing stages of the build pipeline.
