### ISSUE TITLE
[arcade-services] BarViz INT is failing to load

### ISSUE THREAD

**Issue by alexperovich** [dotnet/arcade#4758]
https://maestro-int.westus2.cloudapp.azure.com/ is currently failing with the following error:
Uncaught TypeError: Cannot read property 'curveLinear' of undefined
    at Object.cSR1 (vendor.4440b98fef4fe902be4a.js:formatted:48556)
    at f (runtime.26209474bfa8dc87a77c.js:1)
    at Object.EiaH (vendor.4440b98fef4fe902be4a.js:formatted:17993)
    at f (runtime.26209474bfa8dc87a77c.js:1)
    at Module.zUnb (main.3ec08af1b26dffef1c7f.js:1)
    at f (runtime.26209474bfa8dc87a77c.js:1)
    at Object.0 (main.3ec08af1b26dffef1c7f.js:1)
    at f (runtime.26209474bfa8dc87a77c.js:1)
    at t (runtime.26209474bfa8dc87a77c.js:1)
    at Array.r [as push] (runtime.26209474bfa8dc87a77c.js:1)

**Comment by adiaaida** [comment]
Alex and I tracked this down to the fact that we have minification turned on for BarViz and the d3 package not meeting the coding guidelines angular-cli has set in place for functional minification. Essentially, certain getters are being optimized away. After searching around for a bit, I found that this is a known issue, see https://github.com/angular/angular-cli/issues/11439. That issue lays out the fact that the angular cli folks know about this sort of thing and are not going to update angular-cli to allow greater controllability of the UglifyJS options. The community has suggested the following options:

1. Turn off optimization (this will double the size of the bundle).
2. Turn off buildOptimize (likely will do the same as wholesale turning off optimization.
3. Create a patch file that modifies the angular-cli file that sets pure_getters to true, and make it default to false. People who have tried this suggest that it only increases their bundle size a small amount (I think one person said 0.7%), and allows for full functionality.

My plan is to try option 3 today and sees how that goes. If it works, great. Otherwise, we will need to discuss either using option 2, or reworking the code that uses d3 to render the graph to use angular to render this. We did it that way in mission control, so it should be doable, but will take more time.

**Comment by adiaaida** [comment]
After a little more digging, and attempting option 3 (which failed), I found this issue in d3-color: https://github.com/d3/d3-color/issues/68. It suggests upgrading angular-cli to version 8. @alexperovich do you see any issue with this?

**Comment by riarenas** [comment]
Reopening until rollout.

**Comment by riarenas** [comment]
This is rolled out.
