### ISSUE TITLE
Decrease noise on test failures

### ISSUE THREAD

**Issue by wfurt** [dotnet/arcade#4779]
For example https://github.com/dotnet/runtime/pull/31860/checks?check_run_id=430072789  with one test failure.

when viewing on GH, it has four entries for a single failure. First two almost identical so as to last two.  This gets even more messy with more failures and it more difficult to read.
It would be nice if each failure has exactly one entry with sufficient information.
Note that the trailing '.' after Console link makes it more difficult to cut & paste. It would be really nice if that is on a separate line with no trailing characters. 

![image](https://user-images.githubusercontent.com/14356188/73964134-7d3b8a80-48c6-11ea-9d8e-0852fb84e93d.png)

**Comment by markwilkie** [comment]
Thoughts on this @alexperovich ?

**Comment by alexperovich** [comment]
The first 2 is because we just have 2 log statements for that failure: https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Helix/Sdk/CheckHelixJobStatus.cs#L39

We can just merge those log statements to fix it.

The third one is an error produced by the build scripts to write an error "Build failed" when the msbuild invocation fails. I don't remember exactly where this is.

The fourth error is a standard error from azure pipelines that gets produced when any script task fails, I don't think there is a way to remove it.

**Comment by alexperovich** [comment]
I merged https://github.com/dotnet/arcade/pull/5211 to remove the duplication of the first 2. The other 2 we can't remove easily.

**Comment by markwilkie** [comment]
Closing as we did our best to improve.  Free free to reopen if you feel strongly of course.
