### ISSUE TITLE
Create passing AzDO test run result for Helix Work Items

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/arcade#4836]
-  Is this issue blocking (yes/no) no
-  Is this issue causing unreasonable pain (yes/no) no

At the moment we only generate a failed test run if a Helix work item hangs/crashes.
If the work item succeeds then we only ingest the unit test results itself but don't create a passing result for the overall work item.

This results in test analytics like below:

![image](https://user-images.githubusercontent.com/1376924/74382299-7395b380-4ded-11ea-8925-906ae7ee855a.png)

AzDO can't calculate the real pass rate since it only knows about the failed work items. We should report passing work items too.

/cc @alexperovich

**Comment by ChadNedzlek** [comment]
I'm concerned about this overflowing out frontends. The reason we went to this minimal method is because the constant pinging of our frontend totally destroyed our website availability.  If we switch to this method, we are going to have to seriously back off on the polling interval... which will slow test reporting down.

Or maybe we could only return these from the API when there are none still running, assuming that the caller won't care until then...

**Comment by ChadNedzlek** [comment]
Are the workitem level analytics in AzDO useful? Right now we only generate that item because we are desperately attempting to communicate to the user that all is not well.  This change might take out production if we try it (since we can't really know without scale testing), and I'm not sure the scenario is there.

**Comment by ChadNedzlek** [comment]
I'm going to remove the FR tag.  The issue says in the description that it isn't blocking, and there is significant risk to this ask.

**Comment by akoeplinger** [comment]
@ChadNedzlek I don't understand what you mean by `constant pinging of our frontend`? There would be no additional call to the Helix service and only one additional call to AzDO APIs for each workitem.

**Comment by ChadNedzlek** [comment]
Every build kicks of all the helix item, then just sits in a loop, calling this API over and over, sometimes for upward of an hour, and we have to answer over and over, until it's finally complete.

It's not a huge amount of data, but it's a _lot_ of calls for the relatively small service that's running the API frontends.  This API exists and is as small as it is because the API it was calling before was the older API that showed a few more details, and our servers cracked under the pressure.

If we tweaked it to only return the successful list when none are still running, on the assumption the callers would only ever ask that question once per job, because as soon as we answered with that status, they should exit that loop, things would probably be fine.  But we do need to be careful.

**Comment by akoeplinger** [comment]
Talked with @ChadNedzlek offline and we found a way to keep the data size small on the API side by only returning the passed work item names when all work items are done.

**Comment by ChadNedzlek** [comment]
Chatted with @akoeplinger.

The server side PR he patiently work through is here: https://dnceng.visualstudio.com/internal/_git/dotnet-helix-service/pullrequest/6794?_a=overview.  Since we went with the "only add the extra data on the last call" things should be ok.

I'm going to make sure it gets rolled out and everything, and when that happens, we can then work on the arcade side of things.

**Comment by markwilkie** [comment]
Adding this to your epic @ChadNedzlek

**Comment by akoeplinger** [comment]
@alexperovich was this done? if not I'd be up for contributing the change :)

**Comment by ChadNedzlek** [comment]
Yup. It was, and checked into arcade. The next arcade promotion + update should get you this behavior for free.

We mostly did it because the history reporting on Azure DevOps isn't great if you don't report the passes. :-)

**Comment by akoeplinger** [comment]
Awesome, thank you! Linking the PR here for completeness: https://github.com/dotnet/arcade/pull/6440
