### ISSUE TITLE
Support WaitForWorkItemCompletion in Helix.MonoQueue

### ISSUE THREAD

**Issue by BrennanConroy** [dotnet/arcade#4847]
-  Is this issue blocking (yes/no) no
-  Is this issue causing unreasonable pain (yes/no) no

Easy workaround, just use `HelixTargetQueues` with a single item instead of `HelixTargetQueue`

**Comment by markwilkie** [comment]
Any comments @ChadNedzlek or @alexperovich ?

**Comment by alexperovich** [comment]
This isn't something we should do. The "workaround" is what should be done. Supporting this would require refactoring a large amount of msbuild and be even more complicated that what is there already.

**Comment by ChadNedzlek** [comment]
We should probably work on getting rid of the thing that doesn't work then.

**Comment by garath** [comment]
Traige: Investigate and recommend. @ChadNedzlek

**Comment by ChadNedzlek** [comment]
We can't remove the existing method, because it's really an internal implementation detail, but there is no such concept in MSBuild.  We can't stop people from using the internals.

In this case, however, the correct usage of the Helix SDK is to use the "HelixTargetQueues".

If there is some incorrect documentation that leads users down the wrong path, we should update that.
