### ISSUE TITLE
Remote executor swallow exception of async Action.

### ISSUE THREAD

**Issue by aik-jahoda** [dotnet/arcade#4912]
Remote executor swallow exception of async Action.

**Repro:**
```c#
RemoteExecutor.Invoke(async () =>
{
    Assert.True(false);
    await Task.Delay(1);
}).Dispose();
```

**Expected behavior:**
An exception is thrown by RemoteExecutor.Invoke.

**Actual Behavior:**
No exception is thrown.

-  Is this issue blocking (yes)
-  Is this issue causing unreasonable pain (yes)

**Comment by aik-jahoda** [comment]
cc @ViktorHofer

**Comment by ViktorHofer** [comment]
@stephentoub are you aware of this issue? Do we need an InvokeAsync path?

**Comment by stephentoub** [comment]
What overload of RemoteExecutor.Invoke is that binding to?  I don't see one defined in https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.RemoteExecutor/src/RemoteExecutor.cs that takes a `Func<Task>`, which means you're almost certainly binding to the one that takes an `Action`, which means your async lambda is actually an async void lambda... not only are exceptions going to be propagated differently, but the Invoke call will actually complete the moment you await something that's not yet completed, breaking the whole test.

If this is a mistake folks are frequently making, I suggest adding a `Func<Task>` overload.  In the meantime, try returning SuccessExitCode from the lambda body so that the compiler will bind to the `Func<Task<int>>` overload that does exist.

**Comment by aik-jahoda** [comment]
I created a PR with adding Func<Task> overload. It is possible when we merge this PR some tests will start fails as an exception will be handled correctly and the invoked callback will finish completely.

**Comment by stephentoub** [comment]
> It is possible when we merge this PR some tests will start fails as an exception will be handled correctly and the invoked callback will finish completely.

Can you please use this to execute the dotnet/runtime tests before merging it?

**Comment by aik-jahoda** [comment]
Yes, I will run the test with this fix before merge. Will share result here.

**Comment by aik-jahoda** [comment]
There are two failing tests and they are disabled by following PR: https://github.com/dotnet/runtime/pull/33560.
There is a ticket to re-enable them again: https://github.com/dotnet/runtime/issues/33558 when the remote executor is deployed.

**Comment by aik-jahoda** [comment]
@ViktorHofer, @stephentoub do you agree with this change? Can I merge it?

**Comment by ViktorHofer** [comment]
I'm fine with the change but @stephentoub should decide as he is the expert on async.

**Comment by stephentoub** [comment]
> do you agree with this change? Can I merge it?

Which PR?

**Comment by ViktorHofer** [comment]
https://github.com/dotnet/arcade/pull/4927
