### ISSUE TITLE
[Publishing] Add the ability to publish to myget

### ISSUE THREAD

**Issue by maririos** [dotnet/arcade#494]
We need to port the necessary parts for Buildtools in order to be able to publish to myget.

The target `NuGetPush` is the one that repos are consuming. It comes from: https://github.com/dotnet/buildtools/blob/a4da379c014274e977f94ba4b037d18a90658050/src/Microsoft.DotNet.Build.Tasks/PackageFiles/PublishProduct.targets which calls Build tasks like `ExecWithRetriesForNuGetPush` defined in  https://github.com/dotnet/buildtools/blob/a4da379c014274e977f94ba4b037d18a90658050/src/Microsoft.DotNet.Build.Tasks/ExecWithRetriesForNuGetPush.cs

**Comment by JohnTortugo** [comment]
So, can someone advise if the steps below sound right? @jcagme @chcosta @alexperovich @tmat 

1. Copy `ExecWithRetriesForNuGetPush.cs` into `Microsoft.DotNet.Build.Tasks.Feed\src`
2. Copy the `NuGetPush` target into `Microsoft.DotNet.Build.Tasks.Feed.targets`
3. Patch Arcade SDK `Publish.proj` file to recognize a new flag `PushToNuGet` and call the copied over target
4. Perhaps some change in Arcade SDK `Build.proj`

At the momment I'm not quite familiar where each file should be copied over and how they should be plugged together. Advices on that direction will be appreciated :-)

**Comment by tmat** [comment]
@mmitche Re publishing. 

Is this about myget or nuget? 

My understanding is that the build always uses `PushToBlobFeed` build task to publish. 
The items passed to this task are annotated with shipping/non-shipping flag.
Based on this flag and some publishing configuration for the repo `PushToBlobFeed` decides whether to push to nuget, myget, etc.

**Comment by mmitche** [comment]
myget and nuget have the same process for pushing.

For prodcon v1, we changed the repos over so that they push to an isolated blob feed, then the results are pushed to other blob feeds/myget based on decision making later (generally, did other builds pass). I'd like to keep this model for prodcon v2 where possible.  Repos can still publish directory to endpoints if needed (e.g. they don't participate in prodcon v2 flow) but in general:

- Publishing is done to an isolated feed per-build. This feed is generally (always?) private.
- Build Asset Registry events + build metadata (e.g. is build of an internal branch, on an internal channel, etc.) trigger what kind of downstream publishing should happen.

This solves a few problems:
- In speculative flow, we'll have throwaway builds.  Why would these be made public
- Builds don't need to generally worry about what endpoints should and shouldn't be pushed to, based on what was built.
- Stabilization/final release cases get easier, because each repo doesn't need worry about setting the right set of parameters to avoid publishing unfinished stable bits.

That said, we do need nuget publishing in arcade.  It just probably won't be called directly by the build.

**Comment by jcagme** [comment]
To answer @JohnTortugo's question. The approach to build the task seems reasonable. Choosing when we want to publish to myget/nuget can be decided on data in BAR as @mmitche describes. 

We could have a stand alone "Publish to myget/nuget" build definition that gets triggered (by Maestro++?) when the data in BAR indicates that's needed.

**Comment by JohnTortugo** [comment]
Thank you all for clarifying this. So, do I only have to implement the first two steps and the build definition will be able to call the task or should I add it to the SDK (Publish.proj) as well?

1. Copy `ExecWithRetriesForNuGetPush.cs` into `Microsoft.DotNet.Build.Tasks.Feed\src`
2. Copy the `NuGetPush` target into `Microsoft.DotNet.Build.Tasks.Feed.targets`
