### ISSUE TITLE
[Arcade-Validation] Arcade-Validation official build is failing to move the build to the "latest" channel

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#5043]
- [x] This issue is blocking
Arcade-validation cannot move arcade builds to the latest channel due to this
- [ ] This issue is causing unreasonable pain

The arcade-validation pipeline is failing to move builds to the ".net eng - latest" channel due to a problem with how it triggers the build promotion pipeline, not waiting long enough for the build to be in the channel before failing the build.
https://dev.azure.com/dnceng/internal/_build/results?buildId=556472&view=results

We need to do some changes to the mechanics for how we wait for the channel addition to finish, in reaction to https://github.com/dotnet/arcade/issues/4863

**Comment by markwilkie** [comment]
@JohnTortugo - are you the right person to look at this?

**Comment by JohnTortugo** [comment]
@markwilkie - yeah, I worked on this recently. I'll work on a proper fix.

**Comment by JohnTortugo** [comment]
The problem was that the release pipeline was still running when the promotion build finished. That caused Darc to understand that the build was already promoted but it was still not -- it is only promoted after the release pipeline finishes.

The fix here was just to remove the release pipeline associated with the channel.

I'm moving the issue to Validate to keep an eye on next builds.
