### ISSUE TITLE
Implicit version update with auto generated feed approach 

### ISSUE THREAD

**Issue by wli3** [dotnet/arcade#5050]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

The symptom is, **every month** for implicit version SDK team need to update all servicing branch's' feed like https://github.com/dotnet/core-sdk/pull/6268/files. At the same time, once these package released. SDK team need to remove them. Again every month for all servicing branch.

> Is it not possible to bring in those dependencies using a way that is supported by darc?

no...because there's way to flow multiple versions of the same dependency. The way this is done implies that you cannot finish any uplevel release before all down-level releases are complete.

Historically, SDK team has some solutions for several generations of infra. We had a solution in orchestrate build time. And we also has time tests infra when there is no auto generated feed. We do need to work together to solve this situation again.

**Comment by wli3** [comment]
short term solution https://github.com/dotnet/arcade/issues/5051

**Comment by mmitche** [comment]
I don't think Maestro can solve this problem. I think the problem needs to be solved in how we deal with implicit versions and associated testing in the SDK. Maybe the testing gets moved to CTI, or to another set of automated testing after the build.  Consider the following scenarios:
- 2.1 release is an internal servicing release, but 3.1 is public. Testing implicit versions will be impossible in the public.
- 2.1 build isn't done yet.
- 2.1 build gets a new fix after 3.1 is done. You have reset 3.1 again to get testing,

None of those scenarios is solvable, and we cannot get into a situation where a downlevel release's internal/public nature drags newer releases along with it, and we cannot be in a situation where we have to serialize builds.

How often have these tests ever failed due to real reasons? Could we do something like this instead:
- Update implicit package versions without the feeds
- Test against the previously released runtimes to ensure downlevel targeting works.

/cc @dsplaisted 

I'll leave this issue open for a bit, but this is not an issue that arcade or Maestro can help with.

**Comment by riarenas** [comment]
@mmitche Should this issue be moved then, or just close?
