### ISSUE TITLE
Build promotion pipeline not honoring repo's PublishInstallersAndChecksums

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5063]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The PublishInstallersAndChecksums variable is not being propagated to the promotion pipeline.

**Comment by mmitche** [comment]
@JohnTortugo

**Comment by JohnTortugo** [comment]
I'll take a look once I'm out of FR.

**Comment by JohnTortugo** [comment]
@mmitche - Since this is a repo specific thing I think the only way to handle this is by adding a new parameter to the build promotion pipeline and also to `darc add-build-to-channel` to let the user specify the value of `PublishInstallersAndChecksums` to be used on the promotion build. Is that sufficient or do you have something else in mind / another idea?

**Comment by mmitche** [comment]
@JohnTortugo Yeah probalby fine.
