### ISSUE TITLE
[darc/maestro++] Allow for default channel branches to be specified as a pattern

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#5131]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

To protect against problems such as the one seen in https://github.com/dotnet/arcade/issues/5102 where a newly created branch without a default channel wasn't publishing, we should allow default channels to be specified as a pattern rather than a direct match, so that similarly named branches that need to always publish to the same channel will automatically be onboarded to publish.

**Comment by mmitche** [comment]
@AdamYoblick @Shyam-Gupta We started working on this but I have a question/concern:

**Is assignment to the channel being used for anything more than publishing?**

If it is, I have serious concerns about this feature. It means that if you have a p1, p2, and p3 branch, you'll be relying on a logical progression of branch usage (p1, then p2, then p3) where there is no usage of an old branch after a new one comes into use. Otherwise, an accidental or intentional build of an old branch will result in functionality regressions in downstream repos.

If it's really just for publishing only, however, then I think this is fine.

/cc @MattGal

**Comment by MattGal** [comment]
(I'm going to wait to hear back before proceeding on this issue)

**Comment by AdamYoblick** [comment]
This request is for winforms-designer which is not part of the core sdk product.

Our CI builds inject directly into VIsual Studio via insertion PRs. The main annoyance was whenever we snapped a new release branch we had to add a default channel to enable 1) nuget package publishing (for third party control vendor companies) and 2) for symbol publishing.

So yeah it’s for publishing :)

________________________________

**Comment by MattGal** [comment]
This update rolled out yesterday, closing issue.
