### ISSUE TITLE
[darc/maestro++] darc-add-build-to-channel build promotion pipeline should fail early if trying to promote to a channel without a publishing implementation

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#5141]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The build promotion pipeline should fail early if we see that the build is being promoted to a channel that doesn't have a publishing implementation. The build won't actually do anything, and it's misleading when it succeeds and just shows a warning that it couldn't find the channel.

**Comment by JohnTortugo** [comment]
The validation that emits this warning is in one of the post-build YAML, not only in the promote build YAML. If we do the change there it'll affect build creation as well. I think we should do it there and have the validation at build creation & promotion time. Do you agree?

**Comment by JohnTortugo** [comment]
Update on this after some investigation:

The risk of doing the validation at build creation time is if some repository has the same branch configured with default channels of different releases of .net core. For instance, Roslyn has this branch [release/dev16.6-vs-deps](https://github.com/dotnet/roslyn/tree/release/dev16.6-vs-deps) configured with channels for 3.x and 5.x. If we fail a build because one of the default-channels doesn't have an YAML then Roslyn build will fail.
