### ISSUE TITLE
[QCR][Validation ring] Package validation should check dependencies

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5178]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

A few times in the past, we have shipped packages that depend on either non-shipping packages or packages that don't exist at all. For example, https://github.com/dotnet/runtime/issues/34351.

During the validation stages, we should check that a shipping package's dependencies are one of the following:
- Already released (e.g. nuget.org).
- Available within the set of shipping packages in the current build.

There may be some corner cases here. For exampl, where dependencies cross product version boundaries (e.g. a 5.0 package that depends on a package that is about to ship in a 3.1 release), the package will be published but wouldn't be available in the two places listed above.

We should error in the validation stages, with the potential to skip the error if we determine the error is expected

**Comment by JohnTortugo** [comment]
Looks like related to this: https://github.com/dotnet/arcade/issues/5073

**Comment by jcagme** [comment]
Ack'd

**Comment by ericstj** [comment]
FWIW we already test this for most packages in dotnet/runtime.  We missed this package because it is "special" - a meta-package.  https://github.com/dotnet/runtime/issues/27503

The testing we do in dotnet/runtime is actually installing the package we build, so it needs to understand everywhere the package is expected to install in order to test.  This covers more than suggested in this issue.

The suggestion in this issue could be implemented independently without knowing where a package should install, so it's probably a beneficial one that can be implemented without additional knowledge.

**Comment by dougbu** [comment]
> There may be some corner cases here

How would this work detect references in (say) dotnet/aspnetcore to non-shipping packages from dotnet/runtime?

**Comment by mmitche** [comment]
> > There may be some corner cases here
> 
> How would this work detect references in (say) dotnet/aspnetcore to non-shipping packages from dotnet/runtime?

If we took the unified drop of what we want to release (a candidate), I can take the shipping package directory, which contains runtime, aspnetcore, etc. and the dependencies in each of the packages should either be also in that shipping package directory or on an official release point like nuget.org.
