### ISSUE TITLE
Helix JobSender scenario test parity for the DirectApiTests's job/work item send tests

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#5189]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

In Helix, the DirectApiTests have Job send scenario tests with full coverage of those APIs. Those tests should be ported to the JobSender as good validation for it handling these scenarios properly as well.

**Comment by garath** [comment]
Triage: @ChadNedzlek FYI

**Comment by missymessa** [comment]
I think this was supposed to go into the Validation epic.

**Comment by ChadNedzlek** [comment]
JobSender can't talk to old versions of the the API (by design).  There is no real way to do this without drastically changing how JobSender works (make it have a dozen versions), which would make using it much harder.

The JobSender needs to tests that it can send the right stuff as it's designed. And these tests should be in arcade (where the JobSender).

The API tests need to test that _all_ versions of the API work.  And these tests need to be in Helix (where the API id).

This isn't a two bird with stone situation, I'm afraid.

**Comment by ChadNedzlek** [comment]
If this issue is just "there isn't enough coverage of JobSender", that's fine and we can reopen it, but there are a lot of API's that JobSender doesn't expose, because it's not super useful to do so, that and the versioning thing.

I think looking at each piece independently to decide if the coverage is good is better than just shooting for parity.
