### ISSUE TITLE
Arcade-Services meastro-int SF deployment is broken

### ISSUE THREAD

**Issue by sunandabalu** [dotnet/arcade#5221]
- [x] This issue is blocking from getting green builds needed for a prod deployment
- [ ] This issue is causing unreasonable pain

https://dev.azure.com/dnceng/internal/_build/results?buildId=590595&view=logs&s=d4a9a205-d52e-57fb-7b17-15a9d984af62&j=b277f1ae-44e7-5ce4-4818-00049b2c7654

**Comment by alexperovich** [comment]
This is completely normal behavior for service fabric. A look at the application status: https://maestro-int.westus2.cloudapp.azure.com:19080/Explorer/index.html#/apptype/MaestroApplicationType/app/MaestroApplication shows that the upgrade was aborted and rolled back because the services never became healthy. I think this may be because of the group changes I made. I will fix it.

**Comment by alexperovich** [comment]
I have merged my fix.

**Comment by alexperovich** [comment]
The deployment worked.
