### ISSUE TITLE
[darc/maestro++] Add feature to update dotnet-tools.json

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/arcade#5315]
- [ ] This issue is blocking: no
- [ ] This issue is causing unreasonable pain: no

We're using a dotnet tool configured in [dotnet-tools.json](https://github.com/dotnet/runtime/blob/8ed18e6f2f65a336353be495f298f682cac564d0/.config/dotnet-tools.json#L17-L22) that is available in BAR as [Microsoft.DotNet.XHarness.CLI](https://maestro-prod.westus2.cloudapp.azure.com/2/https:%2F%2Fgithub.com%2Fdotnet%2Fxharness/latest/graph).

As far as I know darc can't auto-update the version number in dotnet-tools.json like it does for Versions.props so we need to manually bump.

It would be nice if darc supported that.

@riarenas @JohnTortugo @ViktorHofer

**Comment by riarenas** [comment]
@mmitche I think this would be useful. I think this could work like this:

* repos add their dependency to version.details.xml
* we look for matching assets in the dotnet-tools.json and update the version there.

**Comment by ChadNedzlek** [comment]
Presumably darc could see the name and version in the tools thing and add the entry itself.   Adding tools right now is pleasantly simple. Just "dotnet tool install MyTool", it would be nice to try to keep it simple, and all the information should be present after that to automate the update.

**Comment by riarenas** [comment]
Ooh yeah, I missed the part where simply adding a tool via `dotnet tool install` would add an entry to the tools manifest. All the info  will be there already.

Sould be simple to check the file against the assets that a build that we're updating from produced.

**Comment by riarenas** [comment]
Only concern of not requiring the addition of the tool as a dependency manually would be if repos want to pin a specific version of the tool instead of having Maestro update it. If the first update adds the entry, they can then pin the dependency in the file, but that first update would always happen and might be undesirable?

**Comment by ChadNedzlek** [comment]
I'd be fine if darc modified versions.details.xml, and then the person could pin it there.  But mucking about with that file should be optional for the rare occasion of pinning.

**Comment by riarenas** [comment]
Yeah, I'm mostly worried about this scenario (which granted, might not be a thing)

1. I add a tool to my repo, but I specifically require version 1.5
1. This feature gets turned on, and unexpectedly to me, Maestro creates a a PR the next day to update the tool to latest version 2.0 and add the entry to the version.details.xml
1. I can go and revert + pin the version in the version.details.xml file to opt out once I figured out this is what was causing problems, but I'm still grumpy at Maestro.

I think we can mitigate this by:

* Assuming that tools always want to be updated if they are in the tools manifest.
* Adding a new `local-tool` type of dependency, so that when people do `darc add-dependency` we will add the entry to `version.details.xml` and to `dotnet-tools.json` if not present already.
* Letting people know that we're turning this feature on, and if they use any local tools that they need a specific version of, to add the dependency via darc and pin it so that their version doesn't float if they don't want it.

**Comment by ChadNedzlek** [comment]
I think the first assumption is fine, especially if they are from a repository someone has a subscription from.  There aren't _many_ tools, but it's a good way to share command line/build things between repositories.  Theoretically it could even be used to get darc in the first place "dotnet tool install darc" and it would just... be in the repo without any special initialization code.

**Comment by riarenas** [comment]
@MattGal this would be a good issue for you to take a look at once the noise from the servicing exercise dies down.

**Comment by akoeplinger** [comment]
Awesome, thank you!

**Comment by akoeplinger** [comment]
@MattGal is this supposed to work for the automated darc PRs now, or just when using `update-dependencies` manually?

I don't see dotnet-tools.json getting updated with new xharness versions in dotnet/runtime.

**Comment by mmitche** [comment]
@akoeplinger Runtime has no dependency in version.details.xml on microsoft.dotnet.xharness.cli

**Comment by akoeplinger** [comment]
@mmitche it does:

https://github.com/dotnet/runtime/blob/c0669313dd36189c6d3bf5c7d5e866284f98263c/eng/Version.Details.xml#L197-L201

**Comment by MattGal** [comment]
Interesting, I will take a look later today.

**Comment by MattGal** [comment]
Still seems to work locally in the `update-dependencies` scenario, so I am working with @riarenas to figure out a local repro for the automated PR version.

**Comment by MattGal** [comment]
@akoeplinger should be fixed via https://github.com/dotnet/arcade-services/pull/1445, which with luck will roll out Wednesday.

**Comment by MattGal** [comment]
Rolled out to prod yesterday, @akoeplinger please let me know if this doesn't fix the issue.

**Comment by riarenas** [comment]
Reopening. We did not roll out Maestro yesterday.
