### ISSUE TITLE
Errors in signing validation due to missing vs property in tools.

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#5362]
- [X] This issue is blocking 
This is blocking dotnet/sdk's official build
- [ ] This issue is causing unreasonable pain

Official builds of dotnet/sdk seem to be failing in the signing validation step:

```
##[error](NETCORE_ENGINEERING_TELEMETRY=InitializeToolset) The property 'vs' cannot be found on this object. Verify that the property exists. 
```
Here’s an example build:  https://dev.azure.com/dnceng/internal/_build/results?buildId=619326&view=results

**Comment by riarenas** [comment]
@chcosta this might have been introduced here? https://github.com/dotnet/arcade/pull/5210/files#diff-853fb537e588caa8b548253bdcf21cd8R155

**Comment by chcosta** [comment]
This is failing because of https://github.com/dotnet/arcade/blob/master/eng/common/sdk-task.ps1#L62

```
  if( -not ($GlobalJson.tools.PSObject.Properties.Name -match "vs" )) {
```

The `match` comparison operator is matching "vs-opt" in [global.json](https://github.com/dotnet/sdk/blob/master/global.json#L9).

The fix (which I'm currently validating), is to use the `contains` comparison operator instead.

As a workaround, you can unblock your builds by adding this section to your global.json...

```
    "vs": {
      "version": "16.4"
    },
    "xcopy-msbuild": "16.4.0-alpha"
```
... like Roslyn does [here](https://github.com/dotnet/roslyn/blob/master/global.json#L4-L7).  The downside of this workaround is that it will slightly increase your dev build times as it copies MSBuild bits locally.  I should have a PR,  which fixes the issue, validated and ready for review in Arcade by EOD.

**Comment by chcosta** [comment]
FYI @dsplaisted

**Comment by chcosta** [comment]
Queue throughput is slowing getting this validated.  Won't have a PR available until tomorrow as wait times for me are 40+ minutes to get a build to run.

**Comment by chcosta** [comment]
Frustratingly, the "simple" fix is leading to another error where Powershell is complaining about the .NET Core SDK.  I'm investigating. :(

**Comment by chcosta** [comment]
I think I have a fix for this.  Validating now and I'll put up a PR soon...
