### ISSUE TITLE
Automated build drop creation

### ISSUE THREAD

**Issue by wli3** [dotnet/arcade#5396]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Currently we always need to ping someone to create an official build. This increases the turnaround time. We need:

1. Optional - Automatically verify the build drop is coherent and up-to-date (no behind build)
2. one API call to create such drop

At the same time, I still cannot find an easy way to create a drop locally.
https://github.com/dotnet/arcade/issues/5397

**Comment by JohnTortugo** [comment]
Item 1 in the list is probably related, or the same, as this issue: https://github.com/dotnet/arcade/issues/4841.

For number 2, you mean an REST API? 

/cc @mmitche

**Comment by wli3** [comment]
REST API maybe better, since we could make it a part of the automation

**Comment by mmitche** [comment]
There is automated drop creation today: https://dev.azure.com/dnceng/internal/_build?definitionId=792&_a=summary

That build is queued with the appropriate parameters (repo and sha or bar build id).

For local drop creation, `darc gather-drop` will do all that work for you. That is what the release pipeline is doing.

**Comment by jcagme** [comment]
Would like to point out that https://dev.azure.com/dnceng/internal/_build?definitionId=792&_a=summary purpose is to release. Yes, it starts by creating a drop, followed by notarizing it, but it has a lot of other tasks that are meant for shipping.

If the intent is only drop creation I'd recommend just doing `darc gather-drop`

**Comment by wli3** [comment]
Could we have a build only drop? We try to move some insertion task to vendors. And the step "ask someone in central engineering team for build drop" could delay a day due to timezone issue. At the same time, document how to use darc is also not trivial. And I only have a handful of success of gathering local drop correctly.

**Comment by jcagme** [comment]
The thing is, you should not depend on us to create a build drop given that `gather-drop` does it even for vendors so why not just asking them to run the command explaining what variables to pass in. Creating a build just for that is literally copying the command to a YAML script task.

**Comment by wli3** [comment]
Per my previous comment. Setup darc is not an easy task. You need to gather the PATs from different places. And `darc authenticate` is not straightforward to use. And the error message is not obvious. [For example, is this setup success or not?](https://dev.azure.com/dnceng/internal/_build/results?buildId=630817&view=logs&j=40e1e683-ea82-5be9-b25e-899b65e1c0cb&t=5fd29762-72ff-5c80-6da9-42a903d04309) That's much harder when people are rotating.

That's said. Is it easy to just take [this build ]( https://dev.azure.com/dnceng/internal/_build?definitionId=792&_a=summary) definition and only keep the gather drop step?

**Comment by wli3** [comment]
Also, we cannot always keep it locally. Once the insertion is finished, we still need to run notarization over it. And that need to be in a shared location

**Comment by mmitche** [comment]
@wli3 I'm not really understanding how setting up darc is not easy. 
All of these steps have explicit documentation, including the required scopes. https://github.com/dotnet/arcade/blob/master/Documentation/Darc.md#step-3-set-additional-pats-for-azure-devops-and-github-operations. `darc authenticate` explicitly says what to do in the pop-up dialog. I don't think it's unreasonable to expect developers to know how to get a PAT from services they use.

That said, your team should use the Release-DotNet pipeline to gather the drop
- It gathers the drop
- It handles the PATs you need
- It notarizes the packages
- It runs post build validation steps like symbol validation that are needed for successful insertions anyway.

As far as the results of that job, as developers we do need to understand both the inputs and outputs of the operations we're trying to perform here. If these operations could be done in a brain-dead simple way without understanding of the .NET Core product we would have made it that way a long while ago.

We need to know whether the build candidate actually has the fixes we want (and thus is one we should gather a drop for), and we need to understand whether the outputs are what we expect. A look at that log indicates that the dotnet/templating in the build is an older version from 3.1.2.  It fails to download because dotnet/templating was on a older version of arcade when that build was produced. Since there is no new build inserted, we're still getting the old failures. That said, we can mark that build as 'released' (since it is) and it won't bother us any longer and the gather step should be green.

**Comment by jcagme** [comment]
@wli3 you can use the pipeline we'll use for validation https://dev.azure.com/dnceng/internal/_build?definitionId=827&_a=summary. Just provide the required inputs. This pipeline will create the build drop and notarize it, also, run validation steps and SDL on top of it.

**Comment by riarenas** [comment]
Moving to release epic. (possibly to close?)

**Comment by wli3** [comment]
We currently workaround it by asking vendors to create a local drop -- it is very time consuming and teaching a group of rotating people to use darc is hard.

At the same time "Optional - Automatically verify the build drop is coherent and up-to-date (no behind build)" is still needed. It could save SDK team a lot of time and risk

**Comment by jcagme** [comment]
Closing since https://dev.azure.com/dnceng/internal/_build?definitionId=827&_a=summary can be used for this purpose. @wli3 feel free to re-open if you think we still need this
