### ISSUE TITLE
Longest build path should trim toolset dependencies

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5429]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

The longest build path calculation today is fine when there are no cycles, or when cycles do not result in a non-reducible flow graph. At those times, we can simply break the cycle on the back edge and then we'll get the calc right. But when the graph is non regular we can't break the cycle and odd things happen.

Instead, we should just eliminate toolset subscriptions and subscriptions that do not contribute to the version.details.xml file.

**Comment by tkapin** [comment]
@lukas-lansky - Please describe the approach you've chosen to implement here. Thanks.

**Comment by lpatalas** [comment]
I updated the PR with new changes: https://github.com/dotnet/arcade-services/pull/1336

Now the tooling edges are determined by getting all assets published by source repository and comparing them with dependencies defined in target repository. If any asset from source is used as product dependency then edge is treated as "Product" otherwise it's "ToolingOnly". Then we ignore the "ToolingOnly" edges when calculating build time.

@mmitche @adiaaida Could you take a look at the PR when you have a minute?

And one additional question @mmitche. When testing it I found the situation described below. Let's say we have 4 repos and dependencies flow "down" the graph from A to D. Both B and C use A as product dependency, but then B is product dependency of D while C is tooling dependency. Then for example if C takes longer to build than (B+C) the longest build path will be "A->C". Is this correct behavior and is this situation even possible in practice? 

```
            A
 product  /   \  product
         B     C
 product  \   /  tooling
            D
```

**Comment by lpatalas** [comment]
This was released yesterday (2020-09-02) to production.

The summary of the changes is:
- When calculating best/worst case time we ignore edges that are tooling-only
- To determine if edge between repos `A` and `B` is tooling-only we get all assets published by `A` that `B` depends on and check if these are tooling dependencies. If at least one of the assets is product dependency then edge is not tooling-only.
- Darc was modified to get flow graph data from API. Previously it was calculating it separately by using DarcLib directly.

**Comment by adiaaida** [comment]
The new graph is looking great! Nice work @lpatalas! I noticed that the worst case time (time with dependency flow) is no longer including the dependency flow time. Can you look into why that's happening?

**Comment by lpatalas** [comment]
@adiaaida Yes, I'm looking into it.

**Comment by lpatalas** [comment]
@adiaaida Surprisingly this turned out to be unrelated to my changes. We were just reading wrong property in frontend app when displaying graph. I made a PR with a fix here: https://github.com/dotnet/arcade-services/pull/1398

**Comment by lpatalas** [comment]
The fix mentioned above was rolled out Wed, 9th. I checked it on production maestro and it looks correct now. I'm closing this issue then.
