### ISSUE TITLE
BARViz should show cancelled builds as failed

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5579]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

BARViz today shows a cancelled build as a build that was not unsuccessful. You get the "this is not the most recent successful build" prompt, which is incorrect. It should show as failed. I think there may have been a debate as to whether this was the right behavior early on (e.g. if I say "oh I didn't mean to queue that" and cancel it), but in practice it always seems to mean that the build failed and should be rerun.

**Comment by ChadNedzlek** [comment]
I just looked at the code, the word "failed" only shows up in one place, and "cancelled" is in the same statement... so the code treats failed and cancelled builds identically.  I'm not sure what the current behavior or the expected behavior is, but I can't see any reason in the code cancelled and failed would not be treated identically.

Unless it's not "cancelled" but some other state.  I'd need more information about what particular build has this problem so I can see what the data looks like to determine what was happening... At this point they are lost to history, so I don't think this is actionable anymore.

@mmitche Any further details? Or is this reproing on a build that's currently available?

@ilyas1974 Without more details, I don't think there is any thing FR can do here.

**Comment by mmitche** [comment]
I haven't seen this repro recently, but I'll keep my eyes out. Maybe it already got fixed?

**Comment by mmitche** [comment]
Oh, yeah: https://github.com/dotnet/arcade-services/pull/1219
