### ISSUE TITLE
[maestro++] Create proof of concept of 'auto-merge info using the checks API' 

### ISSUE THREAD

**Issue by rokonec** [dotnet/arcade#5761]
Create simple console application to validate planned using of GH checks to implement Merge-status checks.
Proposed functionality:
- create check
- update check
  - to success
  - to failure
- update check output using markdown syntax in body
- update checks annotation for a particular file (optional)

Prepare presentation of result to the team ~ about 30 minutes.

**Comment by lwintjen** [comment]
The POC is done & ready to be presented to the team - I've tested the app, everything seems to work fine and the markdown is supported in the output body. The current implementation of the application is available on [this repo](https://github.com/microsoft-internship-lwintjen/proof-of-concept-checks-api)

I didn't implement the last and optional point. However, I did implement the check run actions so that if a check run failed and the result of the check is `action_required`, you can add an action to make.

**Comment by lwintjen** [comment]
The presentation has been done yesterday to the team.

The POC is a playground for the checks api in an organization's repo. It allows you to create or update a check run on an existing PR. The required setup is explained in the readme of the repo, you need to create & install a GH application to have the right credentials to launch the application.

This issue can now be closed, we're now moving to the implementation of the tests in this [issue](https://github.com/dotnet/arcade/issues/5764)
