### ISSUE TITLE
[maestro++] Test scenarios for new 'auto-merge info using the checks API' 

### ISSUE THREAD

**Issue by rokonec** [dotnet/arcade#5764]
- [x] find scenario and unit tests related to current Auto merge logic - `CheckMergePolicyAsync` method and probably others
- [x] verify if existing scenarios cover our future planned logic
- [x] write potentially missing scenarios either in failing state (red state in red, green, refactor TDD cycle) or as scaffold (only comments describing what needs to be done to validate it)
- [x] rewrite test into C#
- [x] new scenario test for `AllChecksSuccessfulMergePolicy` for following scenario:
  - 1st run with other pending check (such as build) is not successful
  - 2nd run with above check finished successfully is successful

related docs:
https://github.com/dotnet/arcade-services/blob/master/src/Maestro/tests/scenarios.md
https://github.com/dotnet/core-eng/blob/master/Documentation/Validation/README.md

**Comment by lwintjen** [comment]
I added a scenario test called _checks-api-playground_ which has almost the same logic as _githubflow-nonbatched-all-checks-successful_ but to know if the test passed or failed, the scenario tests existing check(s) (by querying the checks API) : 

2. at least one check should contain _maestro-policy_ in his external ID 
3. every check with an external ID containing  _maestro-policy_ should be in a completed state

If the two points above are OK then the test passes, otherwise it fails. 

Next step will be to modify maestro to add some checks upon creation (rather than a comment) and update the check(s) when necessary. Once that's done, the new scenario test should not fail anymore.

**Comment by lwintjen** [comment]
Here's an update of the work done so far for this issue :
- [x]  find scenario and unit tests related to current Auto merge logic - CheckMergePolicyAsync method and probably others
- [x]  verify if existing scenarios cover our future planned logic
- [x]  write potentially missing scenarios either in failing state (red state in red, green, refactor TDD cycle) or as scaffold (only comments describing what needs to be done to validate it)
- [ ]  rewrite test in to C# once C# GutHub flow scenario tests PR is merged ([PR](https://github.com/dotnet/arcade-services/pull/1313) currently under review)
- [ ]  new scenario test for AllChecksSuccessfulMergePolicy for following scenario:
    - 1st run with other pending check (such as build) is not successful (yet to be done)
    -  2nd run with above check finished successfully is successful (done)
