### ISSUE TITLE
[Signing][LC] Publish all the things signed (5/5)

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#5850]
We'll need a place to put the signed files

- [ ] Copy the signed output from the light command packaging to the location of the file that was copied over from the drop (overwriting the msi/exe/wixpdb/et cetera from the drop that does not contain signed files)
- [ ] Copy the `shipping` and `nonshipping` folders from the agent with the signed files back to the drop (share directory). 

There is a stubbed out operation/options files in Signing.Extensions called PublishSignedFiles for this functionality.

**Comment by jcagme** [comment]
Something to have in mind is disk space. I've just hit a "There is not enough space on disk" while testing the pipeline. For validation runs, I delete the drops once pushed to build's artifacts, we cannot do this here since the drop is used in CTI and will maybe used for release purposes. Something to have in mind.

**Comment by jcagme** [comment]
[This](https://github.com/dotnet/arcade/issues/5681#issuecomment-671639991) should be considered when uploading things to the feed since we need to replace unsigned NuGet packages with signed versions.

fyi: @missymessa

**Comment by jcagme** [comment]
Also this will be needed https://github.com/dotnet/arcade/issues/6028

**Comment by jcagme** [comment]
Publishing side of things maps what's described in https://github.com/dotnet/arcade/issues/5991. I'll work on #6028 next
