### ISSUE TITLE
Allow stage0 install of SDK from internal sources

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#5934]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

Currently we can install runtimes from dotnetclimsrc (by passing an alternate location for the runtime to the build, along with credentials). The install code will first check the "normal" location and then it will attempt to use dotnetclimsrc if the public runtime was not found.

This does not work for the "stage0" SDK (e.g. https://github.com/dotnet/sdk/blob/master/global.json#L3). This always installs from a public location.

If possible, we should support private stage0. I do not know what the feasibility of this is.

**Comment by MattGal** [comment]
https://github.com/dotnet/arcade/pull/5987 works and tested on Windows & ubuntu; no expectation it should have any variance for MacOS.  Promoted PR to non-draft.

**Comment by MattGal** [comment]
https://dnceng.visualstudio.com/internal/_build/results?buildId=778677  <-- SDK build where the big three flavors all restore the SDK (as evidence by the SDK bug it has : theoretically worked around now in arcade master).

I'm trying a version now here; https://dnceng.visualstudio.com/internal/_build/results?buildId=778731 that should fail because my version is impossible

**Comment by MattGal** [comment]
This is done and merged as well as the follow-up in arcade-validation it caused, closing.
