### ISSUE TITLE
[Maestro++/Darc] Failure to open dependency update PRs due to git failures in the SF cluster

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#5997]
- [ ] This issue is blocking 

- [ ] This issue is causing unreasonable pain

We are seeing the following error when trying to open dependency update PRs in some repos:

```
Something went wrong when pushing the files to <repo> in branch <branch>
```

Digging deeper in the service logs, it looks like it's a git failure doing git init, although still not quite sure what is the actual error:

```
Something failed when executing command git init clonedRepo in <path> 
```

re-triggering an affected subscription results in the same error.

**Comment by riarenas** [comment]
Investigating

**Comment by riarenas** [comment]
It looked like all of these errors from yesterday happened in a single node of the service. I restarted it and re-triggered the subscriptions, which opened PRs. Now that things should be unblocked, I'll try and find how the git installation in this node got to that state.

**Comment by riarenas** [comment]
after the node reset I haven't seen any more instances of this. the git installation in that node seems to have been corrupted somehow. I'm unchecking the blocking box.

**Comment by riarenas** [comment]
Found some logs that revealed that the git installation was missing from the node. I'll add some resiliency to these code paths to make sure we don't end up with broken git installs.

**Comment by riarenas** [comment]
This was the underlying cause for today's rollback during the maestro application deployment.

**Comment by adiaaida** [comment]
The change in https://github.com/dotnet/arcade-services/pull/1512 adds additional hardening to make sure that we download git if it doesn't exist where it's supposed to when we get the path to the executable, however, it doesn't cover the case if the executable is removed/corrupted between download and use in SubscriptionActorService. If we want to cover that case (if this comes back), we'll want to move LocalGit to DarcLib, so that we can download if we find that it's missing when we try to run it.

**Comment by MattGal** [comment]
@adiaaida this rolled out last week and we haven't seen a repro, closing; feel free to reactivate if I am in error.
