### ISSUE TITLE
Darc subscription update is updating more than requested

### ISSUE THREAD

**Issue by dseefeld** [dotnet/arcade#6027]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

I added a subscription from Arcade (.NET 3 Eng) => source-build (release/3.1):
https://github.com/dotnet/arcade (.NET 3 Eng) ==> 'https://github.com/dotnet/source-build' ('release/3.1')
  - Id: 7dd6a25b-619a-4607-9f6a-08d8483d489b
  - Update Frequency: EveryDay
  - Enabled: True
  - Batchable: False
  - Merge Policies: []

When the subscription was triggered, there were updates to other dependencies in eng/Version.Details.xml rather than just to the Arcade dependency as expected.  The changes were changing the URI for some dependencies from external to internal references.

The generated PR is: https://github.com/dotnet/source-build/pull/1720

**Comment by dagood** [comment]
Example unrelated and breaking diff that happened during a dotnet/arcade -> dotnet/source-build update:

```diff
     <Dependency Name="Microsoft.NETCore.App.Runtime.linux-x64" Version="3.1.7" CoherentParentDependency="Microsoft.Dotnet.Sdk.Internal">
-      <Uri>https://github.com/dotnet/core-setup</Uri>
+      <Uri>https://dev.azure.com/dnceng/internal/_git/dotnet-core-setup</Uri>
       <Sha>fcfdef8d6ba770e4d7ba9efefe2591d8c33a1fc6</Sha>
       <RepoName>core-setup</RepoName>
       <RepoName>core-setup-portable</RepoName>
     </Dependency>
```

I think this can be worked around by adding logic to `darc clone` that automatically translates the internal URL to the GitHub URL when we don't pass any auth to `darc clone`.

And actually... we need that `darc` solution for arcade-powered source-build. Since we'll build the tarball out of dotnet/installer, and tagging for that repo should happen automatically on release day, we won't have a chance to manually replace the URL like we do before tagging dotnet/source-build. So, I think we should actually open a new issue to go with a `darc clone`, and let the dependency update do whatever it wants here.

/cc @crummel

**Comment by riarenas** [comment]
I took a quick stab because It'd haunt me.

This is happening during the coherency updates, and it looks like it actually is the correct thing to do. The build that generated the versions of the assets that got their URL updated was a build from an internal release branch, and that's what's causing the URL change.

````
darc get-asset --name "Microsoft.Private.CoreFx.NETCoreApp" --version "4.7.0-servicing.20370.1" --max-age 60
Looking up assets with name 'Microsoft.Private.CoreFx.NETCoreApp' and version '4.7.0-servicing.20370.1' in the last 60 days
Microsoft.Private.CoreFx.NETCoreApp @ 4.7.0-servicing.20370.1
Repository:    https://dev.azure.com/dnceng/internal/_git/dotnet-corefx
Branch:        refs/heads/internal/release/3.1
Commit:        36b8b8e26a8e2e06e000f59e19910d117bf0025b
Build Number:  20200720.1
Date Produced: 7/20/2020 3:44 PM
Build Link:    https://dev.azure.com/dnceng/internal/_build/results?buildId=738347
BAR Build Id:  57948
Released:      True
Channels:
- .NET Core 3.1 Internal Servicing
Locations:
- https://dev.azure.com/dnceng/internal/_apis/build/builds/738347/artifacts (Container)
- https://pkgs.dev.azure.com/dnceng/_packaging/dotnet3.1-internal-transport/nuget/v3/index.json (NugetFeed)

```

**Comment by dagood** [comment]
The URL isn't unexpected, it's that auto-update is making a change to the URL when that dependency isn't being updated. (And the subscription doesn't include that dependency.) But this is a matter of a (presumably undocumented?) bit of auto-update behavior that doesn't matter anyway since we need to have `darc clone` handle this for arcade-powered source-build regardless.

Closing in favor of https://github.com/dotnet/arcade/issues/6058.

**Comment by riarenas** [comment]
I believe this is because coherency updates always happen regardless of the channel that is being updated. I wonder if this is something that should actually be changed?

@mmitche ?

**Comment by dagood** [comment]
The expectation mismatch seems to be that the coherency update is updating the URL to what it thinks is correct even when the `Version` attribute doesn't change. I'd only expect a URL update if the `Version` update changes. This would avoid wiping out manual changes to the dependencies.

**Comment by mmitche** [comment]
Yeah. Coherency is a constraint and so it is always updated. Basically it's considered a requirement (same as pinning, etc.)

**Comment by riarenas** [comment]
It's something like this

coherency update says: for this to be coherent, we need to update `Microsoft.Private.CoreFx.NETCoreApp` to `4.7.0-servicing.20370.1` which was produced by core-fx internal, and that asset was produced by the internal repo, It just so happens that the file already has that version, so there's no actual diff in the version number, but the URL does get changed.

**Comment by dagood** [comment]
Yeah, that's inconvenient for source-build until we get that `darc clone` feature (can't take arcade auto-updates until then) but fine IMO as a behavior.
