### ISSUE TITLE
[darc/maestro++] Promotion pipeline names stable isolated feeds oddly

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6041]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

When used to promote a stable build, the promotion pipeline names the isolated feeds `darc-<pub/int>-dotnet-arcade...` regardless of what repo's build is being promoted. These should be "darc-<pub/int>-<org>-<repo>". Functionally this is fine, but it's confusing.

Based on this behavior, it would also be good to check the properties that are used to construct the feed name and ensure they are not used in unexpected ways elsewhere in the publishing pipeline.

**Comment by riarenas** [comment]
This is definitely because we use the azdo build variables to pick the repository name during the publishing stages.

https://github.com/dotnet/arcade/blob/a885ba04170d758ba964553d002135122e72d523/eng/common/templates/post-build/channels/generic-public-channel.yml#L149-L150

I think we need to plumb these through as parameters all the way from post-build.yml, and use the information from the BAR build we're promoting to populate them.

We already have the build info:
https://github.com/dotnet/arcade/blob/a885ba04170d758ba964553d002135122e72d523/eng/promote-build.yml#L85

**Comment by riarenas** [comment]
This is fixed in publishing v3 thanks to https://github.com/dotnet/arcade/issues/6100. I don't think it's that important to fix it for v2 publishing, as the build promotion pipeline isn't used as much.
