### ISSUE TITLE
ESRP Notarization is failing for two packages

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#6115]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

ESRP notarization is failing for the following two mac packages:

dotnet-sdk-5.0.100-rc.1.20452.6-osx-x64.pkg
dotnet-runtime-5.0.0-rc.1.20451.14-osx-x64.pkg

Links to failure reports can be found in this job: https://dev.azure.com/dnceng/internal/_build/results?buildId=799551&view=logs&j=f15ff3dd-0bdf-5389-2bfc-e693179a3ead&t=029505b8-d43a-5fa8-b67b-c8e390111169

**Comment by adiaaida** [comment]
We're seeing the following 3 errors:

* The binary is not signed with a valid Developer ID certificate.
* The signature does not include a secure timestamp.
* The executable does not have the hardened runtime enabled.

**Comment by ilyas1974** [comment]
@jcagme any suggestions on how to proceed with this.

**Comment by adiaaida** [comment]
I'm actually wondering if there is something wrong with these specific builds, for example, they didn't get signed properly originally. I'm running an older set of ids right now to see if this looks like something on the ESRP side, or if something isn't being done properly on our side.

**Comment by jcagme** [comment]
Have contacted Maritere from the ESRP team and added @adiaaida and @ilyas1974 to the thread since I can’t look at the build at the moment

**Comment by markwilkie** [comment]
@jcagme is OOF today (Thursday).

**Comment by adiaaida** [comment]
Confirming, but Maritere's response suggests that this is an issue on our side:

"Note that you need to send signed packages for notarization. In a future we are considering having both steps (signing and notarizing) in a single step."

**Comment by adiaaida** [comment]
Her latest email confirms:

"Yes, is seems that the package is not correctly signed. This must be signed with a Developer ID certificate."

**Comment by adiaaida** [comment]
@mmitche FYI

**Comment by mmitche** [comment]
@marcpopMSFT @joeloff @sfoslund This is from an attempt to notarize the latest build.

**Comment by jcagme** [comment]
To provide some context, we are signing packages within the PKG and the PKG before sending them for notarization, all these are done in ESRP. Maritere suggests that there are files that were not signed so I’m wondering if there are new files in the packages that somehow the process didn’t identify to be signable. Also, the runtime repo added a process to sign and entitle some files on their build and we added a condition so we don’t sign files already signed. Maybe there that has something to do

**Comment by joeloff** [comment]
From the error it sounds like we're sending the package for notarization, but don't sign the PKG itself. Is this a new package that's maybe not being included in the submission to ESRP or being signed with the wrong keycode in ESRP?

**Comment by adiaaida** [comment]
The only thing different about these particular packages is their version. Nothing else that I can see suggests them as being "new"

**Comment by jcagme** [comment]
Ok. I’ll take a look first thing tomorrow

**Comment by joeloff** [comment]
You might want to ping PRSS as well. ESRP does some validation after signing, but I'm unsure what it does for .pkg files. It's possible there could be a hardware issue as well (HSM went down, etc.). I've seen issues over the years where signing "succeeds", but because of other failures, you get unsigned, or incomplete signed content back. If you have the submission/correlation IDs, PRSS can track the job to confirm whether anything went wrong.

**Comment by jcagme** [comment]
Found the issue. We added a check to not include files which are already signed to the signing + hardening process. Looks like createdump, dotnet and apphost were already signed. The following validates this to be the case:

```
codesign --verbose --verify ./com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App.5.0.0-rc.1.20451.14.component.osx.x64.pkg/Payload/shared/Microsoft.NETCore.App/5.0.0-rc.1.20451.14/createdump
./com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App.5.0.0-rc.1.20451.14.component.osx.x64.pkg/Payload/shared/Microsoft.NETCore.App/5.0.0-rc.1.20451.14/createdump: valid on disk
./com.microsoft.dotnet.sharedframework.Microsoft.NETCore.App.5.0.0-rc.1.20451.14.component.osx.x64.pkg/Payload/shared/Microsoft.NETCore.App/5.0.0-rc.1.20451.14/createdump: satisfies its Designated Requirement
```

@mikem8361 merged https://github.com/dotnet/runtime/pull/40485 to sign these during builds but looks like even though he uses the same ESRP task that we use in the release notarization is not liking it. Maybe timestamps need to be the same? @mikem8361 @hoyosjs what happens if we notarize these again? If we do that we'll override the existing signature but with the same certs, only thing changing would be the timestamp, and by the time we run the pipeline, all consuming product should already be have been produced.

Thoughts?

In the meanwhile I'll have a test run that resigns things so we can compare things in case needed

**Comment by hoyosjs** [comment]
If that is a release time sign+entitle+notarize, that's perfectly fine. The runtime signing is so internal customers can get dumps from their tests. As long as it goes out notarized with all the proper entitlements and signatures in the nupkgs and pkg's, all should work transparently.

**Comment by mikem8361** [comment]
FYI, these binaries are not notarized just signed and entitled.

**Comment by jcagme** [comment]
> FYI, these binaries are not notarized just signed and entitled.
Yes! The process claims that these were not signed and entitled which is weird.

I'll babysit the test run and let you guys know once done in case you want to validate things.

**Comment by jcagme** [comment]
https://dev.azure.com/dnceng/internal/_build/results?buildId=802585&view=logs&j=f15ff3dd-0bdf-5389-2bfc-e693179a3ead&t=f15ff3dd-0bdf-5389-2bfc-e693179a3ead indicates a successful notarization. Notarized packages are in the build's artifacts in case you want to check them

**Comment by markwilkie** [comment]
Thanks @jcagme!  What's the right long term solution here?

**Comment by jcagme** [comment]
This should be enough. The fact that these are been signed during build time is so consuming repos can make use of them otherwise. The fact that we sign them at the end doesn’t change much really. I’ll just follow up with ESRP to understand why this is currently failing just as an understanding exercise. 

PR has been merged.
