### ISSUE TITLE
GetFailedWorkItems task should ensure all expected metadata for CreateFailedTestsForFailedWorkItems  exists and is serializable

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#6163]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

See https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Helix/Sdk/GetFailedWorkItems.cs  and this build: https://dev.azure.com/dnceng/public/_build/results?buildId=811769&view=logs&j=3f6d4e0f-1b71-56b5-361e-d95b6e6da15a&t=d5bf30bc-9e5a-596c-d1c8-39e2dfa42d49&l=1008

... Stuff was going to fail either way but this error could be avoided by ensuring the items created by GetFailedWorkItems are all valid (and perhaps logging their contents if not)

**Comment by adiaaida** [comment]
Just a note: GetFaildWorkItems.cs is now https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Helix/Sdk/GetHelixWorkItems.cs

@MattGal that build is gone now. Do you know if this is still an issue and can you remember how it manifested?

**Comment by MattGal** [comment]
Yes, I think that's the error.  I'm confused, did I not post the exact same path you did?

**Comment by adiaaida** [comment]
In the last 2 months,  https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Helix/Sdk/GetFailedWorkItems.cs was renamed to https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Helix/Sdk/GetHelixWorkItems.cs.

I got the error message from Kusto

**Comment by MattGal** [comment]
Totally missed that :) yes.  The idea here is simple to make sure that all the item metadata that the secondary task reads is created in some viable form (i.e. empty, if actually empty, but valid) by the first task.

**Comment by adiaaida** [comment]
Yeah, from my understanding and reading of various help threads, this might be a case of not doing enough escaping of escape characters. I think the reason is similar to what's happening with the consoleOutputUri in https://github.com/dotnet/arcade/issues/6490: We encode them, but when we read the metadata back in, it are read back in as the unencoded strings.

Similarly, when we read back in the UploadedFiles, we are attempting to deserialize unencoded paths, so all of the \ are read as escape characters. I think what we need to do is make all \'s get written as \\'s. But I'm not 100 sure how to test this theory out.

**Comment by MattGal** [comment]
Easiest way to test it out is to rig up something that calls the two build tasks locally and have a test .proj that invokes one and feeds it the other's output.  Then, you can try out all sorts of special characters and make sure they emerge as something we can use.  Ping me for more details.
