### ISSUE TITLE
InstallDotNetSdk needs to have a way to prevent reinstall / failure when productVersion.txt remaps the folder name

### ISSUE THREAD

**Issue by MattGal** [dotnet/arcade#6278]
- [x] This issue is blocking 

Makes users have to come up with workarounds for productVersion.txt installed SDKs/Runtimes

- [ ] This issue is causing unreasonable pain

See this code:
https://github.com/dotnet/arcade/blob/master/eng/common/tools.ps1#L153

```
    if (-not (Test-Path(Join-Path $dotnetRoot "sdk\$dotnetSdkVersion"))) {
      if ($install) {
        InstallDotNetSdk $dotnetRoot $dotnetSdkVersion
```

With the recent changes to the install scripts to support installing "stable-version" type builds, we need to have a way to check this mapping (from non-stable -> stable version) and prevent re-install / failure if the correct version is actually present.

@dougbu  FYI

**Comment by dougbu** [comment]
- This problem does not occur with preview SDKs or released SDKs e.g. dotnet-sdk-3.1.100-linux-x64.tar.gz is fine because the `3.1.100` version appears as the (expected) folder name under `$dotnetRoot\sdk\`
- I saved an `arcade-6278` branch in https://dev.azure.com/dnceng/internal/_git/dotnet-aspnetcore if you need an example branch where the current `tools.*` files aren't working for us

**Comment by garath** [comment]
Triage: @mattgal to investigate

**Comment by MattGal** [comment]
@dougbu : Let's chat when you can tomorrow please.  I tried to get a repro using the supplied branch running eng\common\cibuild.cmd out of this but saw two behaviors.  (Also strange that this build doesn't seem to care about xcopy-msbuild...)

### When running with msbuild 16.8 on the path:

  The lines you point out do indeed cause some extra checking, about 10-15s of wasted time on subsequent builds when a non-matching product version.txt is used, but nothing blocking

  Build fails with:
  ```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(128,5): error : The local source 'D:\Git\aspnetcore\artifacts\packages
\Debug\NonShipping\' doesn't exist. [D:\Git\aspnetcore\AspNetCore.sln]
```


### When running with msbuild < 16.8 on the path:

```
D:\Git\aspnetcore\eng\tools\BaselineGenerator\BaselineGenerator.csproj : error : Version 5.0.100 of the .NET Core SDK requires at least version 16.8.0 of MSBuild. The current available version of MSBuild is 16.7.0.37604. Change the .NET Core SDK specified in global.json to an o
lder version that requires the MSBuild version currently available
```

I'm definitely interested in making tools.ps1 behave better if I can but I'd like some more help seeing what you're seeing.

**Comment by dougbu** [comment]
I disagree w/ "nothing blocking" @MattGal because the "Build fails with" error breaks us w/ the productVersions.txt redirects. In any case, I was typing up the following as you added your comment&hellip;

----

dotnet/aspnetcore mainly hit problems  errors from the `else` part of `if ($install)` because not all of our build steps pass `-restore` and that controls `$install`. I hacked the eng/common/ files to remove those `else` blocks from `tools.*` and the errors went away but that might not be safe in general. This error is exactly what you mentioned above @MattGal.

Specifically, these types or problems arise when using an SDK like https://dotnetcli.azureedge.net/dotnet/Sdk/5.0.100-rtm.20471.12/dotnet-sdk-5.0.100-win-x64.zip because that has "effective version" 5.0.100` i.e. the full version in the URL isn't present under .dotnet/sdk/.

----

dotnet/aspnetcore also saw problems w/ this SDK version in our [eng/scripts/ci-source-build.sh](https://github.com/dotnet/aspnetcore/blob/release/5.0/eng/scripts/ci-source-build.sh) script. That runs eng/common/build.sh twice and both have `-restore` on the command line, meaning `$install` is `true` both times. The second invocation tries to install the SDK again and fails because `dotnet` processes from the first are still hanging around. My workaround there involved adding `-ci` to the second invocation (to disable node reuse there) and killing `dotnet` processes between them. This is a slightly-separate problem because eng/common/dotnet-install-scripts/dotnet-install.sh might not be using the effective version when confirming an SDK is already installed. That is, we check twice (once with the effective version and again with the specific version) only _after_ expanding the archives.

I think the ask here is to make https://github.com/dotnet/arcade/blob/master/eng/common/dotnet-install-scripts/dotnet-install.sh#L856-L859 more like https://github.com/dotnet/arcade/blob/master/eng/common/dotnet-install-scripts/dotnet-install.sh#L900-L915 or, perhaps, check for an SDK installation using both `$specific_version` and `$specific_product_version` up front.

----

Separately, `msbuild` doesn't get any information about the full `5.0.100-rtm.20471.12` version which causes problems passing that version to Helix jobs that need to repeat the same installation done on build agents. Wish we had something like `$(NETCoreSdkFullVersion)` available by default because `$(NETCoreSdkVersion)` contains only `5.0.100`.

----

The requirement to use VS 16.8 is why I pushed back on changes to use the latest SDK before the main VS2019 buildpool agents were updated. We now use the .pre agents where we hit problems. dotnet/aspnetcore doesn't build any managed projects w/ desktop `msbuild` and, so, wasn't affected. This is mostly a solved problem for ASP.NET repos.

**Comment by dougbu** [comment]
@dsplaisted any thoughts on adding something more to the BundledVersions properties❔ I'm working on hacking around this but am not excited about writing an `msbuild` task just to parse our global.json file.
> Wish we had something like `$(NETCoreSdkFullVersion)` available by default because `$(NETCoreSdkVersion)` contains only `5.0.100`.

**Comment by MattGal** [comment]
@dougbu I'm not trying to say there's nothing blocking, only that the errors I did get didn't seem to be even related.  Can you provide further repro steps for your branch?

**Comment by dougbu** [comment]
Re "didn't seem to be even related", our most common issue with these almost-stable SDKs is exactly something you mentioned.
>   Build fails with:
>  ```
> C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\Common7\IDE\CommonExtensions\Microsoft\NuGet\NuGet.targets(128,5): error : The local source 'D:\Git\aspnetcore\artifacts\packages\Debug\NonShipping\' doesn't exist. [D:\Git\aspnetcore\AspNetCore.sln]
> ```

To get that
1. Update global.json to use `tools.dotnet == 5.0.100-rtm.20471.12`
2. Run any `build.*` script with `-restore`
3. Run any `build.*` script **without** `-restore`

----

To mimic the ci-source-build.sh problem we hit, run the same `build.* -restore` command twice using the correct switches to ensure it uses `dotnet msbuild`. Don't wait long between runs because I think `dotnet` processes eventually die off themselves and node reuse does weird things with `-ci`.

**Comment by MattGal** [comment]
Closing this issue: 
- After working with @mmitche  @dougbu  is unblocked and does not need further change at this moment
- This led to having a good chat with @richlander who suggested I create https://github.com/dotnet/install-scripts/issues/85 before merging the PR that brings this change along to the real scripts (also I would never merge such a PR on a Friday).
