### ISSUE TITLE
[Release/3.x] Arcade-validation official build break due to manifest changes

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#6368]
- [X] This issue is blocking 
This is blocking flow of arcade for the repos subscribed to the .net 3 eng channel

- [ ] This issue is causing unreasonable pain

Arcade-validation's official build started failing after taking the changes from https://github.com/dotnet/arcade/pull/6340

Failed build: https://dev.azure.com/dnceng/internal/_build/results?buildId=845495&view=results

```
error MSB4064: The "IsReleaseOnlyPackageVersion" parameter is not supported by the "PushToAzureDevOpsArtifacts" task. Verify the parameter exists on the task, and it is a settable public instance property.
```

I think we might be missing updating the task versions somewhere in there. 

FYI @epananth

**Comment by epananth** [comment]
yeah you are right :) Have to update the MicrosoftDotNetVersionToolsVersion version. I have test build running for this https://dev.azure.com/dnceng/internal/_build/results?buildId=845588&view=results

**Comment by epananth** [comment]
Have a PR out for this -> https://github.com/dotnet/arcade-services/pull/1434

**Comment by riarenas** [comment]
That PR mentions that the change that caused this break should be reverted? So it doesn't fix this?

**Comment by epananth** [comment]
I initially thought that updating the 3.x branch will create the VersionTools that should be used in the arcade-services will fix this. But I used the arcade update 5.0.0-beta.20506.7 to .NET Eng - Latest that worked, so I feel the change I made to arcade 3.x branch is not that useful. So I think we should revert this change.

The confusion was because arcade-services takes partial arcade update and partial arcade3.x update. 
Please correct me if I'm wrong here.

**Comment by epananth** [comment]
Also I noticed that https://github.com/dotnet/arcade/blob/7fd6d67e17610df7d4d3eb179c7ad75be7611bfd/global.json#L6 this cannot be changed for release/3.x so my change cannot work for 3.x

**Comment by riarenas** [comment]
Let's revert the change please.

**Comment by epananth** [comment]
https://github.com/dotnet/arcade/pull/6380 reverted the change. Closing this issue
