### ISSUE TITLE
When helix logs URL's, they should be encoded

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#6490]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Example logs:
```
  Stopping Azure Pipelines Test Run Ubuntu.1804.Amd64.Open
/home/vsts_azpcontainer/.nuget/packages/microsoft.dotnet.helix.sdk/6.0.0-beta.20526.10/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(76,5): error : Work item SDK Console Template netcoreapp5.0 Build(No Change) in job 1e2c5436-6e9b-4fa8-9f46-2904ee5759f0 has failed. [/__w/1/s/eng/performance/sdk_scenarios.proj]
/home/vsts_azpcontainer/.nuget/packages/microsoft.dotnet.helix.sdk/6.0.0-beta.20526.10/tools/Microsoft.DotNet.Helix.Sdk.MultiQueue.targets(76,5): error : Failure log: https://helix.dot.net/api/2019-06-17/jobs/1e2c5436-6e9b-4fa8-9f46-2904ee5759f0/workitems/SDK Console Template netcoreapp5.0 Build(No Change)/console [/__w/1/s/eng/performance/sdk_scenarios.proj]
```

In these logs, the URL contains spaces, but they are written out un-encoded, producing invalid (and therefore unnavigable) URL's.

**Comment by adiaaida** [comment]
Strangely, we actually save the consoleUri encoded. It's very strange to me that it's coming back unencoded:

https://github.com/dotnet/arcade/blob/72b28b7e023d4c3fffa0a0b9748a7d4e8cc799be/src/Microsoft.DotNet.Helix/Sdk/GetHelixWorkItems.cs#L57

but when we get it from the metadata here, it isn't encoded anymore:

https://github.com/dotnet/arcade/blob/72b28b7e023d4c3fffa0a0b9748a7d4e8cc799be/src/Microsoft.DotNet.Helix/Sdk/CheckHelixJobStatus.cs#L39

It seems like the solution here is to either:
1) Create a helper function that can construct the link to the console log that always escapes workItemName
2) Replace workItemName with Uri.EscapeDataString(workItemName) in CheckHelixJobStatus.cs
3) Do some really crazy uri splitting and re-encoding of each part of the uri (this seems error prone).

All of these options carry some risk. 1 has risk because we can't just reference HelixApi.Options in the helper class (it doesn't like that it isn't static), so we have to pass in the HelixApi object. 2 has risk because string manipulation/replacement is always risky. 3 is risky because we don't necessarily know if the consoleUri will always be missing query parameters and the like, and there are a lot of different possible uris we could come across.

I think 1 is probably the least risky, and means if we ever update the path to the console uri in code, it will be updated everywhere we reference it.

**Comment by ChadNedzlek** [comment]
An extension method on IHelixApi isn't bad, since that gets you the Options that you need. :-)  api.GetConsoleUri(string workitemName)

**Comment by adiaaida** [comment]
Even smarter!

**Comment by adiaaida** [comment]
So I thought of another option while looking into #6163 and what we do there (call `Replace("%", "%25")` on the serialized json object), and I wonder if we could just a) EscapeDataString twice when building the console uri, or do the same `Replace("%", "%25")` on consoleUri before handing it off to the metadata. It's pretty clear that this is MsBuild doing weird escape logic (ie, unescaping things).

**Comment by alexperovich** [comment]
At this point I would rather we just base64 encode the thing, then decode it when we go to use it. Any amount of crazy escaping we do will never be good enough.

**Comment by ChadNedzlek** [comment]
Is MsBuild really messing with the string? That's... super weird.  Since most of MSBuild isn't handling URL's, it's so odd for them to URL escape things.

**Comment by adiaaida** [comment]
msbuild is interpreting %20 as a space. So it goes from this escaped string to an unescaped string. Just like it interprets %25 as %.

**Comment by ChadNedzlek** [comment]
I found it!

You need to cast the thing to a "ITaskItem2", and then call "SetMetadataLiteralValue". Otherwise MSBuild escaping will bite us.

**Comment by ChadNedzlek** [comment]
Apparently "SetMetadata" is just evil and we shouldn't ever use it. Yay msbuild.

**Comment by ChadNedzlek** [comment]
Apparently also the constructor that task IDictionary does the same thing, in that it doesn't deal with escaping well.

**Comment by adiaaida** [comment]
Thanks Chad! I will work on making this change.
