### ISSUE TITLE
Publishing V3 doesn't preserve Category metadata in merged manifest

### ISSUE THREAD

**Issue by hoyosjs** [dotnet/arcade#6517]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

In diagnostics we recently moved to V3 Publishing. We set a special target in publishing.props to generate add a nupkg to `ItemsToPushToBlobFeed` with the `ManifestArtifactData` having `Category=OTHER`. The resulting manifest having a Category attribute in the manifest, and the package would get published to blob storage. However, V3 publishing doesn't preserve such metadata when generating `MergedManifest.xml` (The `Blob` class in arcade-services doesn't have a field for it) and the item ends up in the feed assigned to the default channel. This causes it to not be available through an aka.ms link nor in blob storage, and we use this in the `dotnet-docker` repo to generate the images. Is there any way to get this back in v3, or is this expected?

cc: @jander-msft

**Comment by markwilkie** [comment]
cc/ @epananth @riarenas

**Comment by riarenas** [comment]
Is there a reason why you need a nupkg in blob storage as opposed to a feed where it ends up by default?

**Comment by riarenas** [comment]
Or alternatively, if restoring is not possible, can the package be downloaded from the feed? the link should be just as stable as an aka.ms link:

`https://pkgs.dev.azure.com/dnceng/public/_apis/packaging/feeds/<feed>/nuget/packages/<package>/versions/<version>/content`

For example:

https://pkgs.dev.azure.com/dnceng/public/_apis/packaging/feeds/dotnet-eng/nuget/packages/microsoft.dotnet.arcade.sdk/versions/6.0.0-beta.20555.1/content

**Comment by jander-msft** [comment]
The `dotnet-docker` repo needs to understand what is the latest version of a specific nupkg that starts with 5.0.X for its version. We had the prior publishing system produce a latest aka.ms link to point at the latest in that line of versioning (aka.ms/dotnet/net5/rc2/diagnostics/monitor5.0/dotnet-monitor.nupkg). Generating this link for files that were pushed to NuGet feeds was not supported, so we have the package categorized (OTHER) so that the aka.ms link would be generated. We do the same thing for the checksum file that corresponds with this nupkg file (although it used the CHECKSUM category).

Your suggestion of just pulling from the NuGet feed is where we started in the `dotnet-docker` repo but quickly became tedious to determine what was the latest 5.0.X version and from where to get the checksum file. The latest aka.ms link for the nupkg solved this because `dotnet-docker` could get that file, unpack the nuspec file, and read out the version easily.

**Comment by riarenas** [comment]
Can this be solved via the dependency flow mechanism? If `dotnet-docker` subscribed to the repository that produces the dotnet-monitor package based on a version channel that it gets published to, it would already know what the version is without having to crack open a nupgk, as the version would be in the Version.Details.xml file.

**Comment by jander-msft** [comment]
While I can't definitely say the owners of that repo would not be open to that, prior conversations along the same line were not deemed desirable or even acceptable. My recollection is that the `dotnet-docker` repo does not have any dependencies on any other repo and is purely driven using latest aka.ms links for nightly builds and known release versions for released images.

**Comment by riarenas** [comment]
Can you go into detail into why it's not desirable or acceptable? It seems like that repo does have dependencies, but instead of expressing them outright like any other .net repository, it's hiding them behind aka.ms links.

I'm a little hesitant of adding back functionality that lets customers modify the implicit categories of build artifacts.

**Comment by mmitche** [comment]
@hoyosjs I believe there are nuget apis specifically for querying for packages.

**Comment by mmitche** [comment]
@jander-msft @hoyosjs If the latest links are what is being used to determine what the latest build is...why not just use * versioning and a nuget feed? that seems like it would be much simpler.

**Comment by MichaelSimons** [comment]
> Can this be solved via the dependency flow mechanism? 

We met with @mmitche and company a good year ago or so ago on this topic.  IIRC the problem that surfaced in the discussion was the lack of a mechanism in place to run arbitrary code to update the Dockerfile artifacts.  We would certainly be open to discussing this again if things have changed.

**Comment by MichaelSimons** [comment]
cc @mthalman

**Comment by jander-msft** [comment]
> @jander-msft @hoyosjs If the latest links are what is being used to determine what the latest build is...why not just use * versioning and a nuget feed? that seems like it would be much simpler.

It's not the latest version that dotnet-docker needs, it is the latest version within the 5.0.X line. In the future, when we go to 5.1.X, 6.0.X, etc... dotnet-docker will need to get the latest version within each of those lines (including previous lines such as 5.0.X). The versioning is similar to how the dotnet runtime, sdk, etc use versioning where each line needs to be maintained independently for servicing.

Pushing the knowledge of what is the latest version for each of these lines to dotnet-docker is not automatable. dotnet-docker is just looking at aka.ms/dotnet/net5/rc2/diagnostics/monitor5.0/dotnet-monitor.nupkg to determine the latest version within the 5.0.X line. In the future, we expect to add knowledge of the next versioning lines (e.g. aka.ms/dotnet/net5/rc2/diagnostics/monitor5.1/dotnet-monitor.nupkg and aka.ms/dotnet/net5/rc2/diagnostics/monitor6.0/dotnet-monitor.nupkg).

**Comment by mmitche** [comment]
Okay, we can fix this if it's absolutely necessary, though I do wonder about the wisdom of using a latest link in this case. It means that a new build of a docker image could easily be non-deterministic.

@MichaelSimons We can revisit the version update code, though I don't think it can run arbitrary code from the repo, from both a practicality and security standpoint. Could we constrain the update in such a way that the dockerfiles can be easily manipulated by Maestro?

**Comment by jander-msft** [comment]
> Okay, we can fix this if it's absolutely necessary, though I do wonder about the wisdom of using a latest link in this case. It means that a new build of a docker image could easily be non-deterministic.

Only the nightly image build uses the latest link to determine the latest version for each versioning line. The release image build will use manually set versions, thus they are deterministic.

**Comment by MichaelSimons** [comment]
> It means that a new build of a docker image could easily be non-deterministic.

The latest link is just being used by the update automation to determine what the latest version is so that the Dockerfile can be updated accordingly.  The Dockerfiles themselves reference static versions.  

[dotnet/monitor Dockerfile snippet](https://github.com/dotnet/dotnet-docker/blob/nightly/src/monitor/5.0/alpine/amd64/Dockerfile)
``` dockerfile
# Install .NET Monitor
ENV DOTNET_MONITOR_VERSION=5.0.0-preview.3.20523.1
RUN wget -O dotnet-monitor.$DOTNET_MONITOR_VERSION.nupkg https://dotnetcli.azureedge.net/dotnet/diagnostics/monitor5.0/dotnet-monitor.$DOTNET_MONITOR_VERSION.nupkg \
    && dotnetmonitor_sha512='86936df6ff763d5eceba18490dd1a745d7cf8b84a0999a408415bdfb35c687dc023caa5eb66cbea09a33065f36470400f09be3d7456de80911a87415aaaadc01' \
    && echo "$dotnetmonitor_sha512  dotnet-monitor.$DOTNET_MONITOR_VERSION.nupkg" | sha512sum -c - \
    && dotnet tool install dotnet-monitor --tool-path /app --add-source / --version $DOTNET_MONITOR_VERSION --no-cache \
    # To reduce image size, remove the copy of the nupkg under the tools.
    && find /app -print | grep -i '.*[.]nupkg$' | xargs rm \
    && rm dotnet-monitor.$DOTNET_MONITOR_VERSION.nupkg
```

> Could we constrain the update in such a way that the dockerfiles can be easily manipulated by Maestro?

I will schedule a meeting to discuss this further post 5.0 release.

**Comment by hoyosjs** [comment]
> Okay, we can fix this if it's absolutely necessary, though I do wonder about the wisdom of using a latest link in this case. It means that a new build of a docker image could easily be non-deterministic.

Latest link is not the most stable, I agree. Another reason I remember we had to is there was a versioning scheme change (`5.0.0-preview.2.1234` from `5.0.0-preview.21234`) what caused older packages to be considered newer, so this made NuGet API's to determine the latest package pretty hard. Other options: producing `latest.version` as we did in 3.0 and before, use dependency flow (which looks is not possible right now), or get back the categorization.

**Comment by epananth** [comment]
Matt M fixed this.

**Comment by jander-msft** [comment]
This issue either was not fixed or was regressed again. We're trying to move back to using blob storage again due to the fact that stable version packages get published to darc-pub-* feeds that change with each commit, which probably won't work for dotnet-docker as it works today.

See this build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1460262&view=artifacts&pathAsName=false&type=publishedArtifacts

See that the Windows_NT-AnyCPU.xml manifest has the following entry:
```
<Blob Id="diagnostics/monitor/7.0.0-alpha.1.21558.4/dotnet-monitor.7.0.0-alpha.1.21558.4.nupkg" Category="OTHER" />
```

whereas the MergedManifest.xml has removed the Category specification:
```
<Blob Id="diagnostics/monitor/7.0.0-alpha.1.21558.4/dotnet-monitor.7.0.0-alpha.1.21558.4.nupkg" NonShipping="false" />
```

@epananth, can this issue be reopened (I don't see a way to do that). Also, where is the associated PR for the fix?

**Comment by epananth** [comment]
Reopening this issue, going to investigate

**Comment by epananth** [comment]
I could not find the connecting PR, I missed it, I am working on a fix now

**Comment by epananth** [comment]
I have linked both the Prs. I will merge it after I get back from my vacation.

**Comment by jander-msft** [comment]
FYI, we'll want this to be fixed in the arcade 6.0.0 versions as well so that way we can use this for our 6.0 servicing releases.

**Comment by MattGal** [comment]
@epananth where are we on this?

**Comment by epananth** [comment]
I have a PR and I got some feedback from Matt M on this, so I am working on that. I hoping to have that completed by tomorrow.

**Comment by epananth** [comment]
this is the PR https://github.com/dotnet/arcade-services/pull/1782, the reason this took some time is the way we generated manifest, that code is pretty confusing..

**Comment by jander-msft** [comment]
@ilyas1974, @epananth: https://github.com/dotnet/arcade/pull/8197 was referenced earlier in this issue but still remains open. Does it need to be completed for the preservation of the category metadata to be fixed?

**Comment by riarenas** [comment]
That PR definitely needs to be updated with the real version of the maestro tasks resulting from https://github.com/dotnet/arcade-services/pull/1782 and then merged before this is usable.

**Comment by epananth** [comment]
Yes, you are right. We need to roll out arcade-services change before I can update the maestro task change. I will put this is tracking till we have another rollout..

**Comment by epananth** [comment]
ahh you are right no roll out needed.. finishing up the other PR :)

**Comment by epananth** [comment]
changes merged. Closing this one finally ! :)
