### ISSUE TITLE
Improve Feed package

### ISSUE THREAD

**Issue by JohnTortugo** [dotnet/arcade#660]
It may occur that a build gets blocked for a few hours because another build has the feed container locked. E.g., dotnet/core-eng#4179 . As of now, buildtools publish tasks support a timeout parameter so that users have a clear view of what's happening when the publishing fail on those circumstances.

However, @dagood mentions that a better approach might be needed [here](https://github.com/dotnet/core-eng/issues/4180#issuecomment-420360526):

> Heads up that blob feed publish does legitimately take longer than an hour (for example prodcon final publish), so this will need some work to share time, not just add timeouts.

Cc: @MattGal @mmitche

**Comment by MattGal** [comment]
Wouldn't a publish that legitimately takes longer than an hour simply not supply a timeout, or a huge one?

**Comment by dagood** [comment]
The problem that's up for solving is that the long timeout starves out other builds. They have to wait for an hour due to the global lock, which builds don't tend to handle well due to *them* having short timeouts.

**Comment by dagood** [comment]
I had a phone chat with Matt and it cleared things up for me--we were thinking of different issues.

A timeout on lock acquisition sounds like a good idea to me to prevent publishes from being interrupted partway through. (E.g. if you have 1 hour for publish, and you expect publish to always take less than 40 minutes, you only have 20 minutes where it's acceptable to wait for the lock.) This might cause publishes to sometimes fail when they could have succeeded, but that's better than them being interrupted.

What I was thinking about is finding a way to arrange publishes so that everyone can get it done within their time limits, which is probably not reasonable to try, and completely different.
