### ISSUE TITLE
Arcade's pipeline does not wait for validations to finish before executing publishing

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#6696]
- [ ] This issue is blocking 
- [X] This issue is causing unreasonable pain
There's a chance we will publish arcade SDKs with bugs in them if this isn't fixed.

Arcade's official build is not waiting for the Validate Arcade SDK stage to finish before executing the publishing stage.
![image](https://user-images.githubusercontent.com/23242101/102401858-c9e8fb00-3f98-11eb-9be8-07666edd9616.png)

**Comment by adiaaida** [comment]
Looking at the yaml, we have made it so that publish using darc depends on `${{ parameters.validateDependsOn }}` or `Validate`. I believe that the issue is that instead of depending on Validate, it should depend on `${{ parameters.publishDependsOn }}` (which would include `Validate` and `ValidateSdk`). The question is what should it depend on in the else case (ie, where we are currently depending on  `${{ parameters.validateDependsOn }}`). My inclination is that it should still depend on `ValidateSdk`, which seems to happen regardless, but that's only for arcade. So perhaps that case should just be left alone. Or both cases should just be publishDependsOn, and in the non-validate case, it's just build (which is the default for validateDependsOn)?
