### ISSUE TITLE
Longest build path on BAR uses incorrect data in some cases

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#6737]
The longest build path on BARViz calculates the average official build time based on querying the average runtime times of any pipeline that builds the repo in question, then picks the maximal average per definition. Unfortunately, this means that if there are multiple pipelines that build a repo (runtime is the one in question), the longest one is picked, even if it is not the official build.

Instead, the definition ID that is interesting should be determined based on the definition ID of the previous build that was assigned to the channel.

**Comment by mmitche** [comment]
Today this is resulting in runtime reporting wildly huge values because it's picking up a coreclr superPMI run.

**Comment by mmitche** [comment]
@lpatalas

**Comment by lpatalas** [comment]
@mmitche I'm on FR next week so I can take a look at it on Monday.

**Comment by lpatalas** [comment]
The fix was merged. We need to double-check after the rollout if the times are good now.

**Comment by ilyas1974** [comment]
@lpatalas can you please confirm that this has been resolved.

**Comment by lpatalas** [comment]
@ilyas1974 This was merged to master but was not deployed to production yet because we skipped last two rollouts of arcade-services. If the rollout happens this week than I will do final validation on Thursday and close it.

**Comment by lpatalas** [comment]
I checked the official build times on the graph and now they match with the numbers in "Overall Build Start to Available Time" (https://dev.azure.com/dnceng/internal/_dashboards/dashboard/e1bb572d-a2b0-488f-a58a-54c73a547f0d).

"PR Build Time" for runtime looks suspiciously high but I checked the times in Kusto and it's because of this build: https://dev.azure.com/dnceng/public/_build/results?buildId=938734 which relates to PR https://github.com/dotnet/runtime/pull/42831.

@mmitche I'm going to close this issue because official build times look correct now but if you have a minute then please double check the graph to make sure there's no other errors left.

![net6dev](https://user-images.githubusercontent.com/1406063/106917222-577ad880-6708-11eb-8bf3-509ddfa2b59c.png)
