### ISSUE TITLE
Squelch admonishment from dotnet-install.ps1

### ISSUE THREAD

**Issue by wjk** [dotnet/arcade#6766]
- [ ] This issue is blocking
- [ ] This issue is causing unreasonable pain

When I run `build.cmd` in the root of the WPF repo, the build script proceeds to download not one but two copies of the .NET 5 runtime by invoking `install-dotnet.ps1`. Whenever this script is run, it prints a four-line admonishment about how you should be using the official installers instead. As a result, I get tied of seeing the same warning twice every inner-loop build; printing it also slows down the build by a perceptible amount.

[I have fixed the issue in my fork of WPF here](https://github.com/wjk/dotnet-wpf/commit/9f9aae58ac60933a920deaa3d3b203cd96907541). However, since the script being patched is in eng\common, it would not be useful to propose the change there since eng\common is owned by this repo.

I would appreciate it if you would use the above-linked code to discard the output of `dotnet-install.ps1`, or otherwise prevent the message from appearing on every build. Note that I had to use the “blunderbuss” technique; the redirection of stream 6 also prevents errors generated from the script. However, since the admonishment is printed using `Write-Host`, this was the only code that would do the job. Furthermore, since the script is run within a try/catch block, errors would be handled the same way should the script fail; they just wouldn't be printed to the console. Thanks!

**Comment by markwilkie** [comment]
Hi @wjk!  Thanks for filing this issue, and good job finding the right place etc.  👍 

Generally speaking, we tend to like more logging than less, because when something goes wrong, it's *much* easier to find out what to do.  In this case, WPF needs two different runtimes, which is why you're getting the two logs.  Dumping the output of dotnet-install to the bitbucket means that we'd have a much harder time finding out what the issue if if (or dare I say when...) something goes wrong with the installer itself.

I'm going to close this issue for now, but we're happy to continue the discussion if you'd like.  Cheers
