### ISSUE TITLE
Remove legacy CPD algorithm

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#6782]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Right now we have defaulted the coherency calculation to use the strict algorithm and then fall back to using the regular coherency algorithm. We should remove the legacy algorithm once we're confident that we don't need the fallback anymore.

### Release Note Category
- [x] Feature changes/additions 
- [ ] Bug fixes
- [ ] Internal Infrastructure Improvements
### Release Note Description
Remove the fallback to the legacy coherency algorithm.

**Comment by riarenas** [comment]
This came up again. Dependency updates to installer are blocked due to timeouts during the calculation of the legacy coherency algorithm.

Strict coherency is a lot more sensitive to any repo changes to dependencies and CPD configurations, so in order for us to be able to turn strict coherency into the true and only coherency, we will need to provide self-service ways for repos to find out whether they have a broken coherency configuration.

An idea by @mmitche for achieving this:

* We allow coherency to fail and still do an update PR. This is not the case today.
* In the update PR, we add a new Maestro policy check that is "coherency valid" (sort of like the Do not automerge downgrades). This is always on, regardless of repo policies. If coherency is failing, then we make this check Red

This also allows us to provide the coherency errors we see in the maestro check.

**Comment by garath** [comment]
This came up while investigating dotnet/arcade#12505 and in the Teams chat [[here](https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1676053978078?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1676053978078&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1676053978078&allowXTenantAccess=false)].

**Comment by michellemcdaniel** [comment]
@tkapin @premun This seems to fall under product construction, but we (triage) think that it should be prioritized.

**Comment by tkapin** [comment]
This needs to get prioritized, based on recurrence of the problem #12505. The change is supposed to be done in two steps:
1) remove the fallback to the legacy coherency algorithm in the [PullRequestActor.cs](]https://github.com/dotnet/arcade-services/blob/main/src/Maestro/SubscriptionActorService/PullRequestActor.cs#L1152-L1159)
2) remove the legacy algorithm itself

**Comment by premun** [comment]
FWIW, I just tried to trigger a subscription `23116d50-8f86-4127-4cdc-08d9fbbd4857` and it never appeared (local `update-dependencies` worked) so it might be one to use for debugging purposes.

**Comment by andriipatsula** [comment]
I have a few questions about this issue. @mmitche, @riarenas could you please take a look:

1. I added a GitHub check that informs customers whether the Strict Coherency algorithm completed successfully or not ([check failure](https://github.com/maestro-auth-test/maestro-test2/pull/18454/checks?check_run_id=13346001804) example). The `DarcCoherencyException` exception consists of several fields like `Error(string)`, `PotentialSolutions(List<string>)` ([link](https://github.com/dotnet/arcade-services/blob/a98184ada4647cec5064691ec08115d164a7c567/src/Microsoft.DotNet.Darc/src/DarcLib/DarcCoherencyException.cs#L14-L16)). Should we provide extra information in case the check fails, such as an exception message or a link to documentation?
2. I've been considering whether we can simulate a failure of the Strict Coherency algorithm in our integration tests (the Maestro.ScenarioTests project). Despite my efforts, I haven't been able to find a suitable solution, so I created a custom build that always throws a `DarcCoherencyException` to simulate the failure. Do you have any suggestions for how we can force the algorithm to fail within our [test repos](https://github.com/maestro-auth-test)?

**Comment by mmitche** [comment]
1. I think we would ideally include the exception message and the potential solutions. We can also link to the documentation here: https://github.com/dotnet/arcade/blob/main/Documentation/Darc.md#coherent-parent-dependencies. Once legacy coherency is removed, we can update that documentation to better reflect the current state of things.
2. We should be able to create a scenario test that simulates invalid strict coherency. There are some tests that already deal with coherency: https://github.com/dotnet/arcade-services/blob/main/src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_GitHubFlow.cs#L183-L198. I think you'd essentially change around the data in this test so that the dependency [here](https://github.com/dotnet/arcade-services/blob/main/src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_GitHubFlow.cs#L111-L120) `Baz` does not exist in `Foo`'s commit, as this is what `Baz` is tied to: https://github.com/dotnet/arcade-services/blob/main/src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_GitHubFlow.cs#L122-L130. If you changed `Baz` to `BazWithWrongName` that would happen.

**Comment by riarenas** [comment]
> @andriipatsula @riarenas Could we force the coherency merge policy to:
> 
> 1. Always be used?


I think this is doable. When we post the checks, we could have this one always be posted. A good starting point to figure out where to stick this is https://github.com/dotnet/arcade-services/blob/94f02465e0a8d854a0baf5cb77c1bd4a2a9f1c1c/src/Maestro/SubscriptionActorService/PullRequestActor.cs#L559, which is where we read all the merge policies and post them to GitHub

> 2. Not influence whether Maestro attempts to auto-merge the PR?
> 
> Most of the empty merge policies are probably mistakes or oversights, but some may be intentional to avoid auto-merging. Adding the coherency check policy may cause some of these to auto-merge when not desired.

This one is a bit more involved. The way we currently create checks right now, they are all considered "merge policies" and will cause an auto merge if they all succeed: https://github.com/dotnet/arcade-services/blob/94f02465e0a8d854a0baf5cb77c1bd4a2a9f1c1c/src/Maestro/SubscriptionActorService/PullRequestActor.cs#L501

In order to do 1 and 2 together, I think we would need to introduce a new concept of "policies that do not influence the merging of the PRs". This would probably be an interface similiar to the IMergePolicy and IMergePolicyEvaluator interfaces and even their implementations (in the sense of retrieving and posting checks to github PRs), except they would not influence the merging of PRs by having the PullRequestActor not look at them when deciding to merge a PR or not.

**Comment by andriipatsula** [comment]
@mmitche could you please check the comment above? Thanks.

**Comment by mmitche** [comment]
Agree with @riarenas that doing 1 and 2 together makes the most sense. I don't think this is critical for this CPD removal PR, but I think we should file an issue and do it after this PR is checked in. My hunch is that the intersection of the following sets is pretty small:
- Branches that Maestro can actually auto-merge to (this requires no code review policy for a branch, otherwise auto-merge fails)
- Branches that have coherent parent dependencies in their V.D.xml files.
- Branches with no merge policy **because** no auto-merge was desired (vs. just an oversight)
- Branches where the strict CPD merge policy would be desired because of failures in strict CPD.

Perhaps we should not add the CPD merge policy to branches with no merge policy **except** for cases where:
- We saw strict CPD failures **and** 
- Maestro doesn't have the permissions to actually do an auto-merge.

I can help with the second aspect if you get me a list of subscriptions that fail that strict CPD and have no merge policies.

**Comment by andriipatsula** [comment]
PR merged. Follo up issue: https://github.com/dotnet/arcade/issues/13801

**Comment by andriipatsula** [comment]
> Perhaps we should not add the CPD merge policy to branches with no merge policy except for cases where:
> * We saw strict CPD failures and
> * Maestro doesn't have the permissions to actually do an auto-merge.
>
> I can help with the second aspect if you get me a list of subscriptions that fail that strict CPD and have no merge policies.

The list of subscriptions for the past 6 m. for which the Strict coherency algorithm failed (15 distinct subscriptions): [query](https://ms.portal.azure.com/#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fmaestro-prod-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fmaestro-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA12PT0%252FDMAzF73yKp16WwjK1mzSJww4IcYMbN4RQmrg0Yk2G42gD8eFJK%252FFHk3zxs%252F38fnSydBAfQ7r4wnEgJlxiMAnVjZXItzHYzEzBftxH%252B%252FboR4pZ7n6OKpjgIEVNYsYDOpIjUYByRmiS1bpZb3TTlqqxWuFM3%252Bp2U9flM52EitMYgwzYobixxH5u1a%252F9v8WUu2TZzyFevCsnZcDGiiq537NPfpog9pDMAZ1J5GD%252FYLAvNOgjw0yYWKinRl9roz%252Bfr%252BrFTORQSGF6Ia6WaJdTS%252FxAKZlXmqI4n8QHK%252BdhvgEaT0dsUwEAAA%253D%253D)

1f3b2792-d92f-47ef-f8e8-08db309149d7
c395c61c-56c9-4874-9264-08db24ab3ced
f8ee08b0-6c3d-485a-6895-08db0a1df366
9a2944cb-7dee-4bf2-a65c-08dabd10ae64
23116d50-8f86-4127-4cdc-08d9fbbd4857
7787dd03-cbf4-4297-391c-08d8e9750bf8
d29ed396-31b9-4307-51a3-08d9b98d2513
2f20696b-414c-44f2-a5a4-08d8ed868088
13946afb-e3d4-44f0-2683-08daecc8f206
f6719b3b-6c4d-4a69-45b1-08db67739e29
6b62a3d9-0dd9-4f00-2687-08daecc8f206
085b8bd9-e630-441d-931c-08db157be54d
1e4fa27f-25cc-4275-f3f1-08d8e97c775d
c0f77a87-302f-4225-6440-08db30930111
5f4141ca-7ec3-45bd-2cce-08daee6e84fe

@mmitche checked all those subscriptions. They either has a merge policy enabled already, or the target branch is protected.
