### ISSUE TITLE
Generate aka.ms links with authentication for internal builds

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#6847]
For internal builds, we need to be able to have aka.ms links redirect authentication to the build links so that internal partners can access them

**Comment by MattGal** [comment]
Some notes from today's experimenting:

- URL query parameters and HTTP Headers all go right through aka.ms links, making them ideal ways for passing along authentication tokens
- routes with /s in them don't seem to work with aka.ms (need to follow up), e.g. if your aka.ms points to `http://foo.com/` and http://foo.com/bar/baz exists, navigating that aka.ms link with /bar/baz appended doesn't seem to work.

**Comment by MattGal** [comment]
I've played around with this and there isn't much to implement:

### Assumptions:

- Backing storage of what is linked via aka.ms is still Azure Storage account (very likely)
- Authenticated usage is primarily build automation 

### What we'd do:

- Ensure that all aka.ms links created which need authentication are created with "allow query parameters" value set to true.
- Use existing SAS token already in our vaults / variable groups when fetching bits; it should work with basically the same code other than it would likely need to understand the new, hopefully flatter, path structure.
- Append storage SAS to any aka.ms blob urls used, which is passed to backing storage and experimentally works the same.


### Open questions:

- Do we have want to have "private" builds on more than one backing storage account?
- Should we create a less-attractive-to-malicious users named storage account for private builds?  e.g. "dotnetcliprivate"
- Do we want to build an intermediate auth system that uses an existing system (say AAD auth and traditional Microsoft SG) via a script to authenticate as this user to a key vault, and fetch a SAS token for the user (ideally never writing it down on disk). It would mostly only be helpful for local users, since it doesn't help automated builds.

I'll leave this in WIP til I can discuss with the epic team standup.

**Comment by MattGal** [comment]
OK, I think creating automation that fetches SAS tokens for users to authenticate to private feeds is both outside the scope of this epic and something that can probably leverage what the secret management epic folks are doing later.

However, I noted two things about the links were generating today:

- They are getting created with `"isAllowParam": false,`, meaning they will not support query parameters until this is updated (I will create a PR for this tomorrow in Arcade)
- They are getting created without a SG owner, meaning there's no way to browse them after the fact (and indeed the REST API doesn't even seem to support GET without a short name, so even enumerating them seems difficult).  THe plan is to just create an SG that is owned by dnceng tomorrow, and provide this value instead of null.

**Comment by MattGal** [comment]
https://github.com/dotnet/arcade/pull/6900 should be all that's required to do both the above.  Seems like we just never plumbed through any default SG for link ownership.
