### ISSUE TITLE
Remove V2 publishing from arcade master 

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#6931]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

**Comment by epananth** [comment]
Add test 
1) when channel is not configured in publishingConstants (https://github.com/dotnet/arcade/pull/6999)

**Comment by mmitche** [comment]
I'd like to bump this up as something we should do soon. All publishing except for v3 should be removed from main. We've hit a number of bugs recently due to the complexity of default settings, people not updating from v2 to v3, etc. Anything on arcade 5.0 and beyond should be on v3, and so we should remove v1 and v2.

While at it, the `PublishingInfraVersion` enum should be refactored to be a little clearer. The enum uses qualitative terms right now (`Legacy`, `Latest` and `Next`) in conflicting contexts. For instance, if a **user** references "Latest", that makes sense, where Latest may be a moving target. But when determining behavior based on version, "Latest" should not be used, and instead references to specific versions should be used. For example:

```
// Non-ideal
if (publishingInfraVer == PublishingInfraVersion.Latest) {
  // Publish one way
} else {
  // NYI
}

// More ideal
if (publishingInfraVer == PublishingInfraVersion.V3) {
  // Publish one way
} else {
  // NYI
}
```

This is at least some source of the issues. In the process of eliminating the old publishing infra versions I would update the enum to `Legacy` and `Next` and add values for the old publishing infra versions. And then wherever arcade uses those values, update to compare against `V3` and error out appropriate for anything else.
