### ISSUE TITLE
The arcade build needs to not report a bunch of errors

### ISSUE THREAD

**Issue by ChadNedzlek** [dotnet/arcade#7121]
- [ ] This issue is blocking 
- [X] This issue is causing unreasonable pain

The arcade build [example](https://dev.azure.com/dnceng/public/_build/results?buildId=1044189&view=results) reports a bunch of errors that don't matter. Our builds shouldn't just spew errors. Warning are bad enough, but ignorable errors aren't something we should get in the habit of.

**Comment by riarenas** [comment]
Introduced by https://github.com/dotnet/arcade/commit/5747c84731369c3977580b64c627154fec92b6d7

```
##[error](NETCORE_ENGINEERING_TELEMETRY=Build) One or more eng/common scripts do not use telemetry categorization.
See https://github.com/dotnet/arcade/blob/master/Documentation/Projects/DevOps/CI/Telemetry-Guidance.md
The following ps1 files do not include telemetry categorization output:
D:\workspace\_work\1\s\eng\common\generate-locproject.ps1
##[error](NETCORE_ENGINEERING_TELEMETRY=Build) configure-toolset.ps1 returned a non-zero exit code
``` 

I agree that errors that don't fail the build are not great, and the check from this script
https://github.com/dotnet/arcade/blob/6cc4c1e9e23d5e65e88a8a57216b3d91e9b3d8db/eng/configure-toolset.ps1#L2
 should fail the build so that this blocks PRs from going in.

**Comment by riarenas** [comment]
Fixed by https://github.com/dotnet/arcade/pull/7122, https://dev.azure.com/dnceng/public/_build/results?buildId=1045633&view=results shows no warnings.
