### ISSUE TITLE
Unblock MSbuild to onboard to V3

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#7255]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Update maestro task version in arcade so that msbuild can on board to V3 publishing

**Comment by MattGal** [comment]
[Async Triage] @epananth since you've self assigned this one, can it go into your current epic?

**Comment by epananth** [comment]
In this fix, we will force Publishing.props to send the value for the azure repo uri.

**Comment by epananth** [comment]
@MattGal  is going to help the team to build from azdo mirror instead of github directly.

Reference to the chat conversation  : https://teams.microsoft.com/l/message/19:1dad2081c8634f34915d88dce6220265@thread.skype/1618454901509?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1618454901509&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=Arcade&createdTime=1618454901509

**Comment by MattGal** [comment]
Ooops, I didn't notice this one, but I already did most of the stuff in https://github.com/dotnet/core-eng/issues/12875.  

The work is mostly done, but SourceLink broke expectedly as noted https://github.com/dotnet/msbuild/issues/6375 .  Since this translation happens in Arcade, I'm exploring workarounds.   It will either be:

- Try setting the ScmRepositoryUrl to the GitHub path in the build and turn off translation, so this is honored by the Source Link stuff
- Teach Arcade's regex stuff to translate devdiv.visualstudio URLs back to the proper one (this seems like a waste as this is the only repo building from devdiv.vs right now, but possible)

**Comment by MattGal** [comment]
Explored setting ScmRepositoryUrl in directory.build.props but it didn't work, so just added understanding of devdiv.visualstudio to the regex.

**Comment by MattGal** [comment]
Once the release/5.0 port of the sourcelink fix merges, I'll close this as that will be the last known issue falling out of the move from github source.

**Comment by MattGal** [comment]
PR merged, optimistically closing this issue ...
