### ISSUE TITLE
Some dependency updates are intermittently failing due to timeouts in service fabric actors

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#7262]
- [ ] This issue is blocking 
- [X] This issue is causing unreasonable pain
Errors are being reported almost daily with this failure mode.

The DependencyUpdateErrorProcessor in Maestro has been opening issues about subscription updates failing to complete with this error (See issues linked to this one)

```
Unexpected error processing action: Acquisition of turn based concurrency lock for actor '7bf32a0c-3505-43af-42b0-08d79559e63d' timed out after 00:01:38.3510000
```

For the subscriptions I've checked, they are mostly up to date now so it might be point in time problems, but we should see if we can increase the timeout or prevent this unexpected error.

**Comment by ChadNedzlek** [comment]
Hrm... This sounds like some weird concurrency problem inside the actors... I'm not sure how the actors are constructed, or why an actor would be waiting to execute.  @alexperovich or @epananth, any ideas?

**Comment by jakubstilec** [comment]
[Async Triage]: @riarenas, @ChadNedzlek where should it go?

**Comment by ChadNedzlek** [comment]
It sounds like FR... if dependency updates that customers are depending on are just not happening, we should probably fix that.

**Comment by MattGal** [comment]
[Async Triage] Agree with Chad, putting in FR.

**Comment by alexperovich** [comment]
The concurrency model for actors is quite simple at its core. Even actor instance can only have one method in progress at any time. This timeout problem is caused by too much traffic trying to go to the same actor, some of them will get in the back of the line and timeout.

**Comment by alexperovich** [comment]
These all look like subscription specific actors, so there shouldn't be much contention. This is probably just a previous update that is taking too much time. The system checks every 5 minutes, so if it takes 7 minutes to do one update the next update would time out.

**Comment by AlitzelMendez** [comment]
After looking to this issue, the problem is a Reminder of the actor + the call that is trigger and is waiting for the actor.  

  

Most of the time the reminder duration is between 12-15 seconds but in some uncommon cases that reminder takes more than 2 minutes, sometimes until 5 minutes, when this happens and this call gets trigger is not able to acquire the actor (because is processing the reminder call). 

  

There are two paths to solve this issue, one is passing a cancellation token to the reminder, but the process of the reminder is quite extensive with a bunch of calls. To at least have an idea in which part exactly the process is taking that long I will add logs to know in which part we should focus our effort.  

  

In the other hand we could increase the timeout of the actor but this only can be defined (from my understanding and what I investigated) at the creation of the actor, which is a process that lives on the ServiceHost and I don't know if we want to do changes on that area.  

@ChadNedzlek , @alexperovich  do you have thoughts about this?

**Comment by alexperovich** [comment]
The only solution is to either reduce the amount of time spend processing things, or increase the timeout. Long-running actor methods by design block other calls to the actor.

**Comment by ChadNedzlek** [comment]
@ilyas1974 This is just sitting on the backlog, and isn't blocking anything.  I'm going to bounce out for triage.

**Comment by riarenas** [comment]
Closing for now, will reopen if I see another burst of dependency flow errors due to this problem
