### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by gaoconggit** [dotnet/arcade#7379]
https://pkgs.dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_packaging/45bacae2-5efb-47c8-91e5-8ec20c22b4f8/nuget/v3/flat2/transport.runtime.linux-x64.microsoft.netcore.runtime.coreclr/index.json

`{
"$id": "1",
"innerException": null,
"message": "Can't find the package 'transport.runtime.linux-x64.microsoft.netcore.runtime.coreclr' in feed 'dotnet-public'.",
"typeName": "Microsoft.VisualStudio.Services.NuGet.WebApi.Exceptions.PackageNotFoundException, Microsoft.VisualStudio.Services.NuGet.WebApi",
"typeKey": "PackageNotFoundException",
"errorCode": 0,
"eventId": 3000
}`

**Comment by riarenas** [comment]
Hi @gaoconggit Can you please provide some details?

* What were you trying to build? Doesn't look like it's this repository because that package is not used anywhere.
* Is this being built locally or in a CI environment?
* That package is indeed not in the dotnet-public feed so it's not surprising that it wouldn't be there. Are you sure you need to restore that package?

**Comment by riarenas** [comment]
Giving it a few more days to hear from @gaoconggit, should close if we don't.

**Comment by markwilkie** [comment]
6 days passed.....closing

**Comment by YairHalberstadt** [comment]
I'm getting a similar issue trying to build Roslyn: https://github.com/dotnet/roslyn/issues/53629

**Comment by markwilkie** [comment]
@YairHalberstadt  - this is actually a closed issue.  But, if you're still having issues, be sure and reach out to dnceng and we'll do our best to help.

**Comment by 333fred** [comment]
@markwilkie Yair is external, internal aliases don't work :0
