### ISSUE TITLE
Arcade 6.0.0 error

### ISSUE THREAD

**Issue by Sanan07** [dotnet/arcade#7461]
- [x] This issue is blocking 

After updating arcade by this [PR](https://github.com/microsoft/vstest/pull/2913/files), our signed pipeline started to fail with this error ` Required folder 'C:\A\1\86\s\artifacts\release\packages\manifest' does not exist`. Pipeline : [link](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4796169&view=results)

How can we fix it? Previously we did not get that error.

**Comment by riarenas** [comment]
It's not going to be a straightforward upgrade so I'm not surprised that you're seeing breaking changes. Arcade has changed a lot of things between what is produced by the 3.x (1.0.x) branch and what is produced by main (6.0.x).
 
I suggest reverting that change and staying in the 3.x channel until you have some time to go through all the errors that will surface in your official build. This error in particular is due to the changes that we have made to make how we publish packages uniform across all of .net. Since you don't use any of the arcade build scripts to build, components of the build that the infrastructure expects are not there. In this case, nothing is calling the "PushToAzureDevOpsArtifacts" task that would've placed the manifests and assets in the right location. 
 
Basically, this repository was only using some pieces of arcade, and the way that you glued them together to sort of work doesn't anymore.
 
There are three paths forward:

* Stay on the 1.x versions
* Figure out piece by piece everything that fails, and glue it together again in a way that matches how the SDK works in 6.0 versions. 
* Fully onboard the repository to build and publish using the arcade infrastructure. 

We have a guide on how to onboard to using the publishing infrastructure here: https://github.com/dotnet/arcade/blob/main/Documentation/CorePackages/Publishing.md#basic-onboarding-scenario-for-new-repositories-to-the-current-publishing-version-v3 but it assumes that you are using the Arcade SDK to build your repo. 

This guide: https://github.com/dotnet/arcade/blob/e7ede87875f41a9b3df898ae08da5ebc96e24f56/Documentation/DependencyFlowOnboardingWithoutArcade.md#creating-a-manifest might also provide some help to onboard onto the publishing infrastructure without using the Arcade SDK

**Comment by Sanan07** [comment]
@riarenas thank you
@Haplois please look, as you are currently working on arcade

**Comment by Haplois** [comment]
@riarenas, 

We depend on `GenerateBuildManifest` task to generate our build manifest. It's removed [recently][2], so we need to follow the new documentation [here][1]. @Sanan07, it's known and I'll be fixing this on Friday. 


[1]: https://github.com/dotnet/arcade/blob/main/Documentation/DependencyFlowOnboardingWithoutArcade.md
[2]: https://github.com/dotnet/arcade/pull/6729

**Comment by missymessa** [comment]
Hi @Sanan07 and @Haplois, checking in to see if you need any more assistance from the .NET Core Engineering Services team on this issue. Thanks!

**Comment by Haplois** [comment]
Thank you @missymessa, I just started working on this. I'll ping you if I need help, thanks!

**Comment by missymessa** [comment]
@Haplois I'm going to close this issue then. If you have any other problems, feel free to re-open it.
