### ISSUE TITLE
Tagging script not able to create tags for 5.0.301 SDK

### ISSUE THREAD

**Issue by rbhanda** [dotnet/arcade#7554]
There was an issue with "\\vsufile\patches\sign\NET\NET_CORE\5.0.7\configs\manifests\manifest-204.json" which is used by the tagging script. Although, the manifest.json has both the 204 and 301 SDKs, the script created tags only for 204. 

As a workaround, I copied "\\vsufile\patches\sign\NET\NET_CORE\5.0.7\configs\manifests\manifest.json" from the 5.0.301 SDK build and re-ran the tag creation

**Comment by adiaaida** [comment]
These are the locations where this is happening:

https://dev.azure.com/dnceng/internal/_git/dotnet-release?path=%2Fsrc%2Fscripts%2Frepo-tagging%2Frepo-tagging.ps1&version=GBmacos-signing-changes&line=233&lineEnd=234&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents

Basically, we assume that if we've found more than one entry for a particular repo, we only consider the first, which may make sense for some repos (runtime, aspnetcore, etc), but not for installer/sdk. It's also marked as a "quick fix". So obviously it wasn't quite right. What I think we need to do is consider every copy of the repo, because it may be expected for there to be multiple, and tag them based on the asset version (like we do). If we see multiple with the same version, then we probably only want to tag one of the shas, and we'll need to do some considering for that, but when the version is different, we likely want to tag multiple commits

**Comment by riarenas** [comment]
@adiaaida does this make sense as part of your epic?

**Comment by adiaaida** [comment]
Yes, it should be

**Comment by adiaaida** [comment]
I believe @vseanreesermsft fixed this. Closing.
