### ISSUE TITLE
Investigate SDL errors in arcade's release/3.x and release/5.x branch

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#7616]
- [X] This issue is blocking 
We might not be reporting SDL issues correctly.

Arcade's official build in the release branch is failing with SDL errors. The errors say they are blocking, but the step still succeeds. We should understand:

* [ ] is this a real sdl issue? if so, fix it. 
* [ ] Is it expected for these errors to fail the sdl step, and if so, why aren't we failing?

Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1228948&view=logs&j=7d9eef18-6720-5c1f-4d30-89d7b76728e9&t=f511b583-5060-5810-7549-865816347c8e&l=878

Adding directly to FR @ilyas1974

**Comment by riarenas** [comment]
I'm... not sure how I made this an epic.

**Comment by lpatalas** [comment]
I think the step is not failing because of the same issue that we solved on `main` some time ago: https://github.com/dotnet/core-eng/issues/13247. We use `$LASTEXITCODE = 0` at the top of the file which shadows global `$LASTEXITCODE` variable and then we only check this local one which is always 0. I'm currently testing a fix.

**Comment by lpatalas** [comment]
The certificate that SDL is complaining about is for UWP test runner. It was used to sign the installation package. It's expired since 2019 and I'm pretty sure it's basically useless at this point. I think the easiest solution would be to remove the certificate because the runner is built manually and if anyone wants to build it then they will need to generate a fresh certificate anyway. I'm not sure if it's even used anymore. The last commit is from 2019. Readme for those tools can be found [here](https://github.com/dotnet/arcade/tree/release/3.x/src/Microsoft.DotNet.Uap.TestTools).

There is also an option to add exclusion for this alert but I'm not sure if it's worth it in this case?

@riarenas Do you think removing the cert is the right thing to do?

**Comment by riarenas** [comment]
I think I remember @alexperovich knows something about this cert so he might have more context. It sounds like removing it is safe, especially since we deleted it in main.

**Comment by riarenas** [comment]
we removed everything about that here: https://github.com/dotnet/arcade/pull/4110. Maybe @ViktorHofer can confirm that we can remove it just the same in the release branch.

**Comment by lpatalas** [comment]
We have the same issue related to the usage of `$LASTEXITCODE = 0` on `release/5.0`. I think it makes sense to also fix it there because it can bite us sooner or later.

**Comment by lpatalas** [comment]
I've created PR with the `release/3.x` changes: https://github.com/dotnet/arcade/pull/7654. I also have the same fixes prepared for `release/5.0` branch but I will wait with them until we merge 3.x so that I don't have to do the same fixes twice.

**Comment by ViktorHofer** [comment]
> we removed everything about that here: #4110. Maybe @ViktorHofer can confirm that we can remove it just the same in the release branch.

Feel free to remove it entirely. We don't test for Uap in the release branches anymore.

**Comment by ilyas1974** [comment]
Once the changes have been merged in the 3.x branch, we need to perform the same changes to our 5.x branch.

**Comment by lpatalas** [comment]
I have the changes prepared for `release/5.0` on the separate branch: https://github.com/dotnet/arcade/tree/lupatala/fix-sdl-5.0.

**Comment by premun** [comment]
We decided to close this and in case of new SDL alerts, re-open
