### ISSUE TITLE
Publish task PublishArtifactsInManifest failing in AspLabs pipeline

### ISSUE THREAD

**Issue by JunTaoLuo** [dotnet/arcade#7636]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

I see that the publishing step of the AspLabs hasn't passed in a long time: https://dnceng.visualstudio.com/internal/_build?definitionId=249&_a=summary and the error suggests something is wrong in the task `PublishArtifactsInManifest` in arcade. It looks like my attempt didn't fix it so I'm hoping someone can help from Arcade can help us.

This is currently blocking publishing packages from this repo and we are trying to push out some new bits for customers to try so there is some urgency.

Investigation wise, I think this is related to the work in https://github.com/dotnet/arcade/pull/7317. This repo uses publishingInfraVersion=2. Given that most repos are using version 3 already and that this is a low traffic repo, I can see how we didn't notice the problem. Is there an issue with publishing infra version 2 that needs to be fixed? Or do we need to do work to move to version 3 like the rest of the repos?

FYI @epananth @DamianEdwards

**Comment by JunTaoLuo** [comment]
BTW the Arcade version in the repo is 6.0.0-beta.21357.3 which is relatively new.

**Comment by epananth** [comment]
Since you are using latest arcade version, its better to move to V3 publishing, that error should go away after that

https://github.com/dotnet/arcade/blob/main/Documentation/CorePackages/Publishing.md#how-to-upgrade-from-v2-to-v3

**Comment by epananth** [comment]
We made sure we still support older publishing version when I added parallelism to the publishing infra 3. But that being said, its best to get on boarded with V3 publishing since its the latest and makes publishing lot more cleaner. 

V3 publishing -> https://github.com/dotnet/arcade/blob/main/Documentation/CorePackages/Publishing.md#what-is-v3-publishing-how-is-it-different-from-v2

**Comment by epananth** [comment]
@JunTaoLuo can we close this issue?

**Comment by JunTaoLuo** [comment]
I'm still having trouble. It passed on an internal build but the [official build](https://dnceng.visualstudio.com/internal/_build/results?buildId=1243394&view=logs&j=226748d0-f812-5437-d3f0-2dd291f5666e&t=bad11196-972e-5d03-45a8-9db526506073) fails with
 
```
The property TargetFeedConfig is required but doesn't have a value set.
```
 
Is there some darc configuration that I need to update for this to work?

**Comment by epananth** [comment]
I checked the repo, you are using the latest version of arcade sdk but all other version like maestro task is using old version 
Please update this to the latest version and that should be help. 

Right now, you are (since you are using the older task versions for maestro task https://dev.azure.com/dnceng/internal/_git/dotnet-arcade?path=%2Feng%2FVersions.props&version=GBmain&line=82&lineEnd=83&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents and maestroclient https://dev.azure.com/dnceng/internal/_git/dotnet-arcade?path=%2Feng%2FVersions.props&version=GBmain&line=77&lineEnd=78&lineStartColumn=1&lineEndColumn=1&lineStyle=plain&_a=contents you are forcing the manifest to have publishing infra 2 
![image](https://user-images.githubusercontent.com/47157394/126394119-4f0cf0ef-5223-4e51-b0ce-3c126ed8b8f9.png)

But in post-build.yml you are using Publishing-infra =3

**Comment by epananth** [comment]
I looked at the version.props for your repo 

https://dnceng.visualstudio.com/internal/_git/aspnet-AspLabs?version=GBmain&path=%2Feng%2FVersions.props, it has to have dependency on MicrosoftDotNetBuildTasksFeed task. 

@riarenas  please correct me if I am wrong here.

**Comment by riarenas** [comment]
It's actually not expected that a repo would have a reference to the maestro build tasks. That should come with Arcade.

**Comment by riarenas** [comment]
I think I see the problem, and it's silly. 

https://github.com/aspnet/AspLabs/blob/main/eng/Publish.props needs to be renamed to Publishing.props so that the Arcade SDK will try to read from it.

**Comment by JunTaoLuo** [comment]
Oh, duh... oops.

**Comment by riarenas** [comment]
Hopefully that's all it takes, but since this is blocking, moving this to FR to keep assisting if needed.

**Comment by epananth** [comment]
thanks @riarenas !

**Comment by JunTaoLuo** [comment]
Looks like that fixed it. Thanks all @riarenas @epananth
