### ISSUE TITLE
Arcade publishing failing for files over 2GB

### ISSUE THREAD

**Issue by mmitche** [dotnet/arcade#7660]
- [x] This issue is blocking 
- [ ] This issue is causing unreasonable pain

Blocking the installer build promotion in main right now. The source tarball is > 2GB. https://dev.azure.com/dnceng/internal/_build/results?buildId=1255098&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a

**Comment by riarenas** [comment]
I think this is https://stackoverflow.com/questions/18720435/httpclient-buffer-size-limit-exceeded, when making the request, httpclient tries to allocate a buffer for the response contents, but it exceeds [MaxResponseContentBufferSize](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient.maxresponsecontentbuffersize?view=net-5.0) and fails. We might be able to just set the httpcompletionoptions so that the buffer is not created. I will create an sdk with the changes and test it against the failing installer build.

**Comment by riarenas** [comment]
Still requires updating arcade's main branch: https://github.com/dotnet/arcade/pull/7664

**Comment by riarenas** [comment]
Installer build https://dev.azure.com/dnceng/internal/_build/results?buildId=1256225 was able to publish using the new sdk.
