### ISSUE TITLE
OneLoc process has no way to notify loc team if things are succeeding

### ISSUE THREAD

**Issue by jmarolf** [dotnet/arcade#7765]
In the old loc system the loc team would submit PRs and work with the team to merge them in. In OneLoc PRs are fire-and-forget via and automated system with no notifications to the Loc team of whether their PRs are mergeable (or even buildable). 

Would be nice to have an automated system to notify the loc team is the build fails on a loc PR.

**Comment by MattGal** [comment]
[Triage]: Sounds cool, but given the name "OneLoc" may not be something we control.  @jonfortescue can you comment?

**Comment by jonfortescue** [comment]
We own the last mile infrastructure of running the OneLocBuild task, so it does fall under our purview. The specific scenario described is:

1. OneLocBuild runs, creates a PR
2. That PR fails due to something OneLocBuild did

The OneLocBuild task isn't actually running in step 2, so I'd imagine we could potentially build infrastructure that:

1. Detects an xliff-tasks failure
2. Detects that the build was triggered by a loc PR
3. Opens a Loc Issue in ceapex alerting them of the problem

**Comment by riarenas** [comment]
This seems like a broken model from the get go. The system shouldn't be opening broken PRs with no way to interact with the team other than manually creating a PR. Is this something we can push on the loc team to add notifications for?

**Comment by jonfortescue** [comment]
@riarenas We could absolutely push on the loc team to monitor the PRs they open and alert themselves if those PRs break.
