### ISSUE TITLE
Arcade-validation scheduled build failing due to pool provider configurations

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#7987]
- [ ] This issue is blocking 
- [X] This issue is causing unreasonable pain
This means we're not able to run the daily scheduled build that:
1. Tests out the staging pools
2. Attempts to promote arcade even if there haven't been any newer changes

The scheduled arcade-validation build is failing to get machines, and is failing with the following error:

```
Failed to request agent. Exception Image Build.Server.Amd64.VS2017 doesn't exist in pool NetCore1ESPool-Internal-Int
```

The pool configuration for the scheduled runs is here: https://github.com/dotnet/arcade-validation/blob/eff4a01ca55e2ace8acb0cacb4f50b437252e39d/azure-pipelines.yml#L15-L20

Are we allowed to send jobs to the int 1es pools, or is this something that we should change?

**Comment by riarenas** [comment]
Any ideas @ulisesh @lpatalas @jonfortescue ?

**Comment by lpatalas** [comment]
@riarenas We're on it. We are just discussing it on 1ES teams channel

**Comment by lpatalas** [comment]
Issue happens because staging CloudTest images have -Int suffix but we forgot to take it into account when migrating the pipeline.

The plan to solve it is to:
1. Revert the changes to unblock promotion (https://github.com/dotnet/arcade-validation/pull/2590)
2. Increase max scale for staging pools to 10
3. Change staging image names or update pipeline yaml to include the suffixes

**Comment by lpatalas** [comment]
I've created PR to increase size for staging pools here: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/18673

**Comment by lpatalas** [comment]
This was already merged and the build runs fine on staging pools: https://dev.azure.com/dnceng/internal/_build/results?buildId=1481861
