### ISSUE TITLE
Publishing pipeline failing with "error : DLL <name> for portable PDB not found

### ISSUE THREAD

**Issue by ghost** [dotnet/arcade#8033]
- [X] This issue is blocking 
This error is causing publishing failures across many repositories

- [ ] This issue is causing unreasonable pain

Installer: https://dev.azure.com/dnceng/internal/_build/results?buildId=1417830&view=results
EFcore: https://dev.azure.com/dnceng/internal/_build/results?buildId=1417617&view=results
Runtime: https://dev.azure.com/dnceng/internal/_build/results?buildId=1417358&view=results
ASP.Net: https://dev.azure.com/dnceng/internal/_build/results?buildId=1417270&view=results

**Comment by riarenas** [comment]
This is causing another type of failure in aspnetcore's publishing:

https://dev.azure.com/dnceng/internal/_build/results?buildId=1417315&view=logs&j=ba23343f-f710-5af9-782d-5bd26b102304&t=6e277ba4-1c1e-552d-b96f-db0aeb4be20a

```
error : PDB0021: Document name doesn't match any pattern in Source Link: 'd:\a\_work\1\s\src\Azure\AzureAD\Authentication.AzureADB2C.UI\src\Areas\AzureADB2C\Pages\_ViewStart.cshtml
```

which looks to be the same issue as https://github.com/dotnet/arcade/issues/7388. I'm going to roll back the portable PDB change. Looks like the approach of converting everything to portable won't work right now until we figure out all the issues.

This was unfortunately hidden for a while because of the bug where we stopped publishing symbols altogether.
