### ISSUE TITLE
Support dependency flow of multiple versions of the same dependency

### ISSUE THREAD

**Issue by jander-msft** [dotnet/arcade#8230]
- [ ] This issue is blocking
- [x] This issue is causing unreasonable pain

The dotnet-monitor tool (https://github.com/dotnet/dotnet-monitor) ships as a tool package with multiple TFMs within the package (the 6.0.X release ships both a netcoreapp3.1 TFM and a net6.0 TFM). There are a few dependencies of the net6.0 TFM that are held back to the netcoreapp3.1 version since that is the least common denominator and those netcoreapp3.1 dependencies _happen_ to work while running in .NET 6. We want to be able to split that up so that the netcoreapp3.1 build references the netcoreapp3.1 versions and the net6.0 build references the net6.0 versions for better correctness and to better enable future scenarios (e.g. trimming and crossgen2). This is technically doable by just conditionally including a PackageReference for each version depending on the build TFM.

However, we want to be able to use Maestro to flow updates of these dependencies from their respective channels. But dependency flow only allows for tracking one version per named dependency. At best as of now, we can have only one version (the net6.0 version) updated by dependency flow and then we'd have to manually check if the other version (the netcoreapp3.1 version) has a newer servicing version and manually maintain the darc feeds for that version; this will likely quickly get out of hand as we try to continually chase the latest version manually.

**Example**
The dotnet-monitor tool has a dependency on the Microsoft.AspNetCore.Authentication.JwtBearer package. We would like to make changes so that:
- the netcoreapp3.1 build takes a dependency on the ASP.NET Core 3.1 version (which is currently 3.1.21)
- the net6.0 build takes a dependency on the ASP.NET 6.0 version (which is currently 6.0.0)
- have Maestro update those versions independently as their respective sources produce new versions.

**Comment by riarenas** [comment]
The way we handle things right now is by branching, but I understand that's not desirable here as the same version of the tool needs both dependencies at the same time?

@mmitche FYI and in case you have any thoughts. We could add something to the dependency xml to indicate on which channel you want to look at for specific dependencies, but it would be a big change.

**Comment by mmitche** [comment]
The right answer here is to use packages where the dependency names vary across the releases. The VS.Redist packages, which map to the runtimes, have the major version number of their respect release in them. E.g. `VS.Redist.Common.AspNetCore.SharedFramework.x64.6.0`

**Comment by jander-msft** [comment]
> The way we handle things right now is by branching, but I understand that's not desirable here as the same version of the tool needs both dependencies at the same time?

Correct, both versions have to be available at the same time since both TFMs are built at the same time and packaged into a single tool package.

**Comment by mmitche** [comment]
FYI depending on multiple releases at the same time is a little dicey. Your build ends up bound by whichever release finishes its build "last". We specifically avoid this kind of inter-release dependency in the product because it creates a highly complex build graph. This is less the case here because your graph is small, but it's something to think about.

**Comment by jander-msft** [comment]
> The right answer here is to use packages where the dependency names vary across the releases. The VS.Redist packages, which map to the runtimes, have the major version number of their respect release in them. E.g. `VS.Redist.Common.AspNetCore.SharedFramework.x64.6.0`

Aren't the dependency names solely based on the file names (with some mangling e.g. to replace dashes with dots)? Also, I don't think that either runtime or aspentcore are going to create unused packages for the sake of appending `3.1` or `6.0` (or `7.0`) just for our need.

Wouldn't this be solvable in the Version.Details.xml file by adding (1) channel/branch information to a dependency, and (2) allowing aliasing of a dependency to a different name? All of which would be completely opt-in.

**Comment by jander-msft** [comment]
> FYI depending on multiple releases at the same time is a little dicey. Your build ends up bound by whichever release finishes its build "last". We specifically avoid this kind of inter-release dependency in the product because it creates a highly complex build graph. This is less the case here because your graph is small, but it's something to think about.

I don't think we can avoid that without splitting the repo into two repos, one for building the dotnet-monitor version for each TFM and then another repo that has a dependency on that one for just packing them together as a tool package. That's very unnatural given that the SDK provides for building multiple TFMs at the same time and packaging them together in one tool package (note that a tool package is different than the typical NuGet library package built by runtime/aspnetcore/etc).

**Comment by jander-msft** [comment]
> @jander-msft Aren't you just depending on the ref pack version from each release? Those don't shift very often.

No, we are depending on the actual package themselves. Tool packages pack their dependencies within their own package instead of just adding a reference to the nuspec file (which is what a library package does). Getting the exact version with the exact package and binaries is absolutely necessary.

**Comment by jander-msft** [comment]
For what you are suggesting to work, we would need something like `Microsoft.AspNetCore.Authentication.JwtBearer.3.1` with a version of `3.1.21`, not `3.1.21-servicing.#####`.

**Comment by jander-msft** [comment]
> @jander-msft Aren't you just depending on the ref pack version from each release? Those don't shift very often.

It's also my understanding that library packages produced from runtime/aspnetcore/etc can rev their patch version independently, so using the ref pack version of the build would not necessarily correspond with the individual library versions.

**Comment by mmitche** [comment]
Alright, if these are OOB packages that you depend on (not just the runtime packs), then it's not practical to produce sentinel versions for each one.

How often are the packages that you're depending on revving? Every month? How practical is it to update these manually?

We **cannot** introduce subscription information into the V.D.xml file. So support would look something like:
- The V.D.xml file would get some support so that the "name" of a dependency includes the Major.Minor of the dependency's version, rather than just the name itself, perhaps with an attribute. For example: Name="Foo" MajorMinor="3.1"
- Those new names would need to map onto appropriately named properties in Versions.props
- The dependency update process would need to be changed to process these new properties across the various update scenarios.

This is definitely not a trivially simple change and I think you should explore alternative options (manual updates) first before we go down this route.

Full disclosure that supporting this makes me **extremely** uncomfortable, since additional flexibility around dependency flow has historically led to increasing complexity in our build process (more dependency flow), to the point which the number of people who understand it can be counted on one hand, maybe with only a couple of fingers. We do manual updates of cross-release implicit package versions in the SDK for this very reason.

For instance, this is what dependency flow looks like for the .NET 7 SDK:

![image](https://user-images.githubusercontent.com/8725170/144102056-4c80de49-668c-4b7c-974e-e98b87904479.png)

**Comment by mmitche** [comment]
> I anticipate that we'll have to do this manually for the 6.0.X releases since I would guess that this probably wouldn't be backported to Arcade 6.0.

This isn't arcade specific (arcade doesn't know about dependency flow). The functionality is purely on the Maestro side.

**Comment by jander-msft** [comment]
Another scenario where this would be useful is for the repos that add multiple runtime and aspnetcore versions to their global.json file. Everytime there is a servicing release, we have to wait until the bits go out the door before updating the runtime and aspnetcore versions for non-latest versions (e.g. 3.1 and 5.0, and 6.0 once we add 7.0) if we want to test our features on the latest runtimes. This is currently a manual process every month. We do this in the dotnet-monitor repo: https://github.com/dotnet/dotnet-monitor/blob/main/global.json

Dependency flow _could_ work for this because we can use the version properties such as `VSRedistCommonAspNetCoreSharedFrameworkx6431Version`, `VSRedistCommonAspNetCoreSharedFrameworkx6450Version`, `VSRedistCommonAspNetCoreSharedFrameworkx6460Version`, etc. However, this usage is largely blocked if Version.Details.xml has a named dependency that is shared among multiple channels and you end up with the "last dependency update wins" problem.

**Comment by markwilkie** [comment]
Thoughts on an alternative approach @jander-msft ?  Given the amount of work this feature is, our current commitments, and the added complexity, it's hard to see this work actually getting done.

**Comment by jander-msft** [comment]
> Thoughts on an alternative approach @jander-msft ? Given the amount of work this feature is, our current commitments, and the added complexity, it's hard to see this work actually getting done.

The only approaches that I understand so far are:
1. Maestro adds support for this (which sounds unlikely). I would personally volunteer time to get this to work but if you say that it's too complex, too hard to maintain, etc, then...
1. We manually do this by hand (good luck to the person who has to manually figure out the darc-pub and darc-int feeds and keep updating them as new version of the dependencies come out). I fear this is going to lead to a situation where we miss an update and accidentally ship bits from an intermediate build. Then...
1. We automate on our end to effectively replicate Maestro for non-latest versions. We'd probably use darc, AzDO pipelines, and a pile of scripts to get it done. But this seems it would be wasted effort, and I'm not sure this would looked highly upon for doing a one-off system or would get by-off to do it, and really should be incorporated into (1).

I like @mmitche idea of specifying an optional version affix in V.D.xml file for each dependency that cares to do this, such that whatever system scans that file does something like:
1. Find dependencies based on name.
2. For each matching dependency, if affix is specified, match (starts with comparison?) version affix. If match is found, update that dependency only and update the Versions.props property named <name><affix> with the new value. Otherwise, do the existing behavior.

Also update the `darc verify` command to:
- Validate that dependencies in V.D.xml with affixes have their corresponding named property Versions.props.
- (Maybe) validate the dependencies with the same name in V.D.xml are disambiguated such that zero or one does not have the affix and each one that does have the affix has a unique affix.

This makes it completely optional to opt-in and preserves the existing behavior for anyone not using this affix notion. Maybe I'm over-simplifying it, but that doesn't sound that difficult to do.

**Comment by mmitche** [comment]
I support adding this feature (though it may be complicated to add) to Maestro as long as it is **NEVER** used for any repo that ships as part of the main product. Keep in mind @jander-msft that you will end up bound by the whims of commits and dependency flow from dozens and dozens of repos.

Most of the concern here is not about whether this kind of flow is technically possible. It's the added complexity around a vastly expanded dependency graph. The machinery today can mechanically understand that dependency graph. It cannot tell you whether it is correct, or complete, or what it will look like tomorrow.

You'll need to monitor Tactics communications to understand the current state of the 3.1, 5.0 and 6.0 builds and whether the current set of assets are the completed ones or whether there are additional builds coming. 'Extra' commits (they happen) may rev your bits without warning. You'll also most likely need to understand coherency state for the 3.1 runtimes, since you want to make sure the bits you depend on are coherent. Also of note that you'll be intaking **non-signed** 6.0 packages and thus will need to either sign the binaries yourself (probably preferable?) or somehow get onto post-build signing, which is currently designed for the installer and runtime repos.

**High level question:**

Is sim-shipping with the servicing releases a requirement? IMO it is **vastly** simpler to simply ship same day as patch Tuesday and build against newly publicly released bits when they are available.

**Comment by markwilkie** [comment]
Closing this for now given that it seems to have lost momentum.  However, don't hesitate to reopen as appropriate.
