### ISSUE TITLE
Make XHarness tests run in parallel with other arcade testing

### ISSUE THREAD

**Issue by adiaaida** [dotnet/arcade#8252]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

Today, XHarness tests run after all the regular arcade tests finish. Frequently, the xharness tests timeout, despite the regular tests completing successfully, and you have to rerun the entire job (aka, all of the arcade tests + all the xharness tests). Xharness tests should be broken out into a separate job per configuration, so that when they need to be rerun, we don't have to rerun ALL of the tests (and possibly time out again).

**Comment by premun** [comment]
Oh, it looks like that when runtime is running the full BCL suite on the 10 iPhones we have and Arcade runs at the same time, they pile up on the few devices. I never noticed because runtime-staging rolling build only runs 2x a day and it's out of my hours.

Thanks for this @adiaaida. Can we now maybe prioritize #7979?
