### ISSUE TITLE
[AsmDiff] Unexpectedly adding a destructor

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/arcade#8517]
Running the tool with these arguments:

```
Microsoft.DotNet.AsmDiff.exe -r -a -c -itc -cfn -adm -hbm -da  ... <and all the file arguments, unimportant here>
```

The tool was executed to compare the GA version of 6.0 and the 7.0 Preview1 version.

The `System.Threading.PeriodicTimer.~PeriodicTimer()` destructor showed up unexpectedly as newly added in 7.0, even though it already existed in 6.0.

Comment: https://github.com/dotnet/core/pull/7211/files#r810084435

**Comment by riarenas** [comment]
I believe ASMDiff is part of the things maintained by the runtime folks. @ericstj I applied the fancy new label

**Comment by ericstj** [comment]
It may have existed, but it wasn't in the reference assembly: https://github.com/dotnet/runtime/blob/release/6.0/src/libraries/System.Runtime/ref/System.Runtime.cs

@jkotas added that here: https://github.com/dotnet/runtime/commit/d094a34a4d555d3aef434bc87ad3fefe15d83e08#diff-cec8e6f471b4193246bdc0107b0dd7cbe131fb7fd189b288b37269c333d1171dR14765

The tool is identifying a real difference in the references.  That said, the existence of a finalizer in a reference assembly isn't something that folks can actually bind to, it's just for their own informational purposes so that they need not implement it themselves in a derived class.  Since `PeriodicTimer` is sealed it's not all that interesting.
