### ISSUE TITLE
'The specified blob already exists' errors thrown retrying uploading workitem payloads from Helix Arcade SDK

### ISSUE THREAD

**Issue by danmoseley** [dotnet/arcade#8622]
### Build

https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=1666323

### Build leg reported

Libraries Test Run checked coreclr OSX x64 Debug / Send to Helix

### Error message

The engineering services team will fill in the error message using [known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section).

```json
{
   "errorMessage" : "RequestFailedException: The specified blob already exists."
}
```
https://github.com/dotnet/runtime/pull/66703/checks?check_run_id=5570022819

**Comment by MattGal** [comment]
@ilyas1974 asked me to look and comment here.  

### Notes:

- The exception logged comes from our code in https://github.com/dotnet/arcade/blob/main/src/Microsoft.DotNet.Helix/JobSender/StorageHelpers/ContainerBase.cs#L21
- We use the overload of BlobClient.UploadAsync that throws if the file is already present
- We use a generic retry wrapper in the Helix Arcade SDK that retries in failure cases; we retried

### How I'd fix it (in order of decreasing preference)
- Permanently switch to the overwrite-allowed version of this API (https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/src/BlobClient.cs#L622) and just let the overwrite happen
- Catch the HTTP 409, download the blob that 409ed, diff the bytes (less preferable ; lower perf than just re-uploading the file)
- Explore expanding the retry behavior in the Helix Arcade SDK's usage of the storage SDK and remove our retries (unfavorable mostly because we get very few "real" tries at bad connections and it's easy to screw up.
- Catch the http 409, do nothing (pray that the first retry succeeded)

bullet 1 is cheap, a one-liner change, and would permanently prevent this issue.  (We may have to port it to other release branches if the problem is common)

**Comment by ChadNedzlek** [comment]
I'd be fine with just taking the 409 and moving on (without diffing). Maybe with a warning in the log.  The odds of it being some other random file is vanishingly small, since it's a new storage container made just for the job.  I'd rather not have overwrite turned on, because it will allow problems to appear that will be difficult/impossible to diagnose if things end up writing to the same blob twice for some _other_ reason.

**Comment by epananth** [comment]
Putting this back into backlog. I couldn't get to this
