### ISSUE TITLE
Consider renaming Check Run for Build Analysis

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#8625]
Per feedback from @danmoseley:

> You might consider renaming the header here from ".NET Helix" to "## Results Analysis ##"  or something. .NET Helix doesn't mean anything to our community, so they won't expect to find analysis underneath it. 
 
![image](https://user-images.githubusercontent.com/47990216/158640156-e901ceb8-d589-4c1e-9158-e3ed19e4ff4b.png)

> I think you'd get more usage. It's also inconsistent with the display in Github

![image](https://user-images.githubusercontent.com/47990216/158640232-7f78eb9a-0f9a-4746-9304-6203a468f34a.png)

----

We'll have to see if this is feasible to change, since I think that the name of the check is directly tied to the app, which is used for things besides Build Analysis (such as the auth mechanism that allows for folks to download logs from Helix)

**Comment by missymessa** [comment]
Thought: Is there any reason we shouldn't split the Build Analysis functionality out from the main .NET Helix app into another app?

**Comment by ChadNedzlek** [comment]
Just means more apps to manage, but that's not really that big of a deal.  It would also mean permissions could make more sense.  Right now this thing has a LOT of permissions and is installed in a lot of places because it's doing so much.  It's really 3 things:
* The auth layer for helix.dot.net
* The build analysis stuff
* The project/epic management stuff

We should split those all out.  And it might be something else too.

**Comment by missymessa** [comment]
Moving this to M5 per our team conversation yesterday to extract this into three different apps that Chad defined above.

**Comment by missymessa** [comment]
This work was broken up by other issues. I'm going to close this issue in favor of https://github.com/dotnet/arcade/issues/9221 which is specific for the app we need for Build Analysis/DevWF work.
