### ISSUE TITLE
Helix test runs fail with: The response contained an invalid status code 500 Internal Server Error

### ISSUE THREAD

**Issue by jkotas** [dotnet/arcade#8670]
### Build

https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=1676838

### Build leg reported

Mono llvmfullaot Pri0 Runtime Tests Run  Linux x64 release / Send tests to Helix (Unix)

### Action required for the engineering services team

To triage this issue (First Responder / @dotnet/dnceng):
- [ ] Open the failing build above and investigate
- [ ] Add a comment explaining your findings 

If this is an issue that is causing build breaks across multiple builds and would get benefit from being listed on the [build analysis check](https://github.com/dotnet/arcade/blob/174acbcafeba3ae339c1935ec48812514ee09837/Documentation/Projects/Build%20Analysis/Introduction.md), follow the next steps:
1. Add the label "Known Build Error"
2. Edit this issue and add an error string in the Json below that can help us match this issue with future build breaks. You should use the [known issues documentation](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-message-section)

 ```json
 {
    "errorMessage" : ""
 }
 ```

**Comment by dkurepa** [comment]
Hello, we are looking into this issue

**Comment by MattGal** [comment]
This was caused by transient DNS outage from the Helix API talking to the Azure storage resource provider ("No such host is known.")

Here's an [App Insights query showing the exception](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fdotnet-eng-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA3XNsQrCMBSF4d2nuHSpgtU01QrFCm46KCJOikhMrhpJm5LcYgcfXkUQHVwO%252FMPHwUZiRdqWvnWH2wUdAukCPYmiggkoQfjqNmecRyyJeLJhcRYPM5b2WJryARtsOyBKBV9u%252FNeNftznUhpbq8PaGlyKAiHPITiJo9My68%252FQ6Oa909U8eJLK2StKAlsTugV6L87YhV2okIQ2Ptw%252FAJb2nQTUAAAA)

@dkurepa we can pretty safely add more retry logic in the /api/storage path, by tweaking the settings that are already used.

**Comment by alexperovich** [comment]
I am fairly certain there is already retry logic built in to this code path. I will check though.

**Comment by alexperovich** [comment]
Yep, there is already lots of retry logic built into this code path, adding more would just add more strain to the system. If this starts happening a significant amount then we can explore other options.
