### ISSUE TITLE
Issue with build timing out before Helix completes

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#8826]
From CI Council today, can someone on FR please investigate why there is a time delta between when [Pipelines - Run 20220406.24 logs (azure.com)](https://dev.azure.com/dnceng/public/_build/results?buildId=1703376&view=logs&j=3f6d4e0f-1b71-56b5-361e-d95b6e6da15a&t=e4ee6667-9b0a-5a6e-4e24-bcba939f2af2) was submitted and when https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-aspnetcore-refs-heads-main-48f55fce9afc40ef8b/Microsoft.AspNetCore.JsonPatch.Tests--net7.0/1/console.06826cd9.log?sv=2019-07-07&se=2022-04-26T18%3A55%3A24Z&sr=c&sp=rl&sig=oMatyzJCtPgxveBgmj%2FApYXU0I7ZLDC6SjueYCLwnKQ%3D started? 

/cc: @dougbu

**Comment by ilyas1974** [comment]
@alexperovich, is this something you can look at? Doug should be able to answer any questions you may have.

**Comment by alexperovich** [comment]
I can check things.

**Comment by alexperovich** [comment]
This looks like a hung work item, I'm looking deeper, but nothing else looks weird. Those jobs haven't even registered as "completed" because a work item is still not reported finished. There was a spike in data migration queue depth around that time, but not data was lost.

**Comment by alexperovich** [comment]
well, this is odd. The machines in that queue don't appear to exist. There are no logs for them.

**Comment by alexperovich** [comment]
I think I've found the cause. There was an event hub hiccup right around the time that these work items messages were being processed, so we lost the completion events. Logs here: [Logs](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fdotnet-eng-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA3WOsQrCMBiEd5%252Fi36qgbVJt0UKdHUREnVwkTU8MpI0mUVvw4a1L0cHp4O477u61MjV5KyTcmNBIXH3nuMGLnhdYkNTmXp52RmMjKlCeU3AWhVUyi1bQqon2N721pqs7Y4O%252B5lUF50V1pQL%252BCdQ09KYUHp9gGMQsjidsNmHpgS8ynmSch%252FM5Y9MkPQajMPzPxuyXHfWTDg9Y5dt1p5qWxLvE2BKWivbrTwkn3yShQmz2AAAA)

I don't yet know the root cause

**Comment by alexperovich** [comment]
We don't have enough logs to determine the complete cause, but logs have been added. The next time this happens we will know more. This was a hiccup in our event hub processing that caused us to drop messages.
