### ISSUE TITLE
Move Helix Job Sender into the Arcade Core SDK

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#902]
* [ ] Move src etc to arcade/src/Microsoft.DotNet.Arcade.Sdk/
* [ ] Update/Add [docs](https://github.com/dotnet/arcade/tree/master/Documentation/CorePackages) (don’t forget ‘packagesroadmap’)

**Comment by alexperovich** [comment]
Why do we need to do this?

**Comment by jonfortescue** [comment]
@markwilkie said it's core functionality

**Comment by jonfortescue** [comment]
what are the main barriers you see here? What are the obstacles to shipping the job sender as part of the main arcade sdk package?

**Comment by alexperovich** [comment]
The Helix JobSender package should never be included as source code in the arcade sdk. Its a C# package. If functionality in it is needed then a PackageReference should be used.

The Helix Sdk should not be included because it is fundamentally different than the Arcade Sdk. The arcade sdk is designed to augment Microsoft.NET.Sdk with needed functionality to build C# and VB projects. The helix sdk essentially creates a new "helix" project type that references the helix sdk in the Project element and doesn't use the Microsoft.NET.Sdk at all.

Another reason is that I should be able to send a job to helix, using the arcade packages, without touching the arcade sdk. Combining them would make arcade sdk a requirement for sending stuff to helix.

We should have a conversation about what the actual requirements are that caused this issue.

**Comment by jonfortescue** [comment]
cc / @markwilkie @jcagme thoughts?

**Comment by jcagme** [comment]
I think Alex has good points. In my case I, yet, don't have a lot of context around the JobSender package and what is the intent in the .Net Core 3 realm so it would be good to chat and define where should it live and how does it need to be delivered.

**Comment by markwilkie** [comment]
Yup - I'm more than happy to chat.  The main goal is that Arcade (our shared toolset mechanism....hand waving here....grin) provide a mechanism for product owners to send test jobs to Helix easily.  Given that our guidance is to use Helix when targeting most of our VM's in the test matrix - it's core functionality that will be used by almost all - if not all- of our tier 1 repos.  Thus....it's part of the "Arcade SDK" - meaning - we (enceng) own making sure that it always works, and an easily update the client side across all repos.

**Comment by jonfortescue** [comment]
@markwilkie do you want me to put a short meeting on the calendar some time this week to hash this out?

**Comment by markwilkie** [comment]
That'd be great - thanks.

**Comment by markwilkie** [comment]
Now tracked as #923
