### ISSUE TITLE
First Responder Scheduler App

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#9023]
(Proposed internship project)

A scheduler app would help the First Responder lead and team to be more efficient with scheduling the team for their FR stints and trade time on the schedule when conflicts arise. This process is currently performed manually, so an automated scheduler and self-serve process for trading time would be handy to have. 

**Requirements**

- Speak to the First Responder lead to understand current scheduling process and challenges with this process
- Speak to the team regarding process for trading FR stints
- Implement process/services that allows for this work to be programmatically

**Suggested Capabilities**

This is just a suggestion for capabilities that I've been thinking of. The outcome of this project is wholly dependent on the data gathered from the team. 

- FR lead is able to order folks and the program should provide a schedule based on that order. 
- Folks going onto FR should get an email reminder (perhaps automate the FR stand up meeting invites that are sent out) regarding their FR stint sent out in advance. 
- Folks on FR should be able to trade days with others, or sub in for someone (without trading). 

(P.S. I feel like I wrote up this issue elsewhere, so if you see it, feel free to link it to this one).

**Comment by riarenas** [comment]
My sense is that while this sounds like a good intern project that would allow an intern to learn and interact with Microsoft technologies, I really don't want us to own and maintain another website / app, and any issues with the current process should be thought of from the process standpoint instead of building automation around it.

Perhaps we can rely on some of the features from existing infrastructure designed around on-call rotations, even if we don't adopt the process of "on call" entirely.

**Comment by ulisesh** [comment]
We can do a PowerApp for this 😆

**Comment by markwilkie** [comment]
We might should use ICM for this

**Comment by missymessa** [comment]
We've been using IcM for this work, so this epic is probably not needed anymore.
