### ISSUE TITLE
Improve telemetry output for matrix of truth

### ISSUE THREAD

**Issue by lpatalas** [dotnet/arcade#9032]
The pipeline output looks currently like this:

```
{
  "Id": 331,
  "Name": "aspnetcore-quarantined-tests",
  "Repository": "dotnet/aspnetcore",
  "Branch": "/main"
},
```

We should:
- Add number of times it was executed
- Add full URL to the definition based on project (internal/public) and ID
- Fix `Branch` property so that it does not start with slash
- For `RecentlyRunDockerImages` element we should use full docker image name with prefix, e.g. `mcr.microsoft.com/dotnet-buildtools/prereqs:...`

**Comment by dkurepa** [comment]
PR Link: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/22488
We are unable to do the first two points for the following reasons:
1) Currently, it is impossible to get the number of times a pipeline was executed on a OneES and MicrosoftHosted execution environments. This is because we find out what machine the job was done on after log scraping, which is done after summarization. The solution to this would be to move the LogScraping to arcade-services and extend the Kusto table with this information (image that the build was performed on).
2) We originally thought that we had this data available in Kusto. However, after research, we found out that not all of our helix jobs are done as a part of dnceng, there are other organizations that also use helix, and we are unable to get their names from the current telemetry.

**Comment by dkurepa** [comment]
This PR has been merged. We will investigate moving log scraping in this issue: https://github.com/dotnet/arcade/issues/9199
