### ISSUE TITLE
Investigate abandoned messages and reenable alert 

### ISSUE THREAD

**Issue by ulisesh** [dotnet/arcade#9044]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

I paused abandoned messages alert because we don't have the resource to investigate the problem and we believe it is caused by long messages. We need to confirm this and make the alert better

https://github.com/dotnet/arcade/issues/8799

**Comment by AlitzelMendez** [comment]
There are still some abandoned message and so far all of them seems to be related wiht: https://github.com/dotnet/arcade/issues/10807

**Comment by missymessa** [comment]
This is for the prod alert which is still disabled. Should make sure it's active and working properly before we complete the epic.

**Comment by AlitzelMendez** [comment]
Looks like this was finally fixed in: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/commit/22b3654f6b48ead3963313dc3cbb398aaed4f31e?refName=refs/heads/rollout/2023-01-11&tab=details

No messages abandoned since that rollout:
<img width="1544" alt="image" src="https://user-images.githubusercontent.com/6895254/214125048-c0932f95-6ef6-4183-972a-1212c11f66e0.png">



I will activate this again.  Do we still one that this gets triggered every time that a message gets dropped?
or for FR are we targeting to something more significant that one message? maybe X number of messages per hour?

**Comment by ulisesh** [comment]
In my opinion, the system seems to be stable enough to set the alert to get triggered every time a message gets dropped

**Comment by AlitzelMendez** [comment]
Reopening as I saw another issue today. I will investigate it and take a decision about the alert

**Comment by AlitzelMendez** [comment]
[Logs & Traces](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2F68672ab8-de0c-40f1-8d1b-ffb20bd62c0f%2FresourceGroups%2Fdotnet-eng-cluster%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fdotnet-eng/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAz2OQQrCQAxF954i9ADtvuBCUXGlUg8g6TTVkcxEJhlU8PBOFV3%252B%252FJfHt4SOdPaC%252B4USgctqElY%252BUFQvUWvHkodTJ0w7DATzOVQj9sm7ttkS%252B0ezzJ6HjjSzLSLyU70ekhSnSqr%252B3lAynotfoqGPCtUGPdMAJnD74j%252BmheNTjUK9y8wdjeU9Olo%252FHN2sTGph31%252FJGaRfBVEMlGxyYYRiN5zOMk5RPnRdvQE6gRaw6QAAAA%253D%253D/timespan/P2D)

This is an issue happening in very old pull request (two months old or so) in where a build is retried and the BuildCacheProvider tries to get the related builds from the cache and they have a different json contract and this fails.

This should stop happening, eventually, soon... closing
