### ISSUE TITLE
Verify if we're able to access our SF portals while on corpnet

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#9049]
Can we access our SF portals (either through the UI or using powershell scripts) while on corpnet? Document outcome from this investigation for future knowledge.

**Comment by garath** [comment]
@alexperovich This came up during the retrospective this week. Do you know how access will work after your deployment changes are complete?

**Comment by alexperovich** [comment]
It works exactly the same, just only from corpnet.

**Comment by premun** [comment]
Are the changes done? Should we test from Prague corpnet? Is the goal to also be able to access it from a VPN?

**Comment by garath** [comment]
> Are the changes done? Should we test from Prague corpnet? 

Yes, these changes are done. Test away! 

> Is the goal to also be able to access it from a VPN?

No, just corpnet.

**Comment by premun** [comment]
I think we might have a problem with this. DevDiv in Microsoft Prague was moved to a leased office which doesn't have corpnet. We just tried and it doesn't work with VPN and it doesn't work with the wired connection here because it's not a MSFT network.

It does work from the other Prague office though (I had a former colleague try to open this and it did ask him about the cert).

Also not sure how does this work for you guys in US? Does FR need to be in the office every day in case of problems?

**Comment by alexperovich** [comment]
I remote desktop to my machine in the team room when I WFH, so I can access the SF portal from there.

**Comment by alexperovich** [comment]
I'm unsure if we can allow the VPN through as well, but that might also have a service tag. SAWs should also work from anywhere I think.

**Comment by riarenas** [comment]
>SAWs should also work from anywhere I think.

I was working on my SAW, so I tried it real quick and it worked.

**Comment by garath** [comment]
Seems like this has found a solution, so closing. 

If anyone wants to explore the details more (and please do feel free!), open an issue in Azure DevOps for the discussion.
