### ISSUE TITLE
Support Clean target in common build scripts

### ISSUE THREAD

**Issue by weshaggard** [dotnet/arcade#906]
Today a lot of core repo's have a clean.cmd/sh script in the root of the repo that folks like to use to get their repo into a known state. See https://github.com/dotnet/corefx/blob/master/clean.cmd as an example. 

We should support that scenario in the eng/common directory. We should either have a clean script explicitly or have the build.cmd/sh scripts support a clean option.

**Comment by ericstj** [comment]
Just hit this myself.  I tried deleting artifacts and it wasn't sufficient to clean the repo 😕 .  `git clean -fxd .` worked but that's a pretty big hammer.

**Comment by tmat** [comment]
@ericstj Deleting `artifacts` should be sufficient. Only tools (such as `dotnet`) should be restored outside of `artifacts` and one usually doesn't want to delete and redownload them.

**Comment by ericstj** [comment]
For some reason with a recent change I was getting an error even after deleting targets around duplicate definitions of Assembly-level attributes for many of the projects.  I know this is bizarre but it was consistently repro-ing.  Unfortunately it is no longer doing it after I did a git clean -fxd so I can't repro any more.  I might have had the sln open in VS at the time, so I imagine that could have been caused by someone changing the convention for the generated file and VS doing a design time build after I deleted artifacts 🤷‍♂️ .  If I ever hit it again I'll dig deeper before using the hammer.

**Comment by jcagme** [comment]
@ericstj do you want to keep this around or we should open a new one if this resurfaces?

**Comment by tmat** [comment]
Let's keep this open. We should add Clean target but it's not a pri for now.

**Comment by ViktorHofer** [comment]
@tmat I attempted to implement the clean target in Build.proj but that has the downside of needing the toolset to be restored. What about implementing clean in the build scripts instead? I guess deleting the artifacts dir would be the desired functionality. What I'm not sure about is how to get the path to the artifacts dir without hardcoding it.

**Comment by tmat** [comment]
@ViktorHofer I don't think this is really necessary. All build outputs go to `artifacts` directory, so `rm -rf artifacts` is your clean command. If you want to nuke `.dotnet` and `.tools` directories you can do `git clean -xfd`.

**Comment by ViktorHofer** [comment]
In corefx we definitely want a clean action, regardless of how many commands are executed behind the scenes. I would be surprised if corefx is the only one interested in this. If you don't think it fits into arcade we can implement it in corefx.

**Comment by tmat** [comment]
@ViktorHofer Can you explain why do you "definitely want a clean action"?

**Comment by ViktorHofer** [comment]
We do have clean scripts in our repository which handle multiple scenarios. Since we moved to arcade much of that functionality isn't needed anymore but we still want to offer a complete developer workflow. I'm really proud of our new CLI expierence in corefx where you can now chain actions all with just the root script. We had build, test, clean, sync, etc. in the past. 

To provide some similarity with what we had and still make it easy to document our developer workflow without the need to differentiate between OS it would be great to have a clean action. For now we integrated the clean switch ourselves in corefx but it would be great if we could streamline that into arcade.

**Comment by tmat** [comment]
Makes sense. I guess we can add `-clean` to `common/build.sh|ps1` that runs `rm -rf $arcade_dir`. You probably don't want to nuke `.dotnet` and `.tools` directories when running `build -clean`, since then you could as well just do `git clean -xfd`, so there would not be much value in providing another way to do `git clean`.
