### ISSUE TITLE
SigningValidation is failing if repo has 7.0.100-preview.4+ in `global.json`

### ISSUE THREAD

**Issue by DavidKarlas** [dotnet/arcade#9161]
- [x] This issue is blocking
- [ ] This issue is causing unreasonable pain

If repo has global.json with SDK version that includes https://github.com/dotnet/sdk/pull/23302 for example `7.0.100-preview.4.22178.9`. It fails to pass `SigningValidation` with [Version 7.0.100-preview.4.22178.9 of the .NET SDK requires at least version 17.0.0 of MSBuild. The current available version of MSBuild is 16.10.0.26302. Change the .NET SDK specified in global.json to an older version that requires the MSBuild version currently available](https://dev.azure.com/dnceng/internal/_build/results?buildId=1730800&view=logs&j=b11b921d-8982-5bb3-754b-b114d42fd804&t=cdcedd1f-8008-523f-9da1-cc35fbfef9a3) error.

Reason for that is because [SigningValidation](https://github.com/dotnet/arcade/blob/77f48b94560439719762cbfe4e8e4730015ecfb1/eng/common/templates/post-build/post-build.yml#L185) step calls  [sdk-task.ps1](https://github.com/dotnet/arcade/blob/977c4612a668c06232bee5acf3e9162dda31fe24/eng/common/sdk-task.ps1#L67) which has hardcoded `16.10.0-preview2` version of [RoslynTools.MSBuild](https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-eng/NuGet/RoslynTools.MSBuild/16.10.0-preview2/overview).

**Comment by riarenas** [comment]
Added to FR but a couple of notes through a quick inspection

* It's not clear to me where templating is trying to use preview 4 for their builds. Their global.json is set to preview 3: https://github.com/dotnet/templating/blob/main/global.json#L3
* It's not surprising we haven't seen this before because Arcade only uses publicly released previews, so we're still using preview 3. 
* There looks to be a bug in arcade where we are not running the signing validation step and that should be fixed so that we can validate this: https://dev.azure.com/dnceng/internal/_build/results?buildId=1732925&view=logs&s=3df7d716-4c9c-5c26-9f45-11f62216640d&j=32659897-e0ce-514a-b22d-a365af367f55

**Comment by DavidKarlas** [comment]
I merged PR few hours ago to downgrade so we could insert into sdk repo: https://github.com/dotnet/templating/pull/4631
But had to disable few tests...

**Comment by riarenas** [comment]
Ah I see. 

The expectation with Arcade is that we control and support the minimum version of the SDK that a repo should use. Repos are welcome and encouraged to scout newer previews, but Arcade can't change its SDK to unreleased versions so the support in some places is bound to hit problems. Signing validation has usually been one of such places due to the reliance on the xcopy msbuild.

**Comment by MattGal** [comment]
I'm somewhat unfamiliar in this space, but I created a 17.1.0 xcopy msbuild and https://github.com/dotnet/arcade/pull/9170 to consume it (and see if anything blows up on PR validation).  We can discuss whether this is "the right fix" on the PR / next week.

**Comment by MattGal** [comment]
@DavidKarlas can you please help validate the changes I've made?  I generated the 17.1.0 xcopy-msbuild package and merged an arcade update that makes this default, but I'm unsure how best to prove this unblocks your scenarios.
