### ISSUE TITLE
Update package versions in the SDK

### ISSUE THREAD

**Issue by jcagme** [dotnet/arcade#917]
Today, taking a dependency on a package which was just updated takes 2 builds:

1.  The build to generate a new version off of the updated package
2.  A build with an update to `DefaultVersions.props` which will generate a new version of the Arcade SDK
3. * A build with the updated SDK version so the change in 1 is tested

We should have a better way to update the versions of the packages contained in the SDK and also a good way to test/validate changes on a package before we merge, for example:

1. Sign package was updated
2. Pack and publish it to a test feed
3. Update `DefaultVersions.props` in a canary repo
4. Start a build
5. If build succeeds then we merge, fail the build if not
6. Update, in a different PR/build, version(s) just tested

**Comment by riarenas** [comment]
The current thinking for this is roughly:

1. Arcade build runs, generates new version of package in local environment
2. Darc updates the packages to use the new version in the local environment
3. Arcade builds again, if successful means the new version of the packages is good to generate.
4. If build fails, fail the build.

**Comment by jcagme** [comment]
As a follow up of 3 I would include that if things worked we would move on with the "official build" which actually publishes the packages to the feeds and inserts the assets into BAR

**Comment by riarenas** [comment]
I was able to get this to work locally  with the following process:

1. Added a `-restoreSources` option to eng\common\build.ps1 so that additional restore sources can be propagated. (all the  proj files were already expecting this param, there was just no entry point for it to get populated)
1. Added an `-updateSdk` option to eng\build.cmd to signal that we'd like to go through the process.
1. When `-updateSdk` is passed, an updateSdk.ps1 script performs the following steps:
1. runs `eng\common\build.ps1 -configuration Debug -restore -build -pack`
1. initializes darc, and runs `darc update-dependencies --packages-folder` so dependencies are updated to use the package versions generated by 4. 
1. Adds a local nuget feed pointing to the packages.
1. runs `eng\common\build.ps1 -configuration Debug -restore -build -test -sign -restoreSources <packages location>`
1. Cleans up the local nuget source and reverts the changes made locally by darc

With this process I was able to inject a bug into the signTool project, which wasn't caught by the initial build in 3, but was caught by the second build in 7.

I still need to:

1. Hook all of this up to the CI process.
2. Darc requires a maestro access token and github PAT to update the local dependencies. I need to pass those as secrets as oposed to having them hardcoded in the script.
3. Test the process in the build machines.
