### ISSUE TITLE
Move Projects board modification out of .NET Helix App into its own GitHub app

### ISSUE THREAD

**Issue by michellemcdaniel** [dotnet/arcade#9222]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

As part of https://github.com/dotnet/arcade/issues/8708 and as described in https://github.com/dotnet/arcade/issues/8554#issuecomment-1072688229, the code that updates our various projects boards (.NET Engineering Services + Known Issues) should be moved to its own GitHub app so that we can limit the access of .NET Helix.

**Comment by adiaaida** [comment]
FYI @AlitzelMendez @ulisesh.

I can take this one on, just want to let you guys know that I'm going to move all the projects board stuff, including the known issues board tracking stuff to a separate github app

**Comment by adiaaida** [comment]
I *think* this is going to require me to move the code that processes the github issues into its own project, similar to the WorkItemProcessor stuff so that it can use its own GitHubApp with the id/key. @ChadNedzlek does that sound right to you? Is there a way that two different parts/controllers of the Helix API could use two different github app id/key pairs?

**Comment by missymessa** [comment]
A lot of this code was removed because GitHub came up with a way to automatically add issues in a repo to a project board, so closing this.
