### ISSUE TITLE
Build monitor webhook failing

### ISSUE THREAD

**Issue by riarenas** [dotnet/arcade#9516]
- [X] This issue is blocking 
This blocks alerting for failed builds, especially the weekly secret synchronization, and codeql pipelines.
- [ ] This issue is causing unreasonable pain

The webhook to the dotneteng-status website has been failing since 5/25, and it was disabled by azure devops.

The logs for the service show 401s from azure devops, so I believe this is a case of an expired secret, or something that needs to be updated manually.

It also looks like the alert that is supposed to fire when the webhooks are failing too much needs to be adjusted, as it looks like there weren't enough requests in a short enough timeframe to activate the alert before the webhook got disabled.

**Comment by riarenas** [comment]
I saw that this service's vault has a duplicate PAT from the maestro key vaults, but had different expiration date metadata than the others, so the secret manager automation didn't alert us about having to rotate that secret.

However, after synchronizing the PAT with the one from the other vaults, the webhook continues to fail, so I'm not sure what else to take a look at.

**Comment by riarenas** [comment]
CC @ChadNedzlek @garath

**Comment by garath** [comment]
Summarizing the [teams conversation](https://teams.microsoft.com/l/message/19:83953de1ddd34bcaa9ebaba54cb8eba4@thread.skype/1654009938770?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=147df318-61de-4f04-8f7b-ecd328c256bb&parentMessageId=1654009938770&teamName=.NET%20Eng%20Services&channelName=General&createdTime=1654009938770) during the live event:

Secret manager does support the same secret used in two vaults. It might work, but there is no guarantee. In this case, the two secrets had different expiry dates. One was within the "needs rotation" range, which secret manager handled. The other was "no change needed". Secret manager rotated the first but did not change the second, which meant the second was now invalid. This is why dotneteng-status failed to process hooks.

Even after the secrets were brought in sync, the service still failed to authenticate. 

The code that was failing is attempting to get project information from Azure DevOps. The Rest API documentation says this requires `vso.project` and `vso.profile` permissions, which the PAT did not have. We added those but it had no effect. 

Restarting the service fixed it, presumably because it refreshed a cached secret. The configuration should be automatically refreshed every five minutes. Why did it not refresh here?

Follow-on work:

- [ ] Adjust the alert to trigger earlier. The frequency of sent hooks is too low for the window that Grafana considers. Alert more aggressively.
- [ ] Do not duplicate secrets between vaults. Create a separate Azure DevOps PAT for this service. (Also, confirm the scope need. It may only need vso.project and vso.profile.
- [ ] Understand why the service did not recover after updating the secrets and fix whatever issues are preventing secret refresh in a live service.

@riarenas, @adiaaida, anything to correct or add? 

@ilyas1974 FYI, I think this is probably FR or (since it's not blocking customers) Operations work.

**Comment by ChadNedzlek** [comment]
Everything with a secret should be IOptionsMonitor, so yes. :-)  I'm not sure how I missed this in my sweep in the long, long ago, but that would explain why rebooting it was necessary.

**Comment by adiaaida** [comment]
So as part of closing out this issue, we need to convert this code to use IOptionsMonitor

**Comment by alexperovich** [comment]
inside a controller type IOptionsSnapshot is preferred. They are scoped.
