### ISSUE TITLE
Missing .npmrc file in arcade-services 

### ISSUE THREAD

**Issue by epananth** [dotnet/arcade#9565]
- [ ] This issue is blocking 
- [x] This issue is causing unreasonable pain

**Comment by epananth** [comment]
Things to do: 

1) create a feed then make sure all the packages are in that feed 
2) create .npmrc file 
3) update credentials 
4) Update pipeline 

This is a huge change.

**Comment by adiaaida** [comment]
Talked with Epsi. We need to request exceptions for this

**Comment by adiaaida** [comment]
Ok, rewind. Once a hotfix reaches our ring in AzDO, we might actually be able to turn this on properly by setting the public upstream. We're going to make a dotnet-public-npm feed in azdo and set that in our .npmrc file. Putting in tracking until the hotfix reaches us.

**Comment by riarenas** [comment]
Is there an azdo issue or something that has more context on why we're doing this? it doesn't look very FR-y

**Comment by adiaaida** [comment]
Yeah, it's another of those security pushes. @mmitche has more info.

**Comment by mmitche** [comment]
It's ensuring that feeds are using CFS. We're blocked on public upstreams though.

**Comment by riarenas** [comment]
Ooh is the plan to also adopt that for nuget? to replace dotnet-migrate-package with a CFS upstream?

**Comment by riarenas** [comment]
> We're going to make a dotnet-public-npm feed in azdo and set that in our .npmrc file

I wonder if we can just use dotnet-public for this? Unless there's some benefit in keeping our node and nuget packages in separate feeds

**Comment by mmitche** [comment]
> > We're going to make a dotnet-public-npm feed in azdo and set that in our .npmrc file
> 
> I wonder if we can just use the existing dotnet-public feed for this? Unless there's some benefit in keeping our node and nuget packages in separate feeds

We can't (most probably). The problem is that for any repo taking stable dependency flow updates, the feeds change all the time, so you'd need to continually create new feeds, which induces fresh ingestion each time (also, ingestion can't be done in public CI). For repos that don't have any of that going on, it's possible but then we have two feed setups, We also can't use dotnet-public for the upstreams because the compliance detection logic is looking for any upstreams in a feed. If so, and multiple feeds, fail. So if you add an upstream to dotnet-public, even for NPM, we'd likely immediately start seeing failures across the board.

Really, to get out of the whole situation we have to get rid of stable dependency flow.

**Comment by adiaaida** [comment]
Right, and you can't just set an upstream to one of the public feeds. It's basically a checkbox of "enable public upstreams" so dotnet-public would get nuget.org and npm, etc.

**Comment by adiaaida** [comment]
Feed is created and populated. 

Need to now make sure the check is happy with it. PR hopefully today.

**Comment by adiaaida** [comment]
PR: https://github.com/dotnet/arcade-services/pull/1924 (this was not a huge change)
