### ISSUE TITLE
Improve information for timed out tests

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/arcade#9598]
- [ ] This issue is blocking 
- [ ] This issue is causing unreasonable pain

When tests time out, I see a line like the following in the test console log:
```
['Methodical_d1' END OF WORK ITEM LOG: Command timed out, and was killed]
```

(for example, from:

https://dev.azure.com/dnceng/public/_build/results?buildId=1808337&view=ms.vss-test-web.build-test-results-tab&runId=48116984&resultId=110600&paneView=dotnet-dnceng.dnceng-build-release-tasks.helix-test-information-tab

console log:

https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-runtime-refs-pull-70271-merge-ec161464679f4f7d86/Methodical_d1/1/console.f7a67526.log?helixlogtype=result
)

Sometimes, for tests that aren't expected to run long enough to cause a timeout, it's very hard to determine why there is a problem. I often run these cases locally very quickly.

To help understand what is going on in the CI, it would be useful if more information was collected when there is a kill due to timeout, that might help debug such issues, namely:
1. a list of all the tasks running on the machine at the time. On Windows, e.g., the output of `tasklist`
2. a bitmap of the screen

These might help determine, for example, if there is a UI dialog that has popped up waiting for input, possibly from some kind of assertion failure.

@MattGal ?

**Comment by MattGal** [comment]
@BruceForstall we'll certainly discuss this one in triage this week.  Also, wow 4 hour timeouts, that's painful!

To quickly comment on these two bullet points:

1. List of tasks running on the machine: Fairly easy to implement, since there are python APIs for this, but not easy in the case of  the docker container where we're still waiting on the command(s) you asked us to run and we just kill the container when the timeout elapses if the `docker run` type invocation didn't finish.  Since your example scenario is docker, this might be a thing, unless it's more interesting getting the task list of what's running on the host.  
2. Bitmap of the screen:  This one gets real weird real fast.  The NVidia Tegra 2 machines running your test in a docker container don't have screens, so there's no way to get a screen grab of such a run.   We have an automated system in place on Windows for clicking modal dialogs so if you think it's that (on a Windows run, of course), I'd personally investigate.  On linux this just isn't possible.  I can assure you there were no graphics to capture running on the ubuntu VM inside Docker in this situation on the host or the container.

**Comment by BruceForstall** [comment]
> 4 hour timeouts, that's painful!

Some of our stress modes, e.g., GC stress, run _really_ slowly. It would be nice to break them up to run fewer tests on more machines. However, currently our test partitioning is static (I believe) and the same partitioning is used for both stress and non-stress runs.

In general, my ideas above are just guesses for information that _might_ help track down problems where a test leg times out. It doesn't preclude collecting other information, nor does it assure this information will help.

**Comment by MattGal** [comment]
We discussed this in triage today.  While this is something that would be goodness in general, it's significantly more difficult than one might expect to do in a general fashion and simply is not going to be funded any time soon, so I am closing the issue.

As a workaround, you could try what the runtime team does such as having an inner timeout, which if elapsed allows you to stop and note what's going on via Environment.FailFast making a dump or other means.  If you use the devtest lab to get a repro machine, and find we are failing to dismiss a dialog, that would absolutely be handled with high priority as well.  I'd be happy to try to help you hunt down some of these issues separately; my suspicion is more logging and a 2-core Azure repro VM could go a long way towards catching some of these hangs.
