### ISSUE TITLE
Test Reporting data discrepancies

### ISSUE THREAD

**Issue by missymessa** [dotnet/arcade#9650]
Using this query, it appears that we're not collecting any passing data for this particular test in ASPNETCore: 

```
let start = 30d;                   // Timespan value
let end = 10d;                     // Timespan value
let repo = "dotnet/aspnetcore";    // Optional: set to empty string if you want results from all repositories
let testName="Microsoft.AspNetCore.Mvc.FunctionalTests.SimpleWithWebApplicationBuilderTests.DefaultEnvironment_Is_Development";
AzureDevOpsTestsSummary
| where ReportDate >= ago(start) and ReportDate <= ago(end) and iff(repo == "", Repository == Repository, Repository == repo) and TestName == testName
```

However, looking at this report on Azure DevOps, it appears that the test has passed, and should be showing up in the data we're collecting: https://dev.azure.com/dnceng/public/_test/analytics?definitionId=278&contextType=build

We need to investigate why the passing test values are not being aggregated in our results.

**Comment by missymessa** [comment]
Related Teams thread: https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1654818742145?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1654818742145&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1654818742145

**Comment by dougbu** [comment]
Thanks @missymessa 👀

**Comment by ChadNedzlek** [comment]
If we have a passing build of the thing that didn't get included, we should be able to use the HelixAzureDevOpsMetadata to find the passing list file for the build, which should contain the test (or not).

**Comment by AlitzelMendez** [comment]
I am taking a look. This is one of the builds in which that test passed: https://dev.azure.com/dnceng/public/_build/results?buildId=1821448&view=ms.vss-test-web.build-test-results-tab&runId=48313542&resultId=118718&paneView=debug

**Comment by AlitzelMendez** [comment]
PR: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/23572

**Comment by dougbu** [comment]
I see the fix for this is rolling out tomorrow. How long will it take before the Kusto data has updated enough to provide correct numbers❔ If the answer is basically "data will start to accumulate tomorrow and beware of results from queries that reach further back", that makes sense but I wanted to confirm.

**Comment by missymessa** [comment]
@dougbu I would give it about a day. We have two jobs: one that runs every hour and another runs every day that do our aggregates.

@ChadNedzlek any additional advice for Doug?

**Comment by ChadNedzlek** [comment]
I believe @dougbu's guess is correct. We should start accumulating data at that point. We'll need to make sure our service handles the scale correctly, but it won't retroactively reach back in time much.  There's about a day where the data will stabilize because of aggregations and what not, so after a day, stuff should be complete going forward.
