### ISSUE TITLE
Longer machine-level caching certain payloads

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#970]
Helix should be able to specify certain correlation payloads as "long-lived" to reduce runtime. Examples of things we'd want to cache for a long time include the .NET Core runtime/CLI and XUnit.

**Comment by ChadNedzlek** [comment]
I'd like to see the data about the benefits here... in general, the Helix machines have incredibly fast pipes to our storage locations... we can upload 3Gb files in < 30 seconds...

The maintenance costs of this would almost certainly dwaraf any potential gains.  Especially since this will only help the first work item in a job... all the other work items will get the cache hit from the first work item.

I don't think we are at the stage of the product where shaving this handful of seconds is the right call.
