### ISSUE TITLE
Reporting issue with Helix Heartbeat table

### ISSUE THREAD

**Issue by ilyas1974** [dotnet/arcade#9788]
It appears that the heartbeat table is reporting incorrect data for the Galaxy Book 2 devices (windows.10.arm64v8.open queue).

The heartbeat table lists the OS version on the systems as 10.0.19041, the systems themselves return 10.0.19044 as the version (both in the UI and running the `ver` command on the system). 

The OSOB Inventory table reflect the true state of the operating systems, but we should investigate why this data is not being updated properly. My suspicion is that the field is populated only when the entry is created. While that is fine for VMs, for on premise systems that are persistent in the heartbeat table, we need to make sure we are updating this entry.

**Comment by MattGal** [comment]
>  My suspicion is that the field is populated only when the entry is created. 

This is incorrect.  The data is read fresh every 30 seconds with every heartbeat.  I am fairly certain this machine has decided that the version of python.exe running needs to be "lied to", most likely because the OS was updated from this previous version at some point.   If you need any help convincing yourself of this let me know and we'll do it together.

**Comment by ilyas1974** [comment]
Matt and I chatted about this and it looks like this is a limitation within Windows/Python. Basically, the python API we use is keyed to the version of Windows that is installed initially on the system. Subsequent updates are not registered within this function. The most accurate information around OS version for on-premise machines is within the OSOB Inventory table.
