### ISSUE TITLE
Runtime tests regularly hitting file locking issues in CI when writing test output

### ISSUE THREAD

**Issue by agocke** [dotnet/arcade#9864]
See https://github.com/dotnet/runtime/issues/70969.

Looks like it's not unique to runtime either, SDK tests were hitting the same problem: https://github.com/dotnet/sdk/issues/10062

|Build|Kind|Start Time|
|---|---|---|
[1885715](https://dev.azure.com/dnceng/public/_build/results?buildId=1885715)|Rolling|2022-16-07|

**Comment by agocke** [comment]
@markwilkie @Chrisboh

**Comment by Chrisboh** [comment]
@dotnet/dnceng we should have someone in FR take a look at this.

**Comment by markwilkie** [comment]
Curious what the latest is here?  I feel like we hit this issue before and have some insight into what's going on.

Also, it'll be good to get the known issue enabled for tests so we can track the impact of this kind of thing too.

**Comment by MattGal** [comment]
While it's true the .targets file implicated in the log is in Arcade, the exception is being thrown by [the WriteLinesToFile task](https://docs.microsoft.com/en-us/visualstudio/msbuild/writelinestofile-task?view=vs-2022), so we should probably loop in an MSBuild expert too like @rainersigwald and ask.

Reading the docs, I'd naively assume that just changing `Overwrite="false" ` -> `Overwrite="true" ` in that line could work as a fix but since it's explicitly set there may be some valid intent behind doing that.

**Comment by rainersigwald** [comment]
Is there a binlog of the build? Even a passing one? This sort of thing is _usually_ a build race condition, though with the write pattern here it could also be AV holding a lock on a just-written file and temporarily blocking further writes.

**Comment by MattGal** [comment]
> Is there a binlog of the build? Even a passing one? This sort of thing is _usually_ a build race condition, though with the write pattern here it could also be AV holding a lock on a just-written file and temporarily blocking further writes.

Shared binlog offline.  Given that these build agents all run Azure Security Pack now, that machines are created fresh-per-build, and that it tends to spin up and do a bunch of stuff on machine creation AV seems like a likely culprit.

**Comment by MattGal** [comment]
I brainstormed with @rainersigwald a bit offline.   We went over a representative binlog and didn't see any evidence of race conditions between different tasks trying to call WriteLinksToFile.

Some ideas for preventing this we touched on:

- Use exec and shell operations to append to the file, hoping the OS shell will do a better job, i.e. `<Exec Command="echo === COMMAND LINE === >> %(TestToRun.ResultsStdOutPath)" /> <Exec Command="echo $(_TestRunnerCommand)  >>  %(TestToRun.ResultsStdOutPath)" />`
- Write an Arcade-specific version of "WriteLinesToFile" with retry logic (easy but then has to be imported everywhere it's used)
- Remove the logging of test runner command (undesirable)

**Comment by rainersigwald** [comment]
Reading your list makes me think of another idea:

* Try switching the order, that is writing the command line first (to a tiny, hopefully easy-to-scan file), _then_ stream the test output into it.

**Comment by agocke** [comment]
One more option: capture the output of the test runner to a temporary buffer, then write all the output + the footer all at once.

**Comment by AraHaan** [comment]
> One more option: capture the output of the test runner to a temporary buffer, then write all the output + the footer all at once.

I like that option better.

**Comment by riarenas** [comment]
Once we are sure this fixes the issue, we should also make this change in the release/5.0 branch.

**Comment by karelz** [comment]
@jonfortescue is there rough estimate when it will propagate to runtime repo? It seems rather impactful there: https://github.com/dotnet/runtime/issues/70969

**Comment by agocke** [comment]
I merged an arcade update yesterday, so hopefully it’s already started having an effect.

**Comment by MattGal** [comment]
I checked into this, and runtime both has the change and has not had an instance of the problem since merging it:

- Currently runtime is on Microsoft.DotNet.Arcade.Sdk 7.0.0-beta.22372.1 (7/22/2022)
- [Last repro](https://dev.azure.com/dnceng/public/_build/results?buildId=1896299&view=logs&j=e36cdb78-1b23-5f53-5d15-e931194c7d32&t=5f3cc2c3-b299-5f57-0006-9e48b00ce7cd&l=734) was on 7.0.0-beta.22362.1 (7/12/2022)
- Change merged on 7/15/2022, so is between these versions.

I'll give this another day to see if it repros, then port the commit to the release branches as appropriate.

**Comment by AraHaan** [comment]
I think the change fixed it.

**Comment by MattGal** [comment]
Checked in on https://github.com/dotnet/runtime/issues/70969, looks that way to me as well.   I'll start porting now.

**Comment by MattGal** [comment]
- [ ] release 6.0: https://github.com/dotnet/arcade/pull/10146
- [ ] release 3.x: https://github.com/dotnet/arcade/pull/10147

**Comment by MattGal** [comment]
With the original PR merged and working for users in main, and both 3.x and 6.0 branches updated (noone's actively running enough to hit this in those branches AFAIK) I am optimistically closing this issue.
