### ISSUE TITLE
Arcade fails to build user-wide feeds have same key and are disabled

### ISSUE THREAD

**Issue by ericstj** [dotnet/arcade#987]
1. Create feeds in package manager settings named the same as https://github.com/dotnet/arcade/blob/f72dba1b9b94e1d8f03cbb30fc666ee2b187056c/NuGet.Config#L9-L10
2. Disable one of those feeds in settings.
3. run build.cmd (from a clean repo)

Expect: build succeeds and is isolated from user settings
Actual: build fails to restore

We should probably name the keys for feeds in the nuget.config with  more unique names.  We should also see if we can avoid the config layering that causes these to be disabled.  I believe this was one of the reasons we didn't rely on solely nuget.config for configuring feeds in CoreFx.

**Comment by tmat** [comment]
We only use nuget.config because of https://github.com/Microsoft/msbuild/issues/2982.

The feeds should be specified in https://github.com/dotnet/arcade/blob/master/eng/Versions.props#L55.

It's unclear to me how NuGet is supposed to work at this point. Seems like it is not possible today to isolate repo from NuGet.config settings outside of it :(.

**Comment by tmat** [comment]
No, the generated project does not use the props file. 

The problem is that there is currently no way to specify feed for imported SDK, other than nuget.config.
