### ISSUE TITLE
Consolidate build images

### ISSUE THREAD

**Issue by jonfortescue** [dotnet/arcade#9895]
We should consolidate our build images in helix-machines to lower operations costs.

This will require coordination with all product teams and hence is being categorized as a mini-epic.

### Release Note Description
The following images are being removed as a result of this work:

* build.server.amd64.vs2017(.open)
* build.windows.10.amd64.vs2017(.open)
* build.server.amd64.vs2019(.open)
* build.windows.10.amd64.vs2019(.open)
* build.windows.10.amd64.vs2019.pre(.open)
* build.windows.10.amd64.es.vs2017(.open)
* build.windows.amd64.vs2022(.open)
* build.windows.amd64.vs2022.scout(.open)
* build.windows.amd64.vs2022.pre(.open)
* build.windows.amd64.vs2022.pre.scout(.open)

Instead, please use one of the following images:

* windows.vs2017.amd64(.open)
* windows.vs2019.amd64(.open) OR 1es-windows-2019(-open)
* windows.vs2017.amd64.es(.open)
* windows.vs2022.amd64(.open) OR 1es-windows-2022(-open)
* windows.vs2022.scout.amd64(.open)
* windows.vs2022preview.amd64(.open)
* windows.vs2022preview.scout.amd64(.open)

**Comment by missymessa** [comment]
Due to https://github.com/dotnet/arcade/issues/11068, I'm taking the labels off this issue that would make it appear in the "Ongoing Critical Infrastructure" section of Build Analysis. We need to figure out a better way to do "announcements" to customers instead of using that section, because of the feedback we've been getting about it. 

Ongoing discussion here regarding the use of Ongoing Critical Infrastructure issues: https://github.com/dotnet/arcade/issues/10882

**Comment by jonfortescue** [comment]
PR in for this [here](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-machines/pullrequest/26853).

**Comment by jonfortescue** [comment]
Build images consolidated!
